-- Copyright The Total RP 3 Authors
-- SPDX-License-Identifier: Apache-2.0

TRP3_DROPDOWN_MENU_POINT = "TOPLEFT";
TRP3_DROPDOWN_MENU_OFFSET_X = 0;
TRP3_DROPDOWN_MENU_OFFSET_Y = 0;
TRP3_DROPDOWN_MENU_RELATIVE_POINT = "BOTTOMLEFT";
