-- Copyright The Total RP 3 Authors
-- SPDX-License-Identifier: Apache-2.0

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- ALL MODIFICATIONS TO THIS FILE WILL BE LOST.

local _, TRP3_API = ...;

local L;

L = {
	["ABOUT_TITLE"] = "Über",
	["BW_COLOR_CODE"] = "Farbcode",
	["BW_COLOR_CODE_ALERT"] = "Falscher hexadezimaler Farbcode!",
	["BW_COLOR_PRESET_SAVE"] = "Aktuelle Farbe speichern",
	["CL_IMPORT_PROFILE"] = "Profil importieren",
	["CM_ACTIONS"] = "Aktionen",
	["CM_APPLY"] = "Übernehmen",
	["CM_CANCEL"] = "Abbrechen",
	["CM_CENTER"] = "Zentriert",
	["CM_CLASS_DEATHKNIGHT"] = "Todesritter",
	["CM_CLASS_DRUID"] = "Druide",
	["CM_CLASS_HUNTER"] = "Jäger",
	["CM_CLASS_MAGE"] = "Magier",
	["CM_CLASS_MONK"] = "Mönch",
	["CM_CLASS_PALADIN"] = "Paladin",
	["CM_CLASS_PRIEST"] = "Priester",
	["CM_CLASS_ROGUE"] = "Schurke",
	["CM_CLASS_SHAMAN"] = "Schamane",
	["CM_CLASS_UNKNOWN"] = "Unbekannt",
	["CM_CLASS_WARLOCK"] = "Hexenmeister",
	["CM_CLASS_WARRIOR"] = "Krieger",
	["CM_CLICK"] = "Klicken",
	["CM_COLOR"] = "Farbe",
	["CM_DRAGDROP"] = "Drag & Drop",
	["CM_ICON"] = "Icon",
	["CM_IMAGE"] = "Bild",
	["CM_LEFT"] = "Links",
	["CM_LINK"] = "Link",
	["CM_NAME"] = "Name",
	["CM_RIGHT"] = "Rechts",
	["CM_UNKNOWN"] = "Unbekannt",
	["CO_ANCHOR_LEFT"] = "Links",
	["CO_ANCHOR_RIGHT"] = "Rechts",
	["COM_LIST"] = "Liste aller Befehle:",
	["GEN_WELCOME_MESSAGE"] = "Danke, dass du Total RP 3 (v %s) verwendest! Viel Spaß!"
};

TRP3_API.loc:RegisterNewLocale("deDE", "Deutsch", L);
