-- Copyright The Total RP 3 Authors
-- SPDX-License-Identifier: Apache-2.0

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- ALL MODIFICATIONS TO THIS FILE WILL BE LOST.

local _, TRP3_API = ...;

local L;

L = {
	["ABOUT_TITLE"] = "Über",
	["BINDING_NAME_TRP3_TOGGLE"] = "Hauptfenster umschalten",
	["BINDING_NAME_TRP3_TOOLBAR_TOGGLE"] = "Werkzeugleiste umschalten",
	["BROADCAST_10"] = "|cffff9900Du bist bereits in zehn Channels. TRP3 wird nicht mehr versuchen sich mit dem Broadcast-Kanal zu verbinden, aber du wirst nicht in der LAge sein einige Funktionen, wie die Spielersuche auf der Karte, zu verwenden.",
	["BROADCAST_OFFLINE_DISABLED"] = "Broadcast wurde deaktiviert.",
	["BROADCAST_PASSWORD"] = [=[|cffff0000Der Übertragungs-Channel (%s) ist passwortgeschützt.
|cffff9900TRP3 wird nicht versuchen, sich zu verbinden, kann jedoch auch keine Features wie die Standortbestimmung von Spielern auf der Karte für dich bereitstellen.
|cff00ff00Du kannst den Übertragungs-Channel in den Allgemeinen Einstellungen von TRP3 ausschalten oder ändern.]=],
	["BROADCAST_PASSWORDED"] = [=[|cffff0000Der Benutzer|r %s|cffff0000 hat gerade ein Passwort für den Übertragungs-Channel (%s) festgelegt.
|cffff9900Wenn du das Passwort nicht kennst, kannst du keine Funktionen nutzen, die in Zusammenhang mit dem Channel stehen, wie etwa der Standortbestimmung von Spielern auf der Karte.]=],
	["BW_COLOR_CODE"] = "Farbcode",
	["BW_COLOR_CODE_ALERT"] = "Falscher hexadezimaler Farbcode!",
	["BW_COLOR_CODE_TT"] = "Hier kannst du 6 Zeichen hexadezimalen Farbcode eintragen und mit ENTER bestätigen.",
	["BW_COLOR_PRESET_DELETE"] = "Voreinstellungen %s löschen.",
	["BW_COLOR_PRESET_RENAME"] = "Voreinstellungen %s umbenennen.",
	["BW_COLOR_PRESET_SAVE"] = "Aktuelle Farbe speichern",
	["BW_COLOR_PRESET_TITLE"] = "Farben Voreinstellungen",
	["BW_CUSTOM_NAME"] = "Eigener Farbname",
	["BW_CUSTOM_NAME_TITLE"] = "Name (Optional)",
	["BW_CUSTOM_NAME_TT"] = "Du kannst der eigenen Farbe, die du speicherst, einen Namen geben. Wenn du sie nicht benennst wird der hexadezimale Farbcode verwendet.",
	["CL_COMPANION_PROFILE"] = "Begleiterprofil",
	["CL_CONTENT_SIZE"] = "Größe: %s",
	["CL_DIRECTORY_COMPANION_PROFILE"] = "Begleiter Profil Verzeichnis",
	["CL_DIRECTORY_PLAYER_PROFILE"] = "Spieler Profil Verzeichnis",
	["CL_DOWNLOADING"] = "Lade Herunter: %0.1f %%",
	["CL_EXPIRED"] = "Dieser Link ist abgelaufen.",
	["CL_GLANCE"] = "Auf den ersten Blick",
	["CL_IMPORT_COMPANION"] = "Begleiterprofil importieren",
	["CL_IMPORT_GLANCE"] = "Importiere \"Auf den ersten Blick\"",
	["CL_IMPORT_PROFILE"] = "Profil importieren",
	["CL_MAKE_IMPORTABLE_BUTTON_TEXT"] = "Importierbar machen",
	["CL_MAKE_IMPORTABLE_SIMPLER"] = [=[Diesen %s Link importierbar machen?

Andere Leute können den Inhalt des Links kopieren und nutzen.]=],
	["CL_MAKE_NON_IMPORTABLE"] = "Nur Ansehbar",
	["CL_OPEN_COMPANION"] = "Begleiterprofil öffnen",
	["CL_OPEN_PROFILE"] = "Profil öffnen",
	["CL_PLAYER_PROFILE"] = "Spielerprofil",
	["CL_REQUESTING_DATA"] = "Frage Datenverbindung von %s an.",
	["CL_SENDING_COMMAND"] = "Sende Befehl...",
	["CL_SENT_BY"] = "Link gesendet von: %s",
	["CL_TOOLTIP"] = "Erstelle einen Chat-Link",
	["CL_VERSIONS_DIFFER"] = [=[Dieser Link wurde mit einer anderen Version von Total RP 3 generiert.

Das Importieren des Inhaltes einer anderen Version könnte aufgrund von Inkompatibilitäten zu Problemen führen. Möchtest Du dennoch fortfahren?]=],
	["CM_ACTIONS"] = "Aktionen",
	["CM_ALT"] = "Alt",
	["CM_APPLY"] = "Übernehmen",
	["CM_BLACK"] = "Schwarz",
	["CM_BLUE"] = "Blau",
	["CM_CANCEL"] = "Abbrechen",
	["CM_CENTER"] = "Zentriert",
	["CM_CLASS_DEATHKNIGHT"] = "Todesritter",
	["CM_CLASS_DEMONHUNTER"] = "Dämonenjäger",
	["CM_CLASS_DRUID"] = "Druide",
	["CM_CLASS_HUNTER"] = "Jäger",
	["CM_CLASS_MAGE"] = "Magier",
	["CM_CLASS_MONK"] = "Mönch",
	["CM_CLASS_PALADIN"] = "Paladin",
	["CM_CLASS_PRIEST"] = "Priester",
	["CM_CLASS_ROGUE"] = "Schurke",
	["CM_CLASS_SHAMAN"] = "Schamane",
	["CM_CLASS_UNKNOWN"] = "Unbekannt",
	["CM_CLASS_WARLOCK"] = "Hexenmeister",
	["CM_CLASS_WARRIOR"] = "Krieger",
	["CM_CLICK"] = "Klicken",
	["CM_COLOR"] = "Farbe",
	["CM_CTRL"] = "Strg",
	["CM_CYAN"] = "Türkis",
	["CM_DELETE"] = "Löschen",
	["CM_DOUBLECLICK"] = "Doppelklick",
	["CM_DRAGDROP"] = "Drag & Drop",
	["CM_EDIT"] = "Bearbeiten",
	["CM_GREEN"] = "Grün",
	["CM_GREY"] = "Grau",
	["CM_IC"] = "IC",
	["CM_ICON"] = "Icon",
	["CM_IMAGE"] = "Bild",
	["CM_L_CLICK"] = "Links-Klick",
	["CM_LEFT"] = "Links",
	["CM_LINK"] = "Link",
	["CM_LOAD"] = "Laden",
	["CM_M_CLICK"] = "Mittel-Klick",
	["CM_MOVE_DOWN"] = "Nach unten",
	["CM_MOVE_UP"] = "Nach oben",
	["CM_NAME"] = "Name",
	["CM_OOC"] = "OOC",
	["CM_OPEN"] = "Öffnen",
	["CM_ORANGE"] = "Orange",
	["CM_PINK"] = "Pink",
	["CM_PLAY"] = "Abspielen",
	["CM_PURPLE"] = "Lila",
	["CM_R_CLICK"] = "Rechts-Klick",
	["CM_RED"] = "Rot",
	["CM_REMOVE"] = "Entfernen",
	["CM_RESET"] = "Zurücksetzen",
	["CM_RESIZE"] = "Größe ändern",
	["CM_RESIZE_TT"] = "Ziehen um die Rahmengröße zu ändern.",
	["CM_RIGHT"] = "Rechts",
	["CM_SAVE"] = "Speichern",
	["CM_SELECT"] = "Auswählen",
	["CM_SHIFT"] = "Umschalttaste",
	["CM_SHOW"] = "Anzeigen",
	["CM_STOP"] = "Anhalten",
	["CM_TWEET"] = "Einen Tweet senden",
	["CM_TWEET_PROFILE"] = "Profil-URL zeigen",
	["CM_UNKNOWN"] = "Unbekannt",
	["CM_VALUE"] = "Wert",
	["CM_WHITE"] = "Weiß",
	["CM_YELLOW"] = "Gelb",
	["CO_ADVANCED_BROADCAST"] = "Add-on Kommunikationen",
	["CO_ADVANCED_BROADCAST_CHANNEL_ALWAYS_LAST"] = "Broadcast-Kanal as Ende setzen",
	["CO_ADVANCED_BROADCAST_CHANNEL_ALWAYS_LAST_TT"] = "Durch diese Option bleibt dieser Kanal immer der letzte in Eurer Kanalliste.",
	["CO_ADVANCED_LANGUAGE_WORKAROUND"] = "Provisorische Lösung für das Rücksetzen der Sprache",
	["CO_ADVANCED_LANGUAGE_WORKAROUND_TT"] = "Seit Patch 8.0.1 setzt das Spiel die ausgewählte Sprache nach jedem Ladebildschirm zur Standardsprache Eurer Fraktion zurück. Diese Überbrückung sorgt dafür, dass Eure Sprache nach einem Ladebildschirm weiterhin ausgewählt bleibt.",
	["CO_ADVANCED_LANGUAGES"] = "Sprachen",
	["CO_ADVANCED_LANGUAGES_REMEMBER"] = "Letzte benutzte Sprache speichern",
	["CO_ADVANCED_LANGUAGES_REMEMBER_TT"] = "Total RP 3 wird die letzte Sprache, die du vor dem ausloggen benutzt hast speichern und beim nächsten Login automatisch wieder aktivieren.",
	["CO_ADVANCED_SETTINGS"] = "Erweiterte Einstellungen",
	["CO_ADVANCED_SETTINGS_MENU_NAME"] = "Erweitert",
	["CO_ADVANCED_SETTINGS_POPUP"] = "Ihr habt eine erweiterte Einstellung verändert. Bitte denkt daran, dass diese Einstellungen Eure Spielerfahrungen mit dem Add-on beeinflussen und diverse Funktionen daran hindern können korrekt zu funktionieren. Benutzung auf eigene Gefahr.",
	["CO_ADVANCED_SETTINGS_RESET"] = "Erweiterte Einstellungen zurücksetzen",
	["CO_ADVANCED_SETTINGS_RESET_TT"] = "Sämtliche erweiterte Einstellungen zurücksetzen. Nutzt dies falls Ihr Probleme habt, nachdem Ihr die Einstellungen verändert habt.",
	["CO_ANCHOR_BOTTOM"] = "Unten",
	["CO_ANCHOR_BOTTOM_LEFT"] = "Unten Links",
	["CO_ANCHOR_BOTTOM_RIGHT"] = "Unten Rechts",
	["CO_ANCHOR_CURSOR"] = "Am Mauszeiger anzeigen",
	["CO_ANCHOR_LEFT"] = "Links",
	["CO_ANCHOR_RIGHT"] = "Rechts",
	["CO_ANCHOR_TOP"] = "Oben",
	["CO_ANCHOR_TOP_LEFT"] = "Oben Links",
	["CO_ANCHOR_TOP_RIGHT"] = "Oben Rechts",
	["CO_CHAT"] = "Chat-Einstellungen",
	["CO_CHAT_DISABLE_OOC"] = "Deaktiviere Anpassungen wenn Ihr OOC seid",
	["CO_CHAT_DISABLE_OOC_TT"] = "Deaktiviere alle Total RP 3 Chatanpassungen (benutzerdefinierte Namen, Emote-Erkennung, NPC-Reden, etc.), wenn dein Charakter als \"Out Of Character\" markiert ist.",
	["CO_CHAT_INCREASE_CONTRAST"] = "Farbkontrast erhöhen",
	["CO_CHAT_INSERT_FULL_RP_NAME"] = "RP-Namen bei Shift-Klick einfügen",
	["CO_CHAT_INSERT_FULL_RP_NAME_TT"] = [=[Füge den kompletten RP namen eines Spielers in den Chat ein, wenn auf seinen Namen Shift-geklickt wird.

(Wenn diese Option eingeschaltet ist, kannst du mit Alt-Shift auf einen Namen klicken wenn du das ursprüngliche Verhalten verwenden möchtest und den Charakternamen statt den vollständigen RP-Namen einfügen möchtest.)]=],
	["CO_CHAT_MAIN"] = "Chat-Haupteinstellungen",
	["CO_CHAT_MAIN_COLOR"] = "Benutzerdefinierte Farben für Namen",
	["CO_CHAT_MAIN_EMOTE"] = "Emote-Erkennung",
	["CO_CHAT_MAIN_EMOTE_PATTERN"] = "Vorlage zur Emote-Erkennung",
	["CO_CHAT_MAIN_EMOTE_USE"] = "Brnütze Emote-Erkennung",
	["CO_CHAT_MAIN_EMOTE_YELL"] = "Keine geschriehenen Emotes",
	["CO_CHAT_MAIN_EMOTE_YELL_TT"] = "Im Schreien Channel *emote* oder <emote> nicht zeigen.",
	["CO_CHAT_MAIN_NAMING"] = "Benennungsmethode",
	["CO_CHAT_MAIN_NAMING_1"] = "Originalnamen beibehalten",
	["CO_CHAT_MAIN_NAMING_2"] = "Angepasste Namen verwenden",
	["CO_CHAT_MAIN_NAMING_3"] = "Vorname + Nachname",
	["CO_CHAT_MAIN_NAMING_4"] = "Kurztitel + Vorname + Nachname",
	["CO_CHAT_MAIN_NPC"] = "NSC-Spracherkennung",
	["CO_CHAT_MAIN_NPC_PREFIX"] = "Muster für NSC-Spracherkennung",
	["CO_CHAT_MAIN_NPC_PREFIX_TT"] = [=[Wenn eine Chatnachricht im Emotekanal mit diesem Zeichen startet, wird sie als NSC-Nachricht interpretiert.

|cff00ff00Voreingestellt : "|| "
(ohne die " und mit einem Leerzeichen nach dem Strich)]=],
	["CO_CHAT_MAIN_NPC_USE"] = "Nutze NSC-Spracherkennung",
	["CO_CHAT_MAIN_OOC"] = "OOC-Erkennung",
	["CO_CHAT_MAIN_OOC_COLOR"] = "OOC-Farbe",
	["CO_CHAT_MAIN_OOC_PATTERN"] = "Muster für OOC-Erkennung",
	["CO_CHAT_MAIN_OOC_USE"] = "Nutze OOC-Erkennung",
	["CO_CHAT_MAIN_SPEECH"] = "Spracherkennung",
	["CO_CHAT_MAIN_SPEECH_USE"] = "Spracherkennung benutzen",
	["CO_CHAT_MAIN_SPEECH_USE_TT"] = "Text in Anführungszeichen wird eingefärbt als wäre er im /say geschrieben.",
	["CO_CHAT_NPCSPEECH_REPLACEMENT"] = "Begleitername in NSC Sprache anpassen",
	["CO_CHAT_NPCSPEECH_REPLACEMENT_TT"] = "Wenn der Begleitername in der NSC Sprache in Klammern eingesetzt wird, wird er eingefärbt und es wird, je nach Einstellung, ein Icon angezeigt.",
	["CO_CHAT_REMOVE_REALM"] = "Spielernamen ohne Servernamen zeigen",
	["CO_CHAT_SHOW_OOC"] = "OOC Indikator anzeigen",
	["CO_CHAT_USE"] = "Benutze Chatkanäle",
	["CO_CHAT_USE_ICONS"] = "Spielersymbole anzeigen",
	["CO_CHAT_USE_SAY"] = "Sagen-Kanal",
	["CO_CONFIGURATION"] = "Einstellungen",
	["CO_CURSOR_DISABLE_OOC"] = "Während OOC deaktiviert",
	["CO_CURSOR_DISABLE_OOC_TT"] = "Deaktiviert Modifikationen vom Cursor während dein Rollenspielstatus |cffccccccOut Of Character|r ist.",
	["CO_CURSOR_MODIFIER_KEY"] = "Modifiziertaste",
	["CO_CURSOR_RIGHT_CLICK"] = "Rechtsklick um Profil zu öffnen",
	["CO_CURSOR_RIGHT_CLICK_TT"] = [=[Rechtsklick auf einen Spieler in der 3D Welt, wird sein Profil öffnen, falls er eines besitzt.

|TInterface\Cursor\WorkOrders:25|t Dieses Symbol wird an dem Mauszeiger angeheftet, wenn ein Spieler ein Profil hat und Ihr es rechtsklicken könnt.

|cffccccccNote: Diese Funktion wird während eines Kampfes deaktiviert.|r]=],
	["CO_CURSOR_TITLE"] = "Cursorinteraktionen",
	["CO_GENERAL"] = "Allgemeine Einstellungen",
	["CO_GENERAL_BROADCAST"] = "Broadcast-Kanal nutzen",
	["CO_GENERAL_BROADCAST_C"] = "Names des Broadcast-Kanals",
	["CO_GENERAL_BROADCAST_TT"] = "Der Broadcast-Kanal wird für viele Funktionen genutzt. Durch das Deaktivieren werden Funktionen wie die Charakterposition auf der Karte, Abspielen lokaler Klänge usw. deaktivert.",
	["CO_GENERAL_CHANGELOCALE_ALERT"] = [=[Interface neu laden, um die Sprache jetzt auf %s zu ändern?

Wenn nicht, wird die Sprache beim nächsten Login geändert.]=],
	["CO_GENERAL_COM"] = "Kommunikation",
	["CO_GENERAL_DEFAULT_COLOR_PICKER"] = "Standard Farbauswahl",
	["CO_GENERAL_DEFAULT_COLOR_PICKER_TT"] = "Aktivieren, um immer die Standard Farbauswahl zu nutzen. Nützlich, wenn du ein Farbauswahl-Addon benutzt.",
	["CO_GENERAL_HEAVY"] = "Warnung bei überlangem Profil",
	["CO_GENERAL_HEAVY_TT"] = "Gibt dir einen Warnhinweis, wenn dein Profil eine verträgliche Größe überschreitet.",
	["CO_GENERAL_LOCALE"] = "Sprache des Addons",
	["CO_GENERAL_MISC"] = "Verschiedenes",
	["CO_GENERAL_NEW_VERSION"] = "Aktualisierungshinweis",
	["CO_GENERAL_NEW_VERSION_TT"] = "Gibt dir einen Hinweis, sobald eine neue Version verfügbar ist.",
	["CO_GENERAL_RESET_CUSTOM_COLORS"] = "Benutzerdefinierte Farben zurücksetzen",
	["CO_GENERAL_RESET_CUSTOM_COLORS_TT"] = "Entfernt alle in der Farbauswahl gespeicherten benutzerdefinierten Farben.",
	["CO_GENERAL_RESET_CUSTOM_COLORS_WARNING"] = "Bist du sicher, dass du alle in der Farbauswahl gespeicherten benutzerdefinierten Farben entfernen möchtest?",
	["CO_GENERAL_TT_SIZE"] = "Textgröße des Informationstooltips",
	["CO_GENERAL_UI_ANIMATIONS"] = "Interface-Animationen",
	["CO_GENERAL_UI_ANIMATIONS_TT"] = "Aktiviert die Interface-Animationen.",
	["CO_GENERAL_UI_SOUNDS"] = "Interface-Klänge",
	["CO_GENERAL_UI_SOUNDS_TT"] = "Aktivert die Interface-Klänge (beim Öffnen von Fenstern, Wechseln zwischen Reitern und Klicken auf Schaltflächen).",
	["CO_GLANCE_LOCK"] = "Leiste fixieren",
	["CO_GLANCE_LOCK_TT"] = "Verhindert, dass die Leiste verschoben wird.",
	["CO_GLANCE_MAIN"] = "\"Auf den ersten Blick\"-Leiste",
	["CO_GLANCE_PRESET_TRP2"] = "Benutze Positionen im Total RP 2 Stil",
	["CO_GLANCE_PRESET_TRP2_BUTTON"] = "Benutzen",
	["CO_GLANCE_PRESET_TRP2_HELP"] = "Verknüpfung, um die Leiste im TRP2-Stil zu konfigurieren – am rechten Rand des WoW-Zielfensters.",
	["CO_GLANCE_PRESET_TRP3"] = "Benutze Positionen im Total RP 3 Stil",
	["CO_GLANCE_PRESET_TRP3_HELP"] = "Verknüpfung um die Zeile im TRP3 Stil aufzusetzen - Am unteren Rand des TRP3 Zielfensters.",
	["CO_GLANCE_RESET_TT"] = "Setze die Leiste auf die untere linke Position des Ankerfensters zurück.",
	["CO_GLANCE_TT_ANCHOR"] = "Ankerpunkt des Tooltips",
	["CO_HIDE_EMPTY_MAP_BUTTON"] = "Ausblenden wenn keine Scans verfügbar sind.",
	["CO_LOCATION"] = "Standorteinstellungen",
	["CO_LOCATION_ACTIVATE"] = "Charakterstandort aktivieren",
	["CO_LOCATION_ACTIVATE_TT"] = "Aktivieren das Charakterstandortsystem, welches erlaubt auf der Weltkarte nach anderen Total RP-Nutzern zu suchen und ihnen erlaubt dich zu finden.",
	["CO_LOCATION_DISABLE_CLASSIC_PVP"] = "Standort deaktivieren, wenn PvP an ist. ",
	["CO_LOCATION_DISABLE_CLASSIC_PVP_TT"] = "Solange PvP aktiv ist, wirst du bei Scans nicht auf der Karte angezeigt. Nützlich, wenn du Missbrauch des Systems um dich zu verfolgen vermeiden willst.",
	["CO_LOCATION_DISABLE_OOC"] = "Standort deaktivieren wenn OOC",
	["CO_LOCATION_DISABLE_OOC_TT"] = "Du wirst keine Antworten auf Standortanfragen anderer Spieler senden wenn dein RP Status auf Out Of Charakter gesetzt ist.",
	["CO_LOCATION_DISABLE_WAR_MODE"] = "Standort deaktivieren, wenn der Kriegsmodus an ist. ",
	["CO_LOCATION_DISABLE_WAR_MODE_TT"] = "Solange der Kriegsmodus aktiv ist und du dich nicht in einer Ruhe-Zone bist, wirst du bei Scans nicht auf der Karte angezeigt. Nützlich, wenn du Missbrauch des Systems um dich zu verfolgen vermeiden willst.",
	["CO_LOCATION_SHOW_DIFFERENT_WAR_MODES"] = "Zeige Spieler mit anderem Kriegsmodus.",
	["CO_LOCATION_SHOW_DIFFERENT_WAR_MODES_TT"] = "Spieler die zur Zeit in dem Gebiet sind, aber einen anderen Kriegsmodus-Status als Ihr haben, werden mit weniger Deckkraft auf der Karte angezeigt und bekommen ein spezielles Symbol im Tooltip.",
	["CO_MAP_BUTTON"] = "Kartenscan-Button",
	["CO_MAP_BUTTON_POS"] = "Position des Scan-Buttons auf der Karte",
	["CO_MINIMAP_BUTTON"] = "Minimap Button",
	["CO_MINIMAP_BUTTON_FRAME"] = "Ankerfenster",
	["CO_MINIMAP_BUTTON_RESET"] = "Position zurücksetzen",
	["CO_MINIMAP_BUTTON_RESET_BUTTON"] = "Zurücksetzen",
	["CO_MINIMAP_BUTTON_SHOW_HELP"] = "Wenn du ein anderes Add-On verwendest um Total RP 3's Minimap-Schaltfläche anzuzeigen (FuBar, Titan, Bazooka) kannst du die Schaltfläche von der Minimap entfernen.",
	["CO_MINIMAP_BUTTON_SHOW_TITLE"] = "Zeige Minimap-Button",
	["CO_MODULES"] = "Modulstatus",
	["CO_MODULES_DISABLE"] = "Deaktiviere Modul",
	["CO_MODULES_ENABLE"] = "Aktiviere Modul",
	["CO_MODULES_ID"] = "Modul ID: %s",
	["CO_MODULES_SHOWERROR"] = "Zeige Fehler",
	["CO_MODULES_STATUS"] = "Status: %s",
	["CO_MODULES_STATUS_0"] = "Fehlende Abhängigkeiten",
	["CO_MODULES_STATUS_1"] = "Geladen",
	["CO_MODULES_STATUS_2"] = "Deaktivert",
	["CO_MODULES_STATUS_3"] = "Total RP 3 Aktualisierung benötigt",
	["CO_MODULES_STATUS_4"] = "Fehler bei der Initialisierung",
	["CO_MODULES_STATUS_5"] = "Fehler beim Start",
	["CO_MODULES_TT_DEP"] = "%s- %s (version %s)|r",
	["CO_MODULES_TT_DEPS"] = "Abhängigkeiten",
	["CO_MODULES_TT_ERROR"] = [=[
|cffff0000Fehler:|r
%s]=],
	["CO_MODULES_TT_NONE"] = "Keine Abhängigkeiten",
	["CO_MODULES_TT_TRP"] = "%sFür Total RP 3 build %s minimum.|r",
	["CO_MODULES_TUTO"] = [=[Ein Modul ist eine unabhängige Funktion, die aktiviert oder deaktiviert werden kann.

Möglicher Status:
|cff00ff00Geladen:|r Modul aktiviert und geladen.
|cff999999Deaktiviert:|r Modul deaktiviert.
|cffff9900Fehlende Abhängigkeiten:|r Einige Abhängigkeiten sind nicht geladen/verfügbar.
|cffff9900TRP Update benötigt:|r Diese Modul benötigt eine aktueller Version von TRP3.
|cffff0000Fehler beim Inizialisieren oder Starten:|r Der Start des Moduls hat nicht funktioniert. Das Modul würde sicher Fehler verursachen!

|cffff9900Wenn ein Modul deaktivert wird muss das UI neu geladen werden!]=],
	["CO_MODULES_VERSION"] = "Version: %s",
	["CO_MSP"] = "Mary Sue Protocol",
	["CO_REGISTER"] = "Einstellungen registrieren",
	["CO_REGISTER_AUTO_PURGE"] = "Verzeichnis automatisch bereinigen",
	["CO_REGISTER_AUTO_PURGE_0"] = "Bereinigung abschalten",
	["CO_REGISTER_AUTO_PURGE_1"] = "Nach %s Tag(en)",
	["CO_REGISTER_AUTO_PURGE_TT"] = [=[Entferne automatisch die Profile von Charakteren aus dem Verzeichnis, denen du seit einer bestimmten Zeit nicht mehr begegnet bist. Du eine Verzögerung vor der Löschung auswählen.
|cff00ff00Beachte dass Profile mit einem Verhältnis zu einem deiner Charaktere niemals bereinigt werden.
|cffff9900 Es gibt einen Bug in WoW bei dem alle gespeicherten Daten verloren gehen, wenn ein bestimmtes Limit überschritten wird. Wir raten eindringlich davon ab das Bereinigungssystem abzuschalten.

]=],
	["CO_SANITIZER"] = "Zensiere eingehende Profile",
	["CO_SANITIZER_TT"] = "Entfernt benutzerdefinierte Kommandos in Tooltips von neuen Profilen, wenn TRP diese nicht gestattet. ( Farben, Bilder ...)",
	["CO_TARGETFRAME"] = "Zielfenstereinstellungen",
	["CO_TARGETFRAME_ICON_SIZE"] = "Icongröße",
	["CO_TARGETFRAME_USE"] = "Anzeigebedingungen",
	["CO_TARGETFRAME_USE_1"] = "Immer",
	["CO_TARGETFRAME_USE_2"] = "Nur wenn IC",
	["CO_TARGETFRAME_USE_3"] = "Niemals (Deaktiviert)",
	["CO_TARGETFRAME_USE_TT"] = "Gibt an, unter welchen Bedingungen das Zielfenster am gewählten Ziel gezeigt werden soll.",
	["CO_TOOLBAR"] = "Fenstereinstellungen",
	["CO_TOOLBAR_CONTENT"] = "Toolbareinstellungen",
	["CO_TOOLBAR_CONTENT_CAPE"] = "Umhang an/aus",
	["CO_TOOLBAR_CONTENT_HELMET"] = "Helm an/aus",
	["CO_TOOLBAR_CONTENT_RPSTATUS"] = "Charakterstatus (IC/OOC)",
	["CO_TOOLBAR_CONTENT_STATUS"] = "Spielerstatus (AFK/DND)",
	["CO_TOOLBAR_HIDE_TITLE"] = "Verstecke Werkzeugleistentitel",
	["CO_TOOLBAR_HIDE_TITLE_HELP"] = "Versteckt den Titel, der über der Werkzeugleiste angezeigt wird.",
	["CO_TOOLBAR_ICON_SIZE"] = "Icongröße",
	["CO_TOOLBAR_MAX"] = "Maximale Icons pro Zeile",
	["CO_TOOLBAR_MAX_TT"] = "Auf 1 stellen wenn du die Leiste vertikal angezeigt haben möchtest!",
	["CO_TOOLBAR_SHOW_ON_LOGIN"] = "Zeige Toolbar beim Login",
	["CO_TOOLBAR_SHOW_ON_LOGIN_HELP"] = "Wenn du nicht möchtest, dass die Toolbar beim Login erscheint, deaktiviere diese Option.",
	["CO_TOOLTIP"] = "Tooltipeinstellungen",
	["CO_TOOLTIP_ANCHOR"] = "Ankerpunkt",
	["CO_TOOLTIP_ANCHORED"] = "Ankerfenster",
	["CO_TOOLTIP_CHARACTER"] = "Charaktertooltip",
	["CO_TOOLTIP_CLIENT"] = "Zeige Client",
	["CO_TOOLTIP_COLOR"] = "Benutzerdefinierte Farben anzeigen",
	["CO_TOOLTIP_COMBAT"] = "Während des Kampfs verbergen",
	["CO_TOOLTIP_COMMON"] = "Standardeinstellungen",
	["CO_TOOLTIP_CONTRAST"] = "Farbkontraste erhöhen",
	["CO_TOOLTIP_CONTRAST_TT"] = "Schalte diese Option ein um Total RP 3 zu erlauben die benutzerdefinierten Farben zu verändern, so dass Text in zu dunklen Farben leichter lesbar ist.",
	["CO_TOOLTIP_CROP_TEXT"] = "Ungerechtfertigt lange Texte kürzen",
	["CO_TOOLTIP_CROP_TEXT_TT"] = [=[Begrenze die Zeichenanzahl die im Tooltip für jedes Feld angezeigt werden kann um ungerechtfertigt lange Texte und mögliche Layoutprobleme zu verhindern.

|cfffff569Limit Details:
Name: 100 Zeichen
Titel: 150 Zeichen
Volk: 50 Zeichen
Klasse: 50 Zeichen|r]=],
	["CO_TOOLTIP_CURRENT"] = "Zeige \"aktuelle\" Informationen",
	["CO_TOOLTIP_CURRENT_LINES"] = "Maximale Zeilen unter \"Aktuelles\"",
	["CO_TOOLTIP_CURRENT_SIZE"] = "Maximale Länge von \"aktuellen\" Informationen",
	["CO_TOOLTIP_FT"] = "Zeige vollen Titel",
	["CO_TOOLTIP_GUILD"] = "Zeige Gildeninformationen",
	["CO_TOOLTIP_HIDE_ORIGINAL"] = "Verstecke Originaltooltip",
	["CO_TOOLTIP_ICONS"] = "Zeige Icons",
	["CO_TOOLTIP_IN_CHARACTER_ONLY"] = "Verbergen wenn Out Of Character",
	["CO_TOOLTIP_MAINSIZE"] = "Hauptschriftgröße",
	["CO_TOOLTIP_NO_FADE_OUT"] = "Sofort ausblenden anstatt verblassen",
	["CO_TOOLTIP_NOTIF"] = "Zeige Benachrichtigungen",
	["CO_TOOLTIP_NOTIF_TT"] = "Die Benachrichtigungszeile enthält die Clientversion, den Marker für ungelesene Beschreibungen und die \"Auf den Ersten Blick\" Leiste.",
	["CO_TOOLTIP_OWNER"] = "Zeige Besitzer",
	["CO_TOOLTIP_PETS"] = "Begleitertooltip",
	["CO_TOOLTIP_PETS_INFO"] = "Zeige Begleiterinformationen",
	["CO_TOOLTIP_PREFERRED_OOC_INDICATOR"] = "Bevorzugter OOC Indikator.",
	["CO_TOOLTIP_PREFERRED_OOC_INDICATOR_ICON"] = "Icon:",
	["CO_TOOLTIP_PREFERRED_OOC_INDICATOR_TEXT"] = "Text:",
	["CO_TOOLTIP_PROFILE_ONLY"] = "Nur benutzen, wenn das Ziel ein Profil hat",
	["CO_TOOLTIP_RACE"] = "Zeige Rasse, Klasse und Level",
	["CO_TOOLTIP_REALM"] = "Zeige Server",
	["CO_TOOLTIP_RELATION"] = "Zeige Beziehungsfarbe",
	["CO_TOOLTIP_RELATION_TT"] = "Fügt dem Rand des Charaktertooltips eine Farbe hinzu, um die Beziehung zu repräsentieren.",
	["CO_TOOLTIP_SPACING"] = "Zeige Leerzeile",
	["CO_TOOLTIP_SPACING_TT"] = "Zeigt Leerzeilen, um den Tooltip dem Tooltip von MyRoleplay ähnlich zu sehen.",
	["CO_TOOLTIP_SUBSIZE"] = "Sekundäre Schriftgöße",
	["CO_TOOLTIP_TARGET"] = "Zeige Ziel",
	["CO_TOOLTIP_TERSIZE"] = "Tertiäre Schriftgröße",
	["CO_TOOLTIP_TITLE"] = "Zeige Titel",
	["CO_TOOLTIP_USE"] = "Benutze die Tooltips für Charaktere/Begleiter",
	["CO_UI_RELOAD_WARNING"] = "Das Interface muss neu geladen werden, damit die Änderungen wirksam werden. Möchtest du das Interface jetzt neu laden?",
	["CO_WIM"] = "|cffff9900Flüsterkanäle deaktiviert.",
	["CO_WIM_TT"] = "Du nutzt |cff00ff00WIM|r, die Nutzung wurde aus Kompatibilitätsgründen deaktiviert",
	["COM_LIST"] = "Liste aller Befehle:",
	["COM_RESET_RESET"] = "Die Position des Fensters wurde zurückgesetzt.",
	["COM_RESET_USAGE"] = "Hinweis: |cff00ff00/trp3 reset frames|r, um alle Fensterpositionen zurückzusetzen.",
	["COM_STASH_DATA"] = [=[|cffff0000Bist du sicher, dass du deine Total RP 3 Daten auslagern möchtest?|r

Deine Profile, Begleiterprofile und Einstellungen werden temporär ausgelagert und dein UI wird mit leeren Daten neu geladen, als wäre es eine brandneue Installation von Total RP 3.
|cff00ff00Nutze den selben Befehl nochmal (|cff999999/trp3 stash|cff00ff00) um die Daten wiederherzustellen.|r]=],
	["COM_SWITCH_USAGE"] = "Hinweis: |cff00ff00/trp3 switch main|r, um das Hauptfenster umzuschalten oder |cff00ff00/trp3 switch toolbar|r, um die Werkzeugleiste umzuschalten.",
	["DB_ABOUT"] = "Über Total RP 3",
	["DB_HTML_GOTO"] = "Zum Öffnen klicken",
	["DB_MORE"] = "Mehr Module",
	["DB_NEW"] = "Was ist neu?",
	["DB_STATUS"] = "Status",
	["DB_STATUS_CURRENTLY"] = "Aktuelles",
	["DB_STATUS_CURRENTLY_COMMON"] = "Der Status wird im Tooltip deines Charakters angezeigt. Halte dich hier kurz, knapp und eindeutig, da |cnGREEN_FONT_COLOR:standartmäßig alle TRP3 Nutzer nur die ersten 140 Zeichen sehen können!|r",
	["DB_STATUS_CURRENTLY_OOC"] = "Andere Informationen (OOC)",
	["DB_STATUS_LC"] = "Rollenspiel Sprache",
	["DB_STATUS_LC_TT"] = "Speichert deine bevorzugte Rollenspiel Sprache. Diese Einstellung wird mit anderen Benutzern mit kompatiblem RP Addon geteilt. |cffff9900Achtung:|r Diese Option ändert |cffff0000nicht|r die Menüsprache von Total RP 3. Diese Möglichkeit findest du unter |cfffff569Erweiterte Einstellungen|r.",
	["DB_STATUS_RP"] = "Charakterstatus",
	["DB_STATUS_RP_IC"] = "In Character (IC)",
	["DB_STATUS_RP_IC_TT"] = [=[Die spielst diesen Charakter aktuell aus.
Dein gesamtes Handeln wird bewertet, als ob dein Charakter diese Aktionen ausführt.]=],
	["DB_STATUS_RP_OOC"] = "Out of Character (OOC)",
	["DB_STATUS_RP_OOC_TT"] = [=[Du spielst diesen Charakter aktuell nicht aus.
Dein Handeln wird nicht mit dem Charakter in Verbindung gebracht.]=],
	["DB_TUTO_1"] = [=[|cffffff00Der Charakter Status|r zeigt an, ob du deinen Charakter momentan ausspielst oder nicht.

|cffffff00Die Rollenspielerfahrung|r gibt an, ob du ein blutiger Anfänger oder ein erfahrener Rollenspieler bist, der gerne Neulingen hilft!

|cff00ff00Diese Informationen werden im Tooltip deines Charakters angezeigt.]=],
	["DICE_HELP"] = "Ein Würfelwurf oder mehrere Würfe durch Leerzeichen getrennt, z.B: 1d6, 2d12 3d20 ...",
	["DICE_ROLL"] = "%s rollt |cffff9900%sx d%s|r|cffcc6600%s|r und erziehlt |cff00ff00%s|r.",
	["DICE_ROLL_T"] = "%s %s würfelt |cffff9900%sx w%s|r|cffcc6600%s|r und erhält |cff00ff00%s|r.",
	["DICE_TOTAL"] = "%s Insgesamt |cff00ff00%s|r mit diesem Wurf.",
	["DICE_TOTAL_T"] = "%s %s hat insgesamt |cff00ff00%s|r mit diesem Wurf erzielt.",
	["DTBK_AFK"] = "Total RP 3 - AFK/DND",
	["DTBK_CLOAK"] = "Total RP 3 - Rücken",
	["DTBK_HELMET"] = "Total RP 3 - Helm",
	["DTBK_LANGUAGES"] = "Total RP 3 - Sprachen",
	["DTBK_RP"] = "Total RP 3 - IC/OOC",
	["GEN_VERSION"] = "Version: %s (Build %s)",
	["GEN_WELCOME_MESSAGE"] = "Danke, dass du Total RP 3 (v %s) verwendest! Viel Spaß!",
	["LANG_CHANGE_CAUSED_REVERT_TO_DEFAULT"] = "Deine aktuell gesprochene Sprache wurde auf %s zurückgesetzt, da du die vorherige Sprache %s nicht mehr verstehst. ",
	["MAP_BUTTON_NO_SCAN"] = "Kein Scan verfügbar",
	["MAP_BUTTON_SCANNING"] = "Scanne",
	["MAP_BUTTON_SUBTITLE"] = "Klicken um verfügbare Scans anzuzeigen",
	["MAP_BUTTON_SUBTITLE_80_DISABLED"] = [=[Aufgrund von 8.0 Änderungen sind Scans momentan nicht möglich.
]=],
	["MAP_BUTTON_SUBTITLE_CONNECTING"] = "Das Scannen der Karte wird eingerichtet. Bitte warten.",
	["MAP_BUTTON_SUBTITLE_OFFLINE"] = "Das Scannen der Karte ist momentan nicht verfügbar: %s",
	["MAP_BUTTON_TITLE"] = "Nach Rollenspiel scannen",
	["MAP_SCAN_CHAR"] = "Nach Charakteren scannen",
	["MAP_SCAN_CHAR_TITLE"] = "Charaktere",
	["MATURE_FILTER_EDIT_DICTIONARY"] = "Benutzerdefiniertes Wörterbuch bearbeiten",
	["MATURE_FILTER_EDIT_DICTIONARY_ADD_BUTTON"] = "Hinzufügen",
	["MATURE_FILTER_EDIT_DICTIONARY_ADD_TEXT"] = "Dem Wörterbuch ein neues Wort hinzufügen",
	["MATURE_FILTER_EDIT_DICTIONARY_BUTTON"] = "Editieren",
	["MATURE_FILTER_EDIT_DICTIONARY_DELETE_WORD"] = "Das Wort aus dem benutzerdefinierten Wörterbuch entfernen",
	["MATURE_FILTER_EDIT_DICTIONARY_EDIT_WORD"] = "Dieses wort editieren",
	["MATURE_FILTER_EDIT_DICTIONARY_RESET_BUTTON"] = "Zurücksetzen",
	["MATURE_FILTER_EDIT_DICTIONARY_RESET_TITLE"] = "Wörterbuch zurücksetzen",
	["MATURE_FILTER_EDIT_DICTIONARY_RESET_WARNING"] = "Bist du sicher, dass du das Wörterbuch zurücksetzen möchtest? Alle Einträge werden entfernt und durch die Standard Wörter deiner Sprache ersetzt (falls vorhanden).",
	["MATURE_FILTER_EDIT_DICTIONARY_TITLE"] = "Benutzerdefiniertes Wörterbuch-Editor",
	["MATURE_FILTER_EDIT_DICTIONARY_TT"] = "Das benutzerdefinierte Wörterbuch editieren, welches zur Filterung von Profilen mit Erwachseneninhalten verwendet wird.",
	["MATURE_FILTER_FLAG_PLAYER"] = "Als Inhalt für Erwachsene markieren",
	["MATURE_FILTER_FLAG_PLAYER_OPTION"] = "Als Inhalt für Erwachsene markieren",
	["MATURE_FILTER_FLAG_PLAYER_TEXT"] = [=[Bestätige, dass du markieren willst, dass das Profil von %s Erwachseneninhalte enthält. Das Profil wird versteckt werden.

|cffffff00Optional:|r Gib das anstößige Wort an welches du im Profil gefunden hast (trenne mehrere Wörter mit Leerzeichen), um es dem Filter hinzuzufügen.]=],
	["MATURE_FILTER_FLAG_PLAYER_TT"] = "Markiere, dass dieses Profil Erwachseneninhalte enthält. Der Inhalt des Profils wird versteckt werden.",
	["MATURE_FILTER_OPTION"] = "Profile mit Erwachseneninhalten filtern",
	["MATURE_FILTER_OPTION_TT"] = [=[Wähle diese Option aus um die Filterung von Erwachseneninhalten zu aktivieren. Total RP 3 wird eintreffende Profile nach bestimmten Schlüsselworten durchsuchen die als Erwachseneninhalte festgelegt wurden und das Profil entsprechend markieren wenn ein solches Wort gefunden wird.

Ein Profil mit Erwachseneninhalten wird einen stummgeschalteten Tooltip haben und du wirst bestätigen müssen, dass du es dir ansehen willst, wenn du es zum ersten Mal aufrufst.]=],
	["MATURE_FILTER_STRENGTH"] = "Stärke des Schimpfwortfilters",
	["MATURE_FILTER_STRENGTH_TT"] = "Setzt die Stärke des Schimpfwort Filters. cffcccccc1 ist schwach (Sätze werden ab 10 Schimpfwörtern erkannt), 10 ist stark (Es reicht ein einzelnes Schimpfwort zur Erkennung).|r",
	["MATURE_FILTER_TITLE"] = "Filter für Profile mit Erwachseneninhalten",
	["MATURE_FILTER_TOOLTIP_WARNING"] = "Erwachseneninhalt",
	["MATURE_FILTER_TOOLTIP_WARNING_SUBTEXT"] = "Das Profil dieses Charakters enthält Inhalte für Erwachsene. Verwende die ",
	["MATURE_FILTER_WARNING_CONTINUE"] = "Weiter",
	["MATURE_FILTER_WARNING_GO_BACK"] = "Zurück",
	["MATURE_FILTER_WARNING_TEXT"] = [=[Du hast Total RP 3's Erwachseneninhalt Filtersystem angeschaltet.

Dieses Profil wurde als Profil mit Inhalt für Erwachsene markiert.

Bist du sicher, dass du dir das Profil ansehen willst?]=],
	["MATURE_FILTER_WARNING_TITLE"] = "Erwachseneninhalt",
	["MM_SHOW_HIDE_MAIN"] = "Zeige/verstecke das Hauptfenster",
	["MM_SHOW_HIDE_MOVE"] = "Icon bewegen",
	["MM_SHOW_HIDE_SHORTCUT"] = "Zeig/verstecke die Toolbar",
	["MO_ADDON_NOT_INSTALLED"] = "Das Addon %s ist nicht installiert, eigene Total RP 3 Integration deaktiviert.",
	["MO_CHAT_CUSTOMIZATIONS_DESCRIPTION"] = "Fügt angepasste Kompatibilität zu dem Addon %s, damit deine Chat Nachrichten und Spielernamen durch Total RP 3 angepasst werden können.",
	["MO_TOOLTIP_CUSTOMIZATIONS_DESCRIPTION"] = "Fügt angepasste Kompatibilität zu dem Addon %s, damit deine Tooltipeinstellungen für Total RP 3 übernommen werden.",
	["MORE_MODULES_2"] = [=[{h2:c}Optionale Module{/h2}
{h3}Total RP 3: Extended |cffF87431|r{/h3}
|cff9999ffTotal RP 3: Extended|r fügt die Möglichkeit hinzu neuen Inhalt in WoW zu erstellen. Kampagnen mit Aufträgen und Dialogen, Gegenstände, Dokumente (Bücher, Schilder, Kontrakte, ...) und vieles mehr!
{link*https://www.curseforge.com/wow/addons/total-rp-3-extended*Download on CurseForge}

{h3}TRP3 Currently Frame{/h3}
Adds a standalone frame to your UI that displays your "Currently" text and allows you to edit it easily.
{link*https://www.curseforge.com/wow/addons/trp3-currently-frame*Download on CurseForge}

{h3}TRP3 Location Toggle{/h3}
Adds a simple button to the toolbar to toggle on and off the map scan location feature.
{link*https://www.curseforge.com/wow/addons/trp3-location-toggle*Download on CurseForge}]=],
	["NEW_VERSION"] = [=[|cff00ff00Eine neue Version von Total RP 3 (v %s) ist verfügbar.

|cffffff00Wir empfehlen dringendst auf dem aktuellen Stand zu bleiben.|r

Diese Nachricht wird nur einmal pro Sitzung angezeigt und kann in den Einstellungen (Allgemeine Einstellungen => Verschiedenes) abgeschaltet werden.]=],
	["NEW_VERSION_BEHIND"] = "Du hinkst momentan %s Versionen hinterher und verpasst dadurch viele Bugfixes und neue Features. Anderen Spielern könnten zudem dein Profil nicht richtig angezeigt werden. Bitte ziehe in Erwägung dein Addon zu updaten.",
	["NEW_VERSION_TITLE"] = "Neues Update verfügbar",
	["NPC_TALK_BUTTON_TT"] = "Das NSC-Sprachfenster zu öffnen erlaubt dir NSC sprechen oder emoten zu lassen.",
	["NPC_TALK_CHANNEL"] = "Kanal:",
	["NPC_TALK_COMMAND_HELP"] = "NSC-Sprachfenster öffnen",
	["NPC_TALK_ERROR_EMPTY_MESSAGE"] = "Die Nachricht darf nicht leer sein.",
	["NPC_TALK_MESSAGE"] = "Nachricht",
	["NPC_TALK_NAME"] = "NSC Name",
	["NPC_TALK_NAME_TT"] = [=[Du kannst Standard-Chat-Tags wie %t um den Namen deines Ziels verwenden oder %f um den Namen deines Fokus einzufügen.

Du kannst dieses Feld auch leer lassen, um Emotes ohne einen NSC-Namen am Anfang zu erstellen.

Den Begleiternamen in [Klammern] einsetzen erlaubt es dir, die Farbe und das Icon anzupassen.]=],
	["NPC_TALK_SAY_PATTERN"] = "sagt:",
	["NPC_TALK_SEND"] = "Senden",
	["NPC_TALK_TITLE"] = "NSC Sprache",
	["NPC_TALK_WHISPER_PATTERN"] = "flüstert:",
	["NPC_TALK_YELL_PATTERN"] = "schreit:",
	["OPTION_DISABLED_TOAST"] = "Option deaktiviert",
	["OPTION_ENABLED_TOAST"] = "Option aktiviert",
	["PATTERN_ERROR"] = "Fehler im Eingabemuster",
	["PATTERN_ERROR_TAG"] = "Fehler im Eingabemuster: Nicht-geschlossener Text-Tag",
	["PR_CO_BATTLE"] = "Begleiter",
	["PR_CO_COUNT"] = "%s Haustiere/Reittiere an dieses Profil gebunden.",
	["PR_CO_EMPTY"] = "Kein Begleiterprofil",
	["PR_CO_MASTERS"] = "Meister",
	["PR_CO_MOUNT"] = "Reittier",
	["PR_CO_NEW_PROFILE"] = "Neues Begleiterprofil",
	["PR_CO_PET"] = "Tier",
	["PR_CO_PROFILE_DETAIL"] = "Dieses Profil ist aktuell gebunden an",
	["PR_CO_PROFILE_HELP"] = [=[Ein Profil enthält alle Informationen über ein |cffffff00"Haustier/Begleiter"|r als |cff00ff00Rollenspiel Charakter|r.

Ein Begleiterprofil kann an folgende Begleiterarten gebunden werden:
- Ein Kampfhaustier |cffff9900(nur wenn es umbennant wurde)|r
- Einen Jägerbegleiter
- Einen Diener eines Hexenmeisters
- Einen Magierelementar
- Einen Ghul eines Todesritters |cffff9900(siehe unten)|r

Genau wie bei einem Charakterprofil kann ein |cff00ff00Begleiterproful|r mit |cffffff00verschiedenen Haustieren|r verbunden werden. Genauso kannst du für dein |cffffff00Haustier|r einfach durch die verschiedenen Profile schalten.

|cffff9900Ghule:|r Für einen Ghul musst du das Profil bei jeder Beschwörung neu auswählen, da dessen Spielname zufällig vergeben wird!]=],
	["PR_CO_PROFILE_HELP2"] = [=[Hier klicken um eine neues Begleiterprofil anzulegen.

|cff00ff00Um ein Profil einem Haustier zu zuweisen, beschwöre einfach dein Haustier/Begleiter, wähle es aus und benutze das Zielfenster um es einem Profil zu zuweisen (oder ein neues Profil zu erstellen).|r]=],
	["PR_CO_PROFILEMANAGER_DELETE_WARNING"] = [=[Bist du sicher, dass du dieses Begleiterprofil %s löschen willst?
Diese Aktion kann nicht rückgängig gemacht werden und alle TRP3 Informationen, die damit zusammenhängen, werden unwiderruflich zerstört!]=],
	["PR_CO_PROFILEMANAGER_DUPP_POPUP"] = [=[Bitte gibt einen Namen für das neue Profil ein.
Der Name darf nicht leer sein.

Diese Kopie ändert nicht die Bindung deines Haustieres/Reittieres zu %s.]=],
	["PR_CO_PROFILEMANAGER_EDIT_POPUP"] = [=[Bitte gib einen Namen für das Profil %s ein.
Der Name darf nicht leer sein.

Das Ändern des Namens ändert nicht die Verbindung des Profils mit deinem Haustier/Reittier.]=],
	["PR_CO_PROFILEMANAGER_TITLE"] = "Begleiterprofile",
	["PR_CO_UNUSED_PROFILE"] = "Dieses Profil ist aktuell nicht an ein Haustier oder Reittier gebunden.",
	["PR_CO_WARNING_RENAME"] = [=[|cffff0000Warnung:|r Es wird dringend empfohlen, dein Haustier umzubenennen, bevor du es mit einem Profil verbindest.

Trotzdem verbinden?]=],
	["PR_CREATE_PROFILE"] = "Profil erstellen",
	["PR_DELETE_PROFILE"] = "Profil löschen",
	["PR_DUPLICATE_PROFILE"] = "Profil kopieren",
	["PR_EXPORT_IMPORT_HELP"] = [=[Du kannst Profile über die Option im Dropdownmenü exportieren und importieren.

Benutze die |cffffff00Profil exportieren|r Option um eine Textserie zu generieren der die Profildaten enthält. Du kannst den Text über Strg+C (Command+C auf einem Mac) kopieren und es woanders als Sicherung einfügen. (|cffff0000Bitte beachte, dass einige fortgeschrittene Textverarbeitungswerkzeuge wie Microsoft Word Sonderzeichen als Zitate ansehen und die Daten verändern. Verwende daher einfachere Werkzeuge wie Notepad.|r)

Benutze die |cffffff00Profil importieren|r Option um Daten aus einem früheren Export in ein existierendes Profil einzufügen. Die existierenden Daten des Profils werden durch das die neu eingefügten ersetzt. Du kannst die Daten nicht direkt in das derzeit ausgewählte Profil importieren.]=],
	["PR_EXPORT_IMPORT_TITLE"] = "Profil exportieren/importieren",
	["PR_EXPORT_NAME"] = "Text für Profil %s (Größe %0.2f kB)",
	["PR_EXPORT_PROFILE"] = "Profil exportieren",
	["PR_EXPORT_TOO_LARGE"] = [=[Dieses Profil ist zu groß und kann nicht exportiert werden.

Profilgröße: %0.2f kB
Max: 20 kB]=],
	["PR_EXPORT_WARNING_MAC"] = "Bitte achte darauf, dass manche Textverarbeitungsprogramme  wie Text Edit oder Discord manche Zeichen (wie z.B. Anführungszeichen) besonders behandeln und damit den Inhalt verändern. Wenn du vor hast den unteren Text in ein Dokument zu kopieren, benutze bitte ein einfaches Textverarbeitungsprogramme, das keine automatische Zeichenerkennung benutzt. (In Text Edit gehe zu  Format > Nur Text erstellen, vor dem Einfügen.)",
	["PR_EXPORT_WARNING_TITLE"] = "Warnung:",
	["PR_EXPORT_WARNING_WINDOWS"] = "Bitte achte darauf, dass manche Textverarbeitungsprogramme  wie Microsoft Word oder Discord manche Zeichen (wie z.B. Anführungszeichen) besonders behandeln und damit den Inhalt verändern. Wenn du vor hast den unteren Text in ein Dokument zu kopieren, benutze bitte ein einfaches Textverarbeitungsprogramme, das keine automatische Zeichenerkennung benutzt, wie zum Beispiel den normalen Windows Editor.",
	["PR_IMPORT"] = "Importieren",
	["PR_IMPORT_CHAR_TAB"] = "Charakterimporteur",
	["PR_IMPORT_EMPTY"] = "Kein importierbares Profil",
	["PR_IMPORT_IMPORT_ALL"] = "Alles importieren",
	["PR_IMPORT_PETS_TAB"] = "Begleiterimporteur",
	["PR_IMPORT_PROFILE"] = "Profil importieren",
	["PR_IMPORT_PROFILE_TT"] = "Hier einen Profiltext einfügen",
	["PR_IMPORT_WILL_BE_IMPORTED"] = "Wird importiert",
	["PR_PROFILE"] = "Profil",
	["PR_PROFILE_CREATED"] = "Profile %s erstellt.",
	["PR_PROFILE_DELETED"] = "Profile %s gelöscht.",
	["PR_PROFILE_DETAIL"] = "Dieses Profil ist aktuell an diese WoW Charaktere gebunden",
	["PR_PROFILE_HELP"] = [=[Ein Profil enthält alle Informationen über einen |cffffff00"Charakter"|r als |cff00ff00Rollenspielcharakter|r.

Ein realer |cffffff00"WoW Charakter"|r kann nur an ein Profil gleichzeitig gebunden sein, kann aber zwischen verschiedenen Profilen hin und her schalten.

Du kannst auch mehrere |cffffff00"WoW Charaktere"|r an dasselbe |cff00ff00Profil|r binden!]=],
	["PR_PROFILE_LOADED"] = "Das Profil %s ist geladen.",
	["PR_PROFILE_MANAGEMENT_TITLE"] = "Profilverwaltung",
	["PR_PROFILEMANAGER_ACTIONS"] = "Aktionen",
	["PR_PROFILEMANAGER_ALREADY_IN_USE"] = "Der Profilname %s ist nicht verfügbar.",
	["PR_PROFILEMANAGER_COUNT"] = "%s WoW Charakter/e an dieses Profil gebunden.",
	["PR_PROFILEMANAGER_CREATE_POPUP"] = [=[Gib bitte einen Namen für das neue Profil ein.
Die Namenszeile darf nicht leer sein.]=],
	["PR_PROFILEMANAGER_CURRENT"] = "Aktuelles Profil",
	["PR_PROFILEMANAGER_DELETE_WARNING"] = [=[Bist du sicher, dass du das Profil %s? löschen willst
Diese Aktion kann nicht rückgängig gemacht werden und alle TRP3 Informationen, die damit verbunden sind, werden unwiderruflich gelöscht!]=],
	["PR_PROFILEMANAGER_DUPP_POPUP"] = [=[Gib bitte einen Namen für das neue Profil ein.
Die Namenszeile darf nicht leer sein.

Diese Kopie ändert nicht die Bindung zu %s.]=],
	["PR_PROFILEMANAGER_EDIT_POPUP"] = [=[Gib bitte einen neuen Namen für das Profil %s ein.
Die Namenszeile darf nicht leer sein.

Die änderung des Namens verändert nicht die Verbindung zwischen dem Profil und den Charakteren.]=],
	["PR_PROFILEMANAGER_IMPORT_WARNING"] = "Den gesamten Inhalt des Profils %s mit den importierten Daten überschreiben?",
	["PR_PROFILEMANAGER_IMPORT_WARNING_2"] = [=[Warnung: dieser Profiltext wurde mit einer älteren Version von TRP3 erstellt.
Dies kann zu Inkompatibilitäten führen.

Den gesamten Inhalt des Profils %s mit den importierten Daten überschreiben?]=],
	["PR_PROFILEMANAGER_RENAME"] = "Profil umbenennen",
	["PR_PROFILEMANAGER_SWITCH"] = "Profil auswählen",
	["PR_PROFILEMANAGER_TITLE"] = "Charakterprofile",
	["PR_PROFILES"] = "Profile",
	["PR_SLASH_EXAMPLE"] = "|cffffff00Befehlnutzung:|r |cffcccccc/trp3 profile Millidan Foamrage|r |cffffff00wechselt zu Millidan Foamrages Profil.|r\"",
	["PR_SLASH_NOT_FOUND"] = "|cffff0000Das Profil Namens|r |cffffff00%s|r|cffff0000.|r wurde nicht gefunden.",
	["PR_SLASH_OPEN_ABORTING"] = "|cffffff00Profilabfrage abgebrochen.|r",
	["PR_SLASH_OPEN_EXAMPLE"] = "|cffffff00Befehlnutzung:|r |cffcccccc/trp3 open|r |cffffff00um das Charakterprofil des Ziels zu öffnen oder |cffcccccc/trp3 open CharakterName-RealmName|r |cffffff00um das Profil eines Charakters zu öffnen.|r",
	["PR_SLASH_OPEN_HELP"] = "Öffnet ein Charakterprofil anhand des Im-Spiel-Name oder anhand des Profile des Ziels, wenn kein Name angegeben wurde.",
	["PR_SLASH_OPEN_WAITING"] = "|cffffff00Frage Profile ab, bitte warten...|r",
	["PR_SLASH_SWITCH_HELP"] = [=[
Wechsel zu einem anderen Profil mit diesem Namen.]=],
	["PR_UNUSED_PROFILE"] = "Dieses Profil ist aktuell an keinen WoW Charakter gebunden.",
	["REG_CODE_INSERTION_WARNING"] = [=[|TInterface\AddOns\totalRP3\resources\policegar.tga:50:50|t
Moment mal!

Wir haben bemerkt, das Ihr manuell ungültige Codes in Euer Total RP 3 Profil eingegeben habt.
Dies wird nicht unterstützt und wir raten jedem dringend davon ab dieses zu tun.
Es kann zu Instabilität und Bugs im Add-on, beschädigten Daten und/oder Verlust von Profilen führen. Des weiteren können Kompatibilitätsprobleme mit anderen Add-ons (wie MRP) entstehen.

Die Codes, die Ihr in Euer Profil eingefügt habt, wurden entfernt um zu verhindern, dass Ihr das Add-on beschädigt.]=],
	["REG_COMPANION"] = "Begleiter",
	["REG_COMPANION_BOUND_TO"] = "Gebunden an ...",
	["REG_COMPANION_BOUND_TO_TARGET"] = "Ziel",
	["REG_COMPANION_BOUNDS"] = "Bindungen",
	["REG_COMPANION_BROWSER_BATTLE"] = "Wildtierbrowser",
	["REG_COMPANION_BROWSER_MOUNT"] = "Reittierbrowser",
	["REG_COMPANION_INFO"] = "Information",
	["REG_COMPANION_LINKED"] = "Der Begleiter %s ist nun verbunden mit dem Profil %s",
	["REG_COMPANION_LINKED_NO"] = "Der Begleiter %s ist nun nicht mehr mit einem Profil verbunden.",
	["REG_COMPANION_NAME"] = "Name",
	["REG_COMPANION_NAME_COLOR"] = "Namensfarbe",
	["REG_COMPANION_PAGE_TUTO_C_1"] = "Consult",
	["REG_COMPANION_PAGE_TUTO_E_1"] = [=[Das ist die|cff00ff00 Hauptinformation deines Begleiters|r.

All diese Informationen werden |cffff9900im Tooltip deines Begleiters angezeigt|r.]=],
	["REG_COMPANION_PAGE_TUTO_E_2"] = [=[Das ist die|cff00ff00 Beschreibung deines Charakters|r.

Es ist nicht auf eine |cffff9900Physische Beschreibung|r limitiert. Deute hier ruhig Teile seiner |cffff9900Hintergrundgeschichte|r oder Details über seine |cffff9900Persönlichkeit|r an.

Es gibt unzählige Wege, die Beschreibung zu personalisieren.
Du kannst eine |cffffff00Hintergrundtextur|r für die Beschreibung aussuchen. Du kannst ebenfalls die Formatierungstools verwenden, um Dinge wie |cffffff00Schriftgröße, Farbe und Textausrichtung|r anzupassen.
Diese Tools erlauben dir auch das Einfügen von |cffffff00Bildern, Icons oder Links zu externen Internetseiten|r.]=],
	["REG_COMPANION_PROFILES"] = "Begleiterprofile",
	["REG_COMPANION_TARGET_NO"] = "Dein Ziel ist kein gültiges Haustier, Diener, Ghul, Elementar oder umbenanntes Kampfhaustier.",
	["REG_COMPANION_TF_BOUND_TO"] = "Profil auswählen",
	["REG_COMPANION_TF_CREATE"] = "Neues Charakterprofil erstellen",
	["REG_COMPANION_TF_NO"] = "Kein Profil",
	["REG_COMPANION_TF_OPEN"] = "Seite öffnen",
	["REG_COMPANION_TF_OWNER"] = "Besitzer: %s",
	["REG_COMPANION_TF_PROFILE"] = "Begleiterprofil",
	["REG_COMPANION_TF_PROFILE_MOUNT"] = "Reittierprofil",
	["REG_COMPANION_TF_UNBOUND"] = "Profil abwählen",
	["REG_COMPANION_TITLE"] = "Titel",
	["REG_COMPANION_UNBOUND"] = "Entbinden von ...",
	["REG_COMPANIONS"] = "Begleiter",
	["REG_DELETE_WARNING"] = [=[Bist du sicher, dass du das Profil "%s" löschen möchtest?
]=],
	["REG_IGNORE_TOAST"] = "Charakter wird ignoriert",
	["REG_LIST_ACTIONS_MASS"] = "Aktion auf %s ausgewählte Profile",
	["REG_LIST_ACTIONS_MASS_IGNORE"] = "Profile ignorieren",
	["REG_LIST_ACTIONS_MASS_IGNORE_C"] = [=[Diese Aktion wird |cff00ff00%s Charaktere der Ignorieren Liste hinzufügen.

Optional kann hier ein Grund angegeben werden. Es handelt sich um eine persönliche Notiz, die nur zur Erinnerung dient.]=],
	["REG_LIST_ACTIONS_MASS_REMOVE"] = "Profile entfernen",
	["REG_LIST_ACTIONS_MASS_REMOVE_C"] = "Diese Aktion wird |cff00ff00%s ausgewählte/s Profil/e löschen|r.",
	["REG_LIST_ACTIONS_PURGE"] = "Register entfernen",
	["REG_LIST_ACTIONS_PURGE_ALL"] = "Alle Profile löschen",
	["REG_LIST_ACTIONS_PURGE_ALL_C"] = [=[Dies wird alle Profile und verlinkten Charaktere löschen.

|cff00ff00%s Charaktere.]=],
	["REG_LIST_ACTIONS_PURGE_ALL_COMP_C"] = [=[Dies wird alle deine Begleiter löschen.

|cff00ff00%s Begleiter.]=],
	["REG_LIST_ACTIONS_PURGE_COUNT"] = "%s Profile werden gelöscht.",
	["REG_LIST_ACTIONS_PURGE_EMPTY"] = "Keine Profile zum Löschen.",
	["REG_LIST_ACTIONS_PURGE_IGNORE"] = "Profile von ignorierten Charakteren",
	["REG_LIST_ACTIONS_PURGE_IGNORE_C"] = [=[Diese Aktion wird alle Profile, die mit ignorierten Charakteren verbunden sind, löschen.

|cff00ff00%s]=],
	["REG_LIST_ACTIONS_PURGE_TIME"] = "Seit 1 Monat nicht mehr gesehene Profile",
	["REG_LIST_ACTIONS_PURGE_TIME_C"] = [=[Dies wird alle Profile löschen, die seit einem Monat nicht gesehen wurden.

|cff00ff00%s]=],
	["REG_LIST_ACTIONS_PURGE_UNLINKED"] = "Profile ohne Charakter",
	["REG_LIST_ACTIONS_PURGE_UNLINKED_C"] = [=[Dies wird alle Profile, die nicht an einen WoW Charakter gebunden sind, löschen.

|cff00ff00%s]=],
	["REG_LIST_ADDON"] = "Profiltyp",
	["REG_LIST_CHAR_EMPTY"] = "Kein Charakter",
	["REG_LIST_CHAR_EMPTY2"] = "Kein Charakter passt zu deiner Auswahl",
	["REG_LIST_CHAR_FILTER"] = "Charaktere: %s / %s",
	["REG_LIST_CHAR_IGNORED"] = "Ignoriert",
	["REG_LIST_CHAR_SEL"] = "Charakter wählen",
	["REG_LIST_CHAR_TITLE"] = "Charakterliste",
	["REG_LIST_CHAR_TT"] = "Zum Anzeigen klicken",
	["REG_LIST_CHAR_TT_CHAR"] = "Gebundene WoW Charakter/e:",
	["REG_LIST_CHAR_TT_CHAR_NO"] = "Nicht an einen Charakter gebunden",
	["REG_LIST_CHAR_TT_DATE"] = [=[Zuletzt gesehen: |cff00ff00%s|r
Wo zuletzt gesehen: |cff00ff00%s|r]=],
	["REG_LIST_CHAR_TT_GLANCE"] = "Auf den ersten Blick",
	["REG_LIST_CHAR_TT_IGNORE"] = "Ignorierte Charakter/e",
	["REG_LIST_CHAR_TT_NEW_ABOUT"] = "Ungelesene Beschreibung",
	["REG_LIST_CHAR_TT_RELATION"] = [=[Beziehung:
|cff00ff00%s]=],
	["REG_LIST_FILTERS"] = "Filter",
	["REG_LIST_FILTERS_TT"] = [=[|cffffff00Links-Klick:|r Filter anwenden
|cffffff00Rechts-Klicken:|r Filter zurücksetzen]=],
	["REG_LIST_FLAGS"] = "Flags",
	["REG_LIST_GUILD"] = "Gilde des Charakters",
	["REG_LIST_IGNORE_EMPTY"] = "Keine ignorierten Charaktere",
	["REG_LIST_IGNORE_TITLE"] = "Liste ignorierter Charaktere",
	["REG_LIST_IGNORE_TT"] = [=[Grund:
|cff00ff00%s

|cffffff00Klicken, um von der Liste zu streichen]=],
	["REG_LIST_NAME"] = "Name das Charakters",
	["REG_LIST_NOTIF_ADD"] = "Neues Profil gefunden für |cff00ff00%s",
	["REG_LIST_NOTIF_ADD_CONFIG"] = "Neues Profil gefunden",
	["REG_LIST_NOTIF_ADD_NOT"] = "Dieses Profil existiert nicht mehr.",
	["REG_LIST_PET_MASTER"] = "Name des Herren",
	["REG_LIST_PET_NAME"] = "Name des Begleiters",
	["REG_LIST_PET_TYPE"] = "Typ des Begleiters",
	["REG_LIST_PETS_EMPTY"] = "Kein/e Begleiter",
	["REG_LIST_PETS_EMPTY2"] = "Kein Begleiter passt zu deiner Auswahl",
	["REG_LIST_PETS_FILTER"] = "Begleiter: %s / %s",
	["REG_LIST_PETS_TITLE"] = "Begleiterliste",
	["REG_LIST_PETS_TOOLTIP"] = "Wurde gesehen bei",
	["REG_LIST_PETS_TOOLTIP2"] = "Wurde gesehen mit",
	["REG_LIST_REALMONLY"] = "Nur dieser Realm",
	["REG_LOCATION_DIFFERENT_WAR_MODE"] = "Anderer Kriegsmodus",
	["REG_MSP_ALERT"] = [=[|cffff0000WARNUNG

Du kannst nicht mehrere Addons nutzen, die das Mary Sue Protocol (MSP) nutzen, da das zu Fehlern führen kann!|r

Aktuell geladen: |cff00ff00%s

|cffff9900Deshalb wir der MSP Support für Total RP3 deaktiviert.|r

Wenn du TRP3 nicht als dein MSP Addon nutzen und diese Meldung nicht noch einmal sehen willst, kannst du das Mary Sue Protocol Modul in den TRP3 Einstellungen unter Modul Status deaktivieren.]=],
	["REG_NOTES_PROFILE"] = "Notizen",
	["REG_NOTES_PROFILE_TT"] = "Öffnet das Notizen Fenster für den anvisierten Charakter.",
	["REG_PLAYER"] = "Charakter",
	["REG_PLAYER_ABOUT"] = "Über",
	["REG_PLAYER_ABOUT_ADD_FRAME"] = "Fenster hinzufügen",
	["REG_PLAYER_ABOUT_EMPTY"] = "Keine Beschreibung",
	["REG_PLAYER_ABOUT_HEADER"] = "Titeltag",
	["REG_PLAYER_ABOUT_MUSIC_LISTEN"] = "Soundtrack abspielen",
	["REG_PLAYER_ABOUT_MUSIC_REMOVE"] = "Soundtrack abwählen",
	["REG_PLAYER_ABOUT_MUSIC_SELECT"] = "Charakter Soundtrack wählen",
	["REG_PLAYER_ABOUT_MUSIC_SELECT2"] = "Soundtrack wählen",
	["REG_PLAYER_ABOUT_MUSIC_STOP"] = "Soundtrack stoppen",
	["REG_PLAYER_ABOUT_MUSIC_THEME"] = "Charakter-Musikthema",
	["REG_PLAYER_ABOUT_NOMUSIC"] = "|cffff9900Kein Soundtrack",
	["REG_PLAYER_ABOUT_P"] = "Paragraph tag",
	["REG_PLAYER_ABOUT_REMOVE_FRAME"] = "Diese Fenster entfernen",
	["REG_PLAYER_ABOUT_SOME"] = "Irgendein Text ...",
	["REG_PLAYER_ABOUT_T1_YOURTEXT"] = "Dein Text hier",
	["REG_PLAYER_ABOUT_TAGS"] = "Formatierungstools",
	["REG_PLAYER_ABOUT_UNMUSIC"] = "|cffff9900Unbekannter Soundtrack",
	["REG_PLAYER_ABOUTS"] = "Über %s",
	["REG_PLAYER_ADD_NEW"] = "Neues Profil erstellen",
	["REG_PLAYER_AGE"] = "Alter",
	["REG_PLAYER_AGE_TT"] = [=[Hier kannst du angeben, wie alt dein Charakter ist.

Hierfür gibt es mehrere Möglichkeiten:|c0000ff00
- Du kannst Jahre angeben,
- Oder ein Adjektiv (jung, ausgewachsen, erwachsen, steinalt, etc.).]=],
	["REG_PLAYER_ALERT_HEAVY_SMALL"] = [=[|cffff0000Dein Profil ist sehr lang.
|cffff9900Du solltest versuchen, die Länge reduzieren.]=],
	["REG_PLAYER_BIRTHPLACE"] = "Geburtsort",
	["REG_PLAYER_BIRTHPLACE_TT"] = [=[Hier kannst du den Geburtsort deines Charakters angeben. Das kann entweder ein Ort, eine Zone oder ein Kontinent sein. Es liegt ganz an dir, wie akkurat du es angeben möchtest.

|c00ffff00Du kannst den Button rechts verwenden, um ganz einfach den aktuellen Ort als deinen Geburtsort festzulegen.]=],
	["REG_PLAYER_BKG"] = "Hintergrundlayout",
	["REG_PLAYER_BKG_TT"] = "Dies repräsentiert den grafischen Hintergrund für dein Charakteristikfenster.",
	["REG_PLAYER_CARACT"] = "Charakteristiken",
	["REG_PLAYER_CHANGE_CONFIRM"] = [=[Du hast ungespeicherte Daten.
Möchtest du die Seite dennoch wechseln?
|cffff9900Alle änderungen gehen verloren.]=],
	["REG_PLAYER_CHARACTERISTICS"] = "Charakteristiken",
	["REG_PLAYER_CLASS"] = "Klasse",
	["REG_PLAYER_CLASS_TT"] = [=[Die Klasse deines Charakters.

|cff00ff00Zum Beispiel :|r
Ritter, Pyromane, Nekromant, Eliteschütze, Arkanwirker, Magd ...]=],
	["REG_PLAYER_COLOR_ALWAYS_DEFAULT_TT"] = [=[|cffffff00Linksklick:|r Wähle eine Farbe
|cffffff00Rechtsklick:|r Wähle Farbe ab]=],
	["REG_PLAYER_COLOR_CLASS"] = "Klassenfarbe",
	["REG_PLAYER_COLOR_CLASS_TT"] = [=[Dies bestimmt ebenfalls die Farbe des Charakternamens.

]=],
	["REG_PLAYER_COLOR_TT"] = [=[|cffffff00Linksklick:|r Wähle eine Farbe
|cffffff00Rechtsklick:|r Farbe abwählen]=],
	["REG_PLAYER_CURRENT"] = "Aktuelles",
	["REG_PLAYER_CURRENT_OOC"] = "Dies ist eine OOC Information.",
	["REG_PLAYER_CURRENTOOC"] = "Aktuelles (OOC)",
	["REG_PLAYER_EDIT_MUSIC_THEME"] = "Musikthema",
	["REG_PLAYER_EYE"] = "Augenfarbe",
	["REG_PLAYER_EYE_TT"] = [=[Hier kannst du die Augenfarbe eintragen.

Bedenke bitte das, auch wenn dein Charakter ein komplett verhülltes Gesicht hat, es trotzdem sinvoll sein kann die Augenfarbe hier zu erwähnen.]=],
	["REG_PLAYER_FIRSTNAME"] = "Vorname",
	["REG_PLAYER_FIRSTNAME_TT"] = [=[Das ist der Vorname deines Charakters. Dies ist ein Freies Feld, wenn du nichts einträgst wird der Spielname (|cffffff00%s|r) deines Charakters benutzt.

Du kannst einen |c0000ff00Spitznamen|r verwenden!]=],
	["REG_PLAYER_FULLTITLE"] = "Voller Titel",
	["REG_PLAYER_FULLTITLE_TT"] = [=[Hier kannst du den Vollen Titel deines Charakter eintragen. Dies kann der komplette volle Titel deines Charakters oder weiter Titel sein.

Wie dem auch sei, versuche bitte Wiederholungen zu vermeinden falls es keine weiteren Informationen zu deinem Titel mehr gibt.]=],
	["REG_PLAYER_GLANCE"] = "Auf den ersten Blick",
	["REG_PLAYER_GLANCE_BAR_DELETED"] = "Gruppenvoreinstellung |cffff9900%s|r wurde gelöscht.",
	["REG_PLAYER_GLANCE_BAR_EMPTY"] = "Der Name einer Voreinstellung darf nicht leer sein.",
	["REG_PLAYER_GLANCE_BAR_LOAD"] = "Gruppenvoreinstellung",
	["REG_PLAYER_GLANCE_BAR_LOAD_SAVE"] = "Gruppenvoreinstellungen",
	["REG_PLAYER_GLANCE_BAR_NAME"] = [=[Bitte gibt einen Voreinstellungsnamen ein

|cff00ff00Hinweis: Wenn der Name bereits von einer anderen Voreinstellung genutzt wird, wird diese ersetzt.]=],
	["REG_PLAYER_GLANCE_BAR_SAVE"] = "Speichere diese Gruppe als Voreinstellung.",
	["REG_PLAYER_GLANCE_BAR_SAVED"] = "Gruppenvoreinstellung |cff00ff00%s|r wurde erstellt.",
	["REG_PLAYER_GLANCE_BAR_TARGET"] = "\"Auf den ersten Blick\"-Voreinstellungen",
	["REG_PLAYER_GLANCE_CONFIG"] = [=[
|cffffff00Links-Klick:|r Slot konfigurieren
|cffffff00Rechts-Klick:|r Slot aktivierung umschalten
|cffffff00Drag & drop:|r Slots neu anordnen]=],
	["REG_PLAYER_GLANCE_EDITOR"] = "Slot Editor",
	["REG_PLAYER_GLANCE_MENU_COPY"] = "Slot kopieren",
	["REG_PLAYER_GLANCE_MENU_PASTE"] = "Slot: %s einfügen",
	["REG_PLAYER_GLANCE_PRESET"] = "Voreinstellung laden",
	["REG_PLAYER_GLANCE_PRESET_ADD"] = "Die Vorlage |cff00ff00%s|r wurde erstellt.",
	["REG_PLAYER_GLANCE_PRESET_ALERT1"] = "Bitte eine Kategorie und einen Namen angeben",
	["REG_PLAYER_GLANCE_PRESET_CATEGORY"] = "Voreinstellungskategorie",
	["REG_PLAYER_GLANCE_PRESET_CREATE"] = "Vorlage erstellen",
	["REG_PLAYER_GLANCE_PRESET_GET_CAT"] = [=[%s

Bitte gib einen Kategoriennamen für diese Vorlage ein.]=],
	["REG_PLAYER_GLANCE_PRESET_NAME"] = "Voreinstellungsname",
	["REG_PLAYER_GLANCE_PRESET_REMOVE"] = "Vorlage |cff00ff00%s|r entfernt",
	["REG_PLAYER_GLANCE_PRESET_SAVE"] = "Informationen als Vorseinstellung speichern",
	["REG_PLAYER_GLANCE_PRESET_SAVE_SMALL"] = "Als Voreinstellung speichern",
	["REG_PLAYER_GLANCE_PRESET_SELECT"] = "Voreinstellung auswählen",
	["REG_PLAYER_GLANCE_TITLE"] = "Attributsname",
	["REG_PLAYER_GLANCE_UNUSED"] = "Unbenutzer Slot",
	["REG_PLAYER_GLANCE_USE"] = "Diesen Slot aktivieren",
	["REG_PLAYER_HEIGHT"] = "Größe",
	["REG_PLAYER_HEIGHT_TT"] = [=[Gibt die Größe deines Charakters an.
Hierfür gibt es mehrere Möglichkeiten:|c0000ff00
- Eine komplette Zahl: 170 cm, 1,45 m, 3 Fuß  ...
- Eine Beschreibung: großgewachsen, klein ...]=],
	["REG_PLAYER_HERE"] = "Position abfragen",
	["REG_PLAYER_HERE_HOME_PRE_TT"] = [=[Aktuelle Heimatort-Kartenkoordinaten:
|cff00ff00%s|r.]=],
	["REG_PLAYER_HERE_HOME_TT"] = [=[|cffffff00Klick|r: Verwende deine aktuellen Koordinaten als Heimatort-Position.
|cffffff00Rechtsklick|r: Entferne deine Heimatort-Position.]=],
	["REG_PLAYER_HERE_TT"] = "|cffffff00Click|r: Auf die aktuelle Position setzen",
	["REG_PLAYER_HISTORY"] = "Hintergrund",
	["REG_PLAYER_ICON"] = "Charaktericon",
	["REG_PLAYER_ICON_TT"] = "Wähle eine Grafik, die deinen Charakter symbolisiert.",
	["REG_PLAYER_IGNORE"] = "Ignoriere verlinkte Charaktere (%s)",
	["REG_PLAYER_IGNORE_WARNING"] = [=[Möchtest du diese Charaktere ignorieren?

|cffff9900%s

|rOptional kannst du einen Grund angeben. Dies ist eine persönliche Notiz und kann nur von dir eingesehen werden.]=],
	["REG_PLAYER_LASTNAME"] = "Nachname",
	["REG_PLAYER_LASTNAME_TT"] = "Dies ist der Familienname deines Charakters.",
	["REG_PLAYER_LEFTTRAIT"] = "Linkes Attribut",
	["REG_PLAYER_MISC_ADD"] = "Füge ein weiteres Feld hinzu.",
	["REG_PLAYER_MORE_INFO"] = "Zusätzliche Informationen",
	["REG_PLAYER_MSP_HOUSE"] = "Hausname",
	["REG_PLAYER_MSP_MOTTO"] = "Motto",
	["REG_PLAYER_MSP_NICK"] = "Spitzname",
	["REG_PLAYER_NAMESTITLES"] = "Namen und Titel",
	["REG_PLAYER_NO_CHAR"] = "Keine Charakterstik",
	["REG_PLAYER_NOTES"] = "Notizen",
	["REG_PLAYER_NOTES_ACCOUNT"] = "Gemeinsame Notizen",
	["REG_PLAYER_NOTES_ACCOUNT_HELP"] = "Diese privaten Notizen sind mit deinem Account verbunden und werden mit allen deinen Profile geteilt.",
	["REG_PLAYER_NOTES_PROFILE"] = "Notizen von %s",
	["REG_PLAYER_NOTES_PROFILE_HELP"] = "Diese privaten Notizen sind mit deinem aktuellen Profil verbunden und verändern sich, je nachdem welches Profil du benutzt. ",
	["REG_PLAYER_NOTES_PROFILE_NONAME"] = "Profil Notizen",
	["REG_PLAYER_PEEK"] = "Verschiedenes",
	["REG_PLAYER_PHYSICAL"] = "Aussehen",
	["REG_PLAYER_PSYCHO"] = "Persönliche Merkmale",
	["REG_PLAYER_PSYCHO_Acete"] = "Asketisch",
	["REG_PLAYER_PSYCHO_ADD"] = "Personliches Merkmal hinzufügen",
	["REG_PLAYER_PSYCHO_ATTIBUTENAME_TT"] = "Attributsname",
	["REG_PLAYER_PSYCHO_Bonvivant"] = "Lebemann",
	["REG_PLAYER_PSYCHO_CHAOTIC"] = "Chaotisch",
	["REG_PLAYER_PSYCHO_Chaste"] = "Keusch",
	["REG_PLAYER_PSYCHO_Conciliant"] = "Vorbildlich",
	["REG_PLAYER_PSYCHO_Couard"] = "Rückgratlos",
	["REG_PLAYER_PSYCHO_CREATENEW"] = "Erstelle einen Wert",
	["REG_PLAYER_PSYCHO_Cruel"] = "Brutal",
	["REG_PLAYER_PSYCHO_CUSTOM"] = "Benutzerdefinierter Wert",
	["REG_PLAYER_PSYCHO_CUSTOMCOLOR"] = "Attributsfarbe auswählen",
	["REG_PLAYER_PSYCHO_CUSTOMCOLOR_LEFT_TT"] = "Wähle eine Farbe, die das linke Merkmal benutzt. |cffffff00Klick:|r Farbe auswählen |cffffff00Rechts-Klick:|r Farbe zurücksetzen |cffffff00Shift-Klick:|r Die Standard Farbauswahl benutzen.",
	["REG_PLAYER_PSYCHO_CUSTOMCOLOR_RIGHT_TT"] = "Wähle eine Farbe, die das rechte Merkmal benutzt. |cffffff00Klick:|r Farbe auswählen |cffffff00Rechts-Klick:|r Farbe zurücksetzen |cffffff00Shift-Klick:|r Die Standard Farbauswahl benutzen.",
	["REG_PLAYER_PSYCHO_Egoiste"] = "Egoistisch",
	["REG_PLAYER_PSYCHO_Genereux"] = "Altruistisch",
	["REG_PLAYER_PSYCHO_Impulsif"] = "Impulsiv",
	["REG_PLAYER_PSYCHO_Indulgent"] = "Vergebend",
	["REG_PLAYER_PSYCHO_LEFTICON_TT"] = "Linkes Attributsicon auswählen.",
	["REG_PLAYER_PSYCHO_Loyal"] = "Rechtschaffen",
	["REG_PLAYER_PSYCHO_Luxurieux"] = "Lüstern",
	["REG_PLAYER_PSYCHO_Misericordieux"] = "Sanft",
	["REG_PLAYER_PSYCHO_MORE"] = "Punkt zu \"%s\" hinzufügen",
	["REG_PLAYER_PSYCHO_PERSONAL"] = "Persönliche Werte",
	["REG_PLAYER_PSYCHO_Pieux"] = "Abergläubisch",
	["REG_PLAYER_PSYCHO_POINT"] = "Punkt hinzufügen",
	["REG_PLAYER_PSYCHO_Pragmatique"] = "Abtrünnig",
	["REG_PLAYER_PSYCHO_Rationnel"] = "Rational",
	["REG_PLAYER_PSYCHO_Reflechi"] = "Vorsichtig",
	["REG_PLAYER_PSYCHO_Rencunier"] = "Rachsüchtig",
	["REG_PLAYER_PSYCHO_RIGHTICON_TT"] = "Rechtes Attributsicon auswählen.",
	["REG_PLAYER_PSYCHO_Sincere"] = "Ehrlich",
	["REG_PLAYER_PSYCHO_SOCIAL"] = "Soziale Werte",
	["REG_PLAYER_PSYCHO_Trompeur"] = "Unehrlich",
	["REG_PLAYER_PSYCHO_Valeureux"] = "Tapfer",
	["REG_PLAYER_RACE"] = "Rasse",
	["REG_PLAYER_RACE_TT"] = "Hier gehört die Rasse des Charakters hin. Die Rasse muss nicht der Spielrasse entsprechen. Es gibt im Warcraft-Universum genügend Kreaturen, die sich ähnlich sehen.",
	["REG_PLAYER_REGISTER"] = "Registerinformationen",
	["REG_PLAYER_RELATIONSHIP_STATUS"] = "Beziehungsstatus ",
	["REG_PLAYER_RELATIONSHIP_STATUS_DIVORCED"] = "Geschieden",
	["REG_PLAYER_RELATIONSHIP_STATUS_MARRIED"] = "Verheiratet",
	["REG_PLAYER_RELATIONSHIP_STATUS_SINGLE"] = "Ledig",
	["REG_PLAYER_RELATIONSHIP_STATUS_TAKEN"] = "Vergeben",
	["REG_PLAYER_RELATIONSHIP_STATUS_TT"] = "Zeigt den Beziehungsstatus deines Charakters. Benutze \"Nicht zeigen\" wenn diese Information geheim bleiben soll.",
	["REG_PLAYER_RELATIONSHIP_STATUS_UNKNOWN"] = "Nicht zeigen",
	["REG_PLAYER_RELATIONSHIP_STATUS_WIDOWED"] = "Verwitwet",
	["REG_PLAYER_RESIDENCE"] = "Heimat",
	["REG_PLAYER_RESIDENCE_SHOW"] = "Wohnort Koordinaten",
	["REG_PLAYER_RESIDENCE_SHOW_TT"] = [=[|cff00ff00%s

|rZum Anzeigen auf Karte klicken]=],
	["REG_PLAYER_RESIDENCE_TT"] = [=[Hier kannst du angeben, wo dein Charakter normalerweise lebt. Das kann eine genaue Adresse sein (dein Heim) oder einfach der Ort oder die Region, in der dein Charakter lebt.
Wenn dein Charakter obdachlos ist oder durch die Welt streift, dann denke daran, die Informationen anzupassen.

|c00ffff00Du kannst den rechten Button verwenden, um ganz einfach den aktuellen Ort als deinen Wohnort festzulegen.]=],
	["REG_PLAYER_RIGHTTRAIT"] = "Rechtes Attribut",
	["REG_PLAYER_SHOWMISC"] = "Zeige Sonstiges Frame",
	["REG_PLAYER_SHOWMISC_TT"] = [=[Anwählen, wenn du benutzerdefinierte Felder auf deinem Charakter anzeigen möchtest.

Wenn du die benutzerdefinierten Felder nicht angezeigt haben willst lasse das Häkchen weg und das Sonstiges Frame wird komplett deaktiviert.]=],
	["REG_PLAYER_SHOWPSYCHO"] = "Zeige Persönlichkeitsfenster",
	["REG_PLAYER_SHOWPSYCHO_TT"] = [=[Anwählen, wenn du die Persönlichkeitsbeschreibung nutzen möchtest.

Wenn du die Persönlichkeit deines Charakter auf diese Art nicht angeben möchtest, dann wähle die Option nicht aus und das Persönlichkeitsfenster wird nicht angezeigt werden.]=],
	["REG_PLAYER_STYLE_DEATH"] = "Akzeptiere Charaktertod",
	["REG_PLAYER_STYLE_EMPTY"] = "Kein Rollenspielattribut geteilt",
	["REG_PLAYER_STYLE_GUILD"] = "Gildenmitgliedschaft",
	["REG_PLAYER_STYLE_GUILD_IC"] = "IC Mitglied",
	["REG_PLAYER_STYLE_GUILD_OOC"] = "OOC Mitglied",
	["REG_PLAYER_STYLE_HIDE"] = "Nicht anzeigen",
	["REG_PLAYER_STYLE_INJURY"] = "Akzeptiere Charakterverletzungen",
	["REG_PLAYER_STYLE_PERMI"] = "Mit Spielererlaubnis",
	["REG_PLAYER_STYLE_ROMANCE"] = "Akzeptiere Charakterromanze",
	["REG_PLAYER_STYLE_RPSTYLE"] = "Rollenspielstil",
	["REG_PLAYER_TITLE"] = "Titel",
	["REG_PLAYER_TITLE_TT"] = [=[Der Titel deines Charakters ist der Titel, mit dem er angesprochen wird. Vermeide bitte lange Titel, für diesen Zweck kannst du das Feld "Kompletter Titel" verwenden.

Beispiele |c0000ff00passender Titel|r :
|c0000ff00- Graf,
- Vogt,
- Magier,
- Lord,
- etc.
|rBeispiele |cffff0000unpassender Titel|r:
|cffff0000- Graf der Nordmarschen,
- Erzmagier des Zirkels von Sturmwind,
- Diplomat der Draenei,
- etc.]=],
	["REG_PLAYER_TRP2_PIERCING"] = "Piercings",
	["REG_PLAYER_TRP2_TATTOO"] = "Tattoos",
	["REG_PLAYER_TRP2_TRAITS"] = "Aussehen",
	["REG_PLAYER_TUTO_ABOUT_COMMON"] = [=[|cff00ff00Charaktersoundtrack:|r
Du kannst einen |cffffff00Soundtrack|r für deinen Charakter aussuchen. Stell es dir als |cffffff00Hintergundmusik beim Lesen deiner Charakterbeschreibung vor|r.

|cff00ff00Hintergund:|r
Dies ist eine |cffffff00Hintergrundtextur|r für deine Charakterbeschreibung.

|cff00ff00Template:|r
Das gewählte Template gibt Auskunft über |cffffff00das generelle Aussehen und die Schriftmöglichkeiten|r deiner Beschreibung.
|cffff9900Nur das ausgewählte Template ist für andere sichtbar. Du musst also nicht alle ausfüllen.|r
Sobald ein Template ausgewählt ist, kannst du das Tutorial nochmals öffnen, um dir Hilfe zu jedem Template anzeigen zu lassen.]=],
	["REG_PLAYER_TUTO_ABOUT_MISC_1"] = [=[Dieser Teil stellt dir |cnGREEN_FONT_COLOR:5 Slots|r zur Verfügung, in denen du die |cnGREEN_FONT_COLOR:wichtigsten Informationen zu deinem Charakter|r beschreiben kannst.

Die Slots sind in |cnGREEN_FONT_COLOR:"Auf den ersten Blick"|r ersichtlich wenn jemand deinen Charakter anwählt.

|cff00ff00Hinweis: Du kannst die Slots per Drag&Drop neu anordnen.|r
Das funktioniert auch in der Sektion |cnGREEN_FONT_COLOR:"Auf den ersten Blick"|r!]=],
	["REG_PLAYER_TUTO_ABOUT_MISC_3"] = "Dieser Teil enthält |cnGREEN_FONT_COLOR:eine Liste von Informationen|r, die eine Menge |cnGREEN_FONT_COLOR:einfache Fragen|r zu der Art, wie du deinen Charakter spielst, beantwortet.",
	["REG_PLAYER_TUTO_ABOUT_T1"] = [=[Dieses Template erlaubt dir deine |cff00ff00Beschreibung frei zu gestalten|r.

Die Beschreibung muss nicht auf die |cffff9900physische Beschreibung|r deines Charakters beschränkt sein. Gibt ruhig Teile seines |cffff9900Hintergrundes|r oder Details zu seiner |cffff9900Persönlichkeit|r an.

Mit diesem Template hast du Zugriff auf die Formatierungstools, um beispielsweise |cffffff00Schriftgröße, Farben und Ausrichtung|r zu beeinflussen.
Diese Tools erlauben auch das Einfügen von |cffffff00Bildern, Icons oder Links zu externen Internetseiten|r.]=],
	["REG_PLAYER_TUTO_ABOUT_T2"] = [=[Dieses Template ist ein wenig strukturierter und besteht aus |cff00ff00einer Reihe unabhängiger Fenster|r.

Jedes Fenster wird von einem eigenen |cffffff00Icon, einem Hintergrund und eineem Text|r repräsentiert. Beachte das du hier Texttags in diesen Fenstern nutzen kannst, genauso kannst du auch Farb- oder Icon-Tags verwenden.

Die Beschreibung muss nicht auf die |cffff9900physische Beschreibung|r deines Charakters beschränkt sein. Gibt ruhig Teile seines |cffff9900Hintergrundes|r oder Details zu seiner |cffff9900Persönlichkeit|r an.]=],
	["REG_PLAYER_TUTO_ABOUT_T3"] = [=[Dieses Template ist in 3 Teile unterteilt: |cff00ff00Die Physische Beschreibung, Persönlichkeit und Hintergrundgeschichte|r.

Du musst nicht alle Fenster ausfüllen, |cffff9900wenn du eines frei läßt wird es in deiner Beschreibung einfach nicht angezeigt|r.

Jedes Fenster wird von einem eigenen |cffffff00Icon, einem Hintergrund und einem Text|r repräsentiert. Beachte das du hier Texttags in diesen Fenstern nutzen kannst, genauso kannst du auch Farb- oder Icon-Tags verwenden.]=],
	["REG_PLAYER_WEIGHT"] = "Körperform",
	["REG_PLAYER_WEIGHT_TT"] = [=[Dies ist die Körperform deines Charakters.
Zum Beispiel kann du folgendes angeben: |c0000ff00schlank, dick or muskulös...|r oder einfach durchschnittlich!]=],
	["REG_PLAYERS"] = "Spieler",
	["REG_REGISTER"] = "Register",
	["REG_REGISTER_CHAR_LIST"] = "Charakterliste",
	["REG_RELATION"] = "Beziehung",
	["REG_RELATION_BUSINESS"] = "Geschäftlich",
	["REG_RELATION_BUSINESS_TT"] = "%s und %s haben eine Geschäftsbeziehung.",
	["REG_RELATION_BUTTON_TT"] = [=[Beziehung: %s
|cff00ff00%s

|cffffff00Klicke, um mögliche Aktionen zu wählen]=],
	["REG_RELATION_FAMILY"] = "Familie",
	["REG_RELATION_FAMILY_TT"] = "%s hat Blutsbande mit %s.",
	["REG_RELATION_FRIEND"] = "Freundlich",
	["REG_RELATION_FRIEND_TT"] = "%s nennt %s einen Freund.",
	["REG_RELATION_LOVE"] = "Liebe",
	["REG_RELATION_LOVE_TT"] = "%s ist in %s verliebt!",
	["REG_RELATION_NEUTRAL"] = "Neutral",
	["REG_RELATION_NEUTRAL_TT"] = "%s hat keine spezielle Beziehung zu %s.",
	["REG_RELATION_NONE"] = "Keine",
	["REG_RELATION_NONE_TT"] = "%s kennt %s nicht.",
	["REG_RELATION_TARGET"] = "|cffffff00Klick:|r Beziehung ändern",
	["REG_RELATION_UNFRIENDLY"] = "Unfreundlich",
	["REG_RELATION_UNFRIENDLY_TT"] = "%s mag %s offensichtlich nicht.",
	["REG_REPORT_PLAYER_OPEN_URL"] = "Du kannst Spieler nur direkt im Spiel melden, wenn du sie anvisieren kannst (benutze dafür den Button im TRP3 Ankerfenster) Wenn du %s's Profil melden möchtest, aber nicht anvisieren kannst, musst du ein normales Kundendienstticket bei Blizzard über den folgenden Link öffnen.",
	["REG_REPORT_PLAYER_OPEN_URL_160"] = "Wenn du %s's Profil melden möchtest, musst du ein normales Kundendienstticket bei Blizzard über den folgenden Link öffnen.",
	["REG_REPORT_PLAYER_PROFILE"] = "Profil an |cff449fe0Blizzard|r melden.",
	["REG_REPORT_PLAYER_PROFILE_TT"] = "Du kannst ein Profil melden, welches die Nutzungsbedingungen von Blizzard verletzt. Dies können Belästigungen, Hasssprache, anstößige Inhalte, der Missbrauch persönlicher Daten oder andere Formen von störenden Inhalten sein.  |cffff0000Bitte beachte, dass diese Option NICHT dafür gedacht ist Profile von subjektiv schlechter Qualität oder Griefing zu melden.",
	["REG_REPORT_PLAYER_TEMPLATE"] = "Dieser Spieler benutzt das RP Profil Addon %s um Inhalte zu verbreiten, die die Nutzungsbedingungen verletzen.. ",
	["REG_REPORT_PLAYER_TEMPLATE_DATE"] = "Die Addon Daten wurden am %s über aufgezeichnete Addon Nachrichten übermittelt. ",
	["REG_REPORT_PLAYER_TEMPLATE_TRIAL_ACCOUNT"] = "Dieser Spieler benutze einen Starter Edition Account.",
	["REG_TIME"] = "Zuletzt gesehen",
	["REG_TRIAL_ACCOUNT"] = "Probeaccount",
	["REG_TT_GUILD"] = "%s von %s",
	["REG_TT_GUILD_IC"] = "IC Mitglied",
	["REG_TT_GUILD_OOC"] = "OOC Mitglied",
	["REG_TT_IGNORED"] = "< Charakter ist ignoriert >",
	["REG_TT_IGNORED_OWNER"] = "< Besitzer ist ignoriert >",
	["REG_TT_LEVEL"] = "Level %s %s",
	["REG_TT_NOTIF"] = "Ungelesene Beschreibung",
	["REG_TT_REALM"] = "Realm: |cffff9900%s",
	["REG_TT_TARGET"] = "Ziel: |cffff9900%s",
	["SCRIPT_ERROR"] = "Fehler im Script.",
	["SCRIPT_UNKNOWN_EFFECT"] = "Scriptfehler, unbekannte FX",
	["SLASH_CMD_STATUS_HELP"] = "Benutzung: |cff00ff00/trp3 status ic || ooc || toggle|r Wechselt deinen Charakter Status zu der entsprechenden Option: |cffff9900/trp3 status ic|r setzt deinen Status auf |cff00ff00in character|r. |cffff9900/trp3 status ooc|r setzt deinen Status auf  |cffff0000out of character|r. |cffff9900/trp3 status toggle|r wechselt deinen Status von ic zu ooc und vice versa.",
	["SLASH_CMD_STATUS_USAGE"] = "ic || ooc || toggle",
	["TB_AFK_MODE"] = "AFK",
	["TB_DND_MODE"] = "Nicht stören (DnD)",
	["TB_GO_TO_MODE"] = "Zu %s Modus wechseln",
	["TB_LANGUAGE"] = "Sprache",
	["TB_LANGUAGES_TT"] = "Sprache wechseln",
	["TB_NORMAL_MODE"] = "Normal",
	["TB_RPSTATUS_OFF"] = "Charakter: |cffff0000Out of Character (OOC) ",
	["TB_RPSTATUS_ON"] = "Charakter: |cff00ff00In Character (IC) ",
	["TB_RPSTATUS_TO_OFF"] = "Zu |cffff0000Out of Character|r wechseln.",
	["TB_RPSTATUS_TO_ON"] = "Zu |cff00ff00In Character|r wechseln.",
	["TB_STATUS"] = "Spieler",
	["TB_SWITCH_CAPE_1"] = "Zeige Umhang",
	["TB_SWITCH_CAPE_2"] = "Verstecke Umhang",
	["TB_SWITCH_CAPE_OFF"] = "Umhang: |cffff0000Versteckt",
	["TB_SWITCH_CAPE_ON"] = "Umhang: |cff00ff00Angezeigt",
	["TB_SWITCH_HELM_1"] = "Zeige Helm",
	["TB_SWITCH_HELM_2"] = "Verstecke Helm",
	["TB_SWITCH_HELM_OFF"] = "Helm: |cffff0000Versteckt",
	["TB_SWITCH_HELM_ON"] = "Helm: |cff00ff00Angezeigt",
	["TB_SWITCH_PROFILE"] = "Zu einem anderen Profil wechseln",
	["TB_SWITCH_TOOLBAR"] = "Toolbar umschalten",
	["TB_TOOLBAR"] = "Toolbar",
	["TF_IGNORE"] = "Spieler ignorieren",
	["TF_IGNORE_CONFIRM"] = [=[Bist du sicher das du die folgende ID ignorieren willst?

|cffffff00%s|r

|cffff7700Du kannst optional angeben, warum die diesen Spieler ignorierst. Dies ist eine persönliche Notiz und kann nicht von anderen Spielern eingesehen werden.]=],
	["TF_IGNORE_NO_REASON"] = "Kein Grund",
	["TF_IGNORE_TT"] = "|cffffff00Klicken:|r Spieler ignorieren",
	["TF_OPEN_CHARACTER"] = "Charakterseite anzeigen",
	["TF_OPEN_COMPANION"] = "Begleiterseite anzeigen",
	["TF_OPEN_MOUNT"] = "Reittierseite anzeigen",
	["TF_PLAY_THEME"] = "Charaktersoundtrack abspielen",
	["TF_PLAY_THEME_TT"] = [=[|cffffff00Linksklick:|r Abspielen |cff00ff00%s
|cffffff00Rechtsklick:|r Anhalten]=],
	["THANK_YOU_1"] = [=[{h1:c}Total RP 3{/h1}
{p:c}{col:6eff51}Version %s (build %s){/col}{/p}
{p:c}{link*http://totalrp3.info*TotalRP3.info}{/p}

{h2}{icon:INV_Eng_gizmo1:20} Created by{/h2}
- Morgane "{twitter*EllypseCelwe*Ellypse}" Parize
- Sylvain "{twitter*Telkostrasz*Telkostrasz}" Cossement


{h2}{icon:THUMBUP:20} Danksagungen{/h2}
{col:ffffff}Logo and minimap button icon:{/col}
- {link*https://twitter.com/Kelandiir*@Kelandiir}

{col:ffffff}Unser Pre-Alpha QA Team:{/col}
- Saelora
- Erzan
- Calian
- Kharess
- Alnih
- 611

{col:ffffff}Danke an alle unsere Freunde für Ihre Unterstützung in all diesen Jahren:{/col}
- Für Telkos: Kharess, Kathryl, Marud, Solona, Stretcher, Lisma...
- Für Ellypse: The guilds Maison Celwë'Belore, Mercenaires Atal'ai, und ganz besonders Erzan, Elenna, Caleb, Siana and Adaeria

{col:ffffff}Danke für die Hilfe die "Total RP Gilde" auf Kirin Tor (EU) zu erstellen:{/col}
- Azane
- Hellclaw
- Leylou

{col:ffffff}Danke an Horionne für das zusend einer Ausgabe von dem Magazin "Gamer Culte Online #14" mit einem Artikel über Total RP.{/col}]=],
	["THANK_YOU_ROLE_AUTHOR"] = "Autor",
	["THANK_YOU_ROLE_COMMUNITY_MANAGER"] = "Community Manager",
	["THANK_YOU_ROLE_CONTRIBUTOR"] = "Mitwirkende(r)",
	["THANK_YOU_ROLE_GUILD_MEMBER"] = "Gildenmitglied",
	["THANK_YOU_ROLE_TESTER"] = "Qualitätssicherung",
	["TT_ELVUI_SKIN"] = "ElvUI Skin",
	["TT_ELVUI_SKIN_ENABLE_TARGET_FRAME"] = "Skin Zielfenster",
	["TT_ELVUI_SKIN_ENABLE_TOOLTIPS"] = "Skin Tooltips",
	["UI_BKG"] = "Hintergrund %s",
	["UI_CLOSE_ALL"] = "Alle schließen",
	["UI_COLOR_BROWSER"] = "Farbwähler",
	["UI_COLOR_BROWSER_PRESETS"] = "Voreinstellungen",
	["UI_COLOR_BROWSER_PRESETS_BASIC"] = "Basis",
	["UI_COLOR_BROWSER_PRESETS_CLASSES"] = "Klasse",
	["UI_COLOR_BROWSER_PRESETS_CUSTOM"] = "Eigene",
	["UI_COLOR_BROWSER_PRESETS_ITEMS"] = "Gegenstandsqualität",
	["UI_COLOR_BROWSER_PRESETS_RESOURCES"] = "Ressource",
	["UI_COLOR_BROWSER_SELECT"] = "Farbe auswählen",
	["UI_COMPANION_BROWSER_HELP"] = "Wähle ein Wildtier",
	["UI_COMPANION_BROWSER_HELP_TT"] = [=[|cffffff00Warnung:|r Nur umbenannte Wildtiere dürfen mit einem Profil verbunden werden.

|cff00ff00Dieser Bereich enthält nur diese Wildtiere.]=],
	["UI_FILTER"] = "Filter",
	["UI_ICON_BROWSER"] = "Iconbrowser",
	["UI_ICON_BROWSER_HELP"] = "Icon kopieren",
	["UI_ICON_BROWSER_HELP_TT"] = [=[Während dieses Fenter geöffnet ist, kannst du mit |cffffff00ctrl + Klick|r auf ein Icon anwenden, um dessen Namen zu kopieren.

Das funktioniert:|cff00ff00
- Mit jedem Item in deinem Inventar
- Mit jeder Fähigkeit in deinem Zauberbuch|r]=],
	["UI_ICON_SELECT"] = "Icon auswählen",
	["UI_IMAGE_BROWSER"] = "Bildbrowser",
	["UI_IMAGE_SELECT"] = "Bild auswählen",
	["UI_LINK_SAFE"] = "Das ist die Link-URL.",
	["UI_LINK_TEXT"] = "Dein Text",
	["UI_LINK_URL"] = "http://deine.url.hier.de",
	["UI_LINK_WARNING"] = [=[Hier ist die Link URL.
Du kannst sie per Copy/Paste in deinen Browser kopieren.

|cffff0000!! Disclaimer !!|r
Total RP ist NICHT für Links verantwortlich, die auf schädlichen oder illegalen Inhalt verweisen!]=],
	["UI_MUSIC_ALTTITLE"] = "Alternativer Titel",
	["UI_MUSIC_BROWSER"] = "Musikbrowser",
	["UI_MUSIC_DURATION"] = "Dauer",
	["UI_MUSIC_SELECT"] = "Musik auswählen",
	["UI_TUTO_BUTTON"] = "Tutorialmodus",
	["UI_TUTO_BUTTON_TT"] = "Klicke, um den Tutorialmodus ein/aus zu schalten"
};

TRP3_API.loc:RegisterNewLocale("deDE", "Deutsch", L);
