-- Copyright The Total RP 3 Authors
-- SPDX-License-Identifier: Apache-2.0

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- ALL MODIFICATIONS TO THIS FILE WILL BE LOST.

local _, TRP3_API = ...;

local L;

L = {
	["ABOUT_TITLE"] = "Acerca de",
	["BINDING_NAME_TRP3_OPEN_TARGET_PROFILE"] = "Abrir perfil del objetivo",
	["BINDING_NAME_TRP3_TOGGLE"] = "Mostrar/ocultar la ventana principal",
	["BINDING_NAME_TRP3_TOGGLE_CHARACTER_STATUS"] = "Mostrar/ocultar estado del personaje",
	["BINDING_NAME_TRP3_TOOLBAR_TOGGLE"] = "Mostrar/ocultar barra de herramientas",
	["BLIZZARD_NAMEPLATES_MODULE_DESCRIPTION"] = "Habilitar la personalización de las placas de nombres por defecto de Blizzard.",
	["BLIZZARD_NAMEPLATES_MODULE_NAME"] = "Placa de nombres de Blizzard",
	["BROADCAST_10"] = "|cffff9900Ya estás en 10 canales. TRP3 no intentará conectar de nuevo con el canal de emisión pero no podrás usar algunas características como la localización de jugadores en el mapa.",
	["BROADCAST_OFFLINE_DISABLED"] = "La emisión ha sido deshabilitada.",
	["BROADCAST_PASSWORD"] = [=[|cffff0000Hay una contraseña para el canal de emisión (%s).
|cffff9900TRP3 no intentará conectarse de nuevo pero no podrás usar algunas características como la localización de jugadores en el mapa.
|cff00ff00Puedes deshabilitar o cambiar de canal de emisión en la configuración general de TRP3.]=],
	["BROADCAST_PASSWORDED"] = [=[|cffff0000El usuario|r %s |cffff0000ha puesto contraseña para el canal de emisión (%s).
|cffff9900Si no conoces la contraseña, no podrás usar algunas características como la localización de personajes en el mapa.]=],
	["BW_COLOR_CODE"] = "Código de color",
	["BW_COLOR_CODE_ALERT"] = "¡Código hexadecimal erróneo!",
	["BW_COLOR_CODE_TT"] = "Pega un código hexadecimal de 6 cifras aquí y presiona Enter.",
	["BW_COLOR_PRESET_DELETE"] = "Borrar %s preestablecido",
	["BW_COLOR_PRESET_RENAME"] = "Renombrar %s preestablecido",
	["BW_COLOR_PRESET_SAVE"] = "Guardar color actual",
	["BW_COLOR_PRESET_TITLE"] = "Colores preestablecidos",
	["BW_CUSTOM_NAME"] = "Color del nombre personalizado",
	["BW_CUSTOM_NAME_TITLE"] = "Nombre (Opcional)",
	["BW_CUSTOM_NAME_TT"] = "Puedes poner un nombre para el color personalizado que vas a guardar. Si se deja vacío, se usará el código hexadecimal para el color.",
	["CL_COMPANION_PROFILE"] = "Perfil del compañero",
	["CL_CONTENT_SIZE"] = "Tamaño: %s",
	["CL_DIRECTORY_COMPANION_PROFILE"] = "Directorio de perfiles de compañero",
	["CL_DIRECTORY_PLAYER_PROFILE"] = "Directorio de perfiles de jugador",
	["CL_DOWNLOADING"] = "Descargando: %0.1f %%",
	["CL_EXPIRED"] = "Este enlace ha caducado.",
	["CL_GLANCE"] = "A primera vista",
	["CL_IMPORT_COMPANION"] = "Importar perfil de compañero",
	["CL_IMPORT_GLANCE"] = "Importar a primera vista",
	["CL_IMPORT_PROFILE"] = "Importar perfil",
	["CL_MAKE_IMPORTABLE_BUTTON_TEXT"] = "Hacer importable",
	["CL_MAKE_IMPORTABLE_SIMPLER"] = [=[¿Hacer el enlace %s importable?

Otros podrán copiar y usar el contenido del enlace.]=],
	["CL_MAKE_NON_IMPORTABLE"] = "Ver solo",
	["CL_OPEN_COMPANION"] = "Abrir perfil del compañero.",
	["CL_OPEN_PROFILE"] = "Abrir perfil",
	["CL_PLAYER_PROFILE"] = "Perfil de jugador",
	["CL_REQUESTING_DATA"] = "Solicitando datos del link de %s.",
	["CL_SENDING_COMMAND"] = "Enviando comando...",
	["CL_SENT_BY"] = "Enlace enviado por: %s",
	["CL_TOOLTIP"] = "Crear un enlace de chat",
	["CL_TYPE"] = "Tipo de enlace TRP3: %s",
	["CL_VERSIONS_DIFFER"] = [=[Este link se ha generado usando una versión diferente de Total RP 3.

Importar contenido de otra versión puede causar problemas en caso de incompatibilidaes. ¿Quieres proceder aún así?]=],
	["CM_ACTIONS"] = "Acciones",
	["CM_ALT"] = "Alt",
	["CM_APPLY"] = "Aplicar",
	["CM_BLACK"] = "Negro",
	["CM_BLUE"] = "Azul",
	["CM_CANCEL"] = "Cancelar",
	["CM_CENTER"] = "Centro",
	["CM_CLASS_DEATHKNIGHT"] = "Caballero de la muerte",
	["CM_CLASS_DEMONHUNTER"] = "Cazador de demonios",
	["CM_CLASS_DRUID"] = "Druida",
	["CM_CLASS_HUNTER"] = "Cazador",
	["CM_CLASS_MAGE"] = "Mago",
	["CM_CLASS_MONK"] = "Monje",
	["CM_CLASS_PALADIN"] = "Paladín",
	["CM_CLASS_PRIEST"] = "Sacerdote",
	["CM_CLASS_ROGUE"] = "Pícaro",
	["CM_CLASS_SHAMAN"] = "Chamán",
	["CM_CLASS_UNKNOWN"] = "Desconocido",
	["CM_CLASS_WARLOCK"] = "Brujo",
	["CM_CLASS_WARRIOR"] = "Guerrero",
	["CM_CLICK"] = "Click",
	["CM_COLOR"] = "Color",
	["CM_CTRL"] = "Ctrl",
	["CM_CYAN"] = "Cian",
	["CM_DELETE"] = "Borrar",
	["CM_DOUBLECLICK"] = "Doble click",
	["CM_DRAGDROP"] = "Arrastrar y soltar",
	["CM_EDIT"] = "Editar",
	["CM_GREEN"] = "Verde",
	["CM_GREY"] = "Gris",
	["CM_IC"] = "IC",
	["CM_ICON"] = "Icono",
	["CM_IMAGE"] = "Imagen",
	["CM_L_CLICK"] = "Click izquierdo",
	["CM_LEFT"] = "Izquierda",
	["CM_LINK"] = "Enlace",
	["CM_LOAD"] = "Cargar",
	["CM_M_CLICK"] = "Click botón central",
	["CM_MOVE_DOWN"] = "Mover hacia abajo",
	["CM_MOVE_UP"] = "Mover hacia arriba",
	["CM_NAME"] = "Nombre",
	["CM_OOC"] = "FdR",
	["CM_OPEN"] = "Abrir",
	["CM_ORANGE"] = "Naranja",
	["CM_PINK"] = "Rosa",
	["CM_PLAY"] = "Reproducir",
	["CM_PURPLE"] = "Morado",
	["CM_R_CLICK"] = "Click derecho",
	["CM_RED"] = "Rojo",
	["CM_REMOVE"] = "Suprimir",
	["CM_RESET"] = "Reiniciar",
	["CM_RESIZE"] = "Redimensionar",
	["CM_RESIZE_TT"] = "Arrastra para redimensionar la ventana.",
	["CM_RIGHT"] = "Derecha",
	["CM_SAVE"] = "Guardar",
	["CM_SELECT"] = "Seleccionar",
	["CM_SHIFT"] = "Shift",
	["CM_SHOW"] = "Mostrar",
	["CM_STOP"] = "Parar",
	["CM_TWEET"] = "Enviar un tweet",
	["CM_TWEET_PROFILE"] = "Mostrar url del perfil",
	["CM_UNKNOWN"] = "Desconocido",
	["CM_VALUE"] = "Valor",
	["CM_WHITE"] = "Blanco",
	["CM_YELLOW"] = "Amarillo",
	["CO_ADVANCED_BROADCAST"] = "Comunicaciones del add-on",
	["CO_ADVANCED_BROADCAST_CHANNEL_ALWAYS_LAST"] = "Mantener el canal de emisión al final",
	["CO_ADVANCED_BROADCAST_CHANNEL_ALWAYS_LAST_TT"] = "Esta opción hará que el canal de emisión siempre sea el último en tu lista de canales.",
	["CO_ADVANCED_LANGUAGE_WORKAROUND"] = "Habilitar solución al reinicio de idiomas",
	["CO_ADVANCED_LANGUAGE_WORKAROUND_TT"] = "Desde el parche 8.0.1, el juego reiniciará el idioma seleccionado al idioma por defecto de tu facción durante cada pantalla de carga. Esta solución se asegura de restaurar el idioma seleccionado tras cada pantalla de carga.",
	["CO_ADVANCED_LANGUAGES"] = "Idiomas",
	["CO_ADVANCED_LANGUAGES_REMEMBER"] = "Recordar último idioma usado",
	["CO_ADVANCED_LANGUAGES_REMEMBER_TT"] = "Total RP 3 recordará el último idioma que estabas usando antes de desconectar y lo seleccionará automáticamente en tu próxima conexión.",
	["CO_ADVANCED_SETTINGS"] = "Configuración avanzada",
	["CO_ADVANCED_SETTINGS_MENU_NAME"] = "Avanzado",
	["CO_ADVANCED_SETTINGS_POPUP"] = [=[Acabas de modificar una configuración avanzada.

Por favor, ten en cuenta que cambiar esta configuración puede alterar tu experiencia con el add-on y podría hacer que algunas características no funcionen del todo bien. Úsalo bajo tu responsabilidad.]=],
	["CO_ADVANCED_SETTINGS_RESET"] = "Reiniciar configuración avanzada",
	["CO_ADVANCED_SETTINGS_RESET_TT"] = "Reinicia toda la configuración avanzada a sus valores por defecto. Usa esto si tienes problemas tras modificar la configuración.",
	["CO_ANCHOR_BOTTOM"] = "Abajo",
	["CO_ANCHOR_BOTTOM_LEFT"] = "Abajo a la izquierda",
	["CO_ANCHOR_BOTTOM_RIGHT"] = "Abajo a la derecha",
	["CO_ANCHOR_CURSOR"] = "Mostrar en el cursor",
	["CO_ANCHOR_LEFT"] = "Izquierda",
	["CO_ANCHOR_RIGHT"] = "Derecha",
	["CO_ANCHOR_TOP"] = "Parte superior",
	["CO_ANCHOR_TOP_LEFT"] = "Parte superior izquierda",
	["CO_ANCHOR_TOP_RIGHT"] = "Parte superior derecha",
	["CO_CHAT"] = "Marco del chat",
	["CO_CHAT_DISABLE_OOC"] = "Deshabilitar personalizaciones cuando se está FDP",
	["CO_CHAT_DISABLE_OOC_TT"] = "Deshabilita todas las personalizaciones de chat del Total RP 3 (nombres personalizados, detección de emotes, diálogos de NPC, etc.) cuando tu personaje está puesto como Fuera de Personaje.",
	["CO_CHAT_INCREASE_CONTRAST"] = "Aumentar contraste de color",
	["CO_CHAT_INSERT_FULL_RP_NAME"] = "Insertar nombres de rol con shift+clic",
	["CO_CHAT_INSERT_FULL_RP_NAME_TT"] = [=[Insertar el nombre completo de rol de un jugador cuando se haga shift+clic en su nombre en la ventana de chat.

(Cuando se habilita esta opción, puedes hacer alt-shift-clic en un nombre cuando quieras que haga lo habitual e inserte el nombre del personaje en lugar del nombre completo de rol.)]=],
	["CO_CHAT_MAIN"] = "Ajustes de chat principal",
	["CO_CHAT_MAIN_COLOR"] = "Usar colores personalizados para los nombres",
	["CO_CHAT_MAIN_EMOTE"] = "Detección de emociones",
	["CO_CHAT_MAIN_EMOTE_PATTERN"] = "Patrón de detección de emociones",
	["CO_CHAT_MAIN_EMOTE_USE"] = "Usar detección de emociones",
	["CO_CHAT_MAIN_EMOTE_YELL"] = "Emoción sin gritos",
	["CO_CHAT_MAIN_EMOTE_YELL_TT"] = "No mostrar *emote* o <emote> en los gitos",
	["CO_CHAT_MAIN_NAMING"] = "Método de nomenclatura",
	["CO_CHAT_MAIN_NAMING_1"] = "Mantener nombres originales",
	["CO_CHAT_MAIN_NAMING_2"] = "Usar nombres originales",
	["CO_CHAT_MAIN_NAMING_3"] = "Nombre + apellido",
	["CO_CHAT_MAIN_NAMING_4"] = "Título corto + nombre + apellido",
	["CO_CHAT_MAIN_NPC"] = "Detección de diálogo de NPC",
	["CO_CHAT_MAIN_NPC_PREFIX"] = "Patrón de detección de diálogo de NPC",
	["CO_CHAT_MAIN_NPC_PREFIX_TT"] = [=[Si un mensaje enviado por el canal /EMOTE comienza con este prefijo, se interpretará como un diálogo de NPC.

|cff00ff00Por defecto: "|| "
(Sin el " y con un espacio después del I)|r]=],
	["CO_CHAT_MAIN_NPC_USE"] = "Usar detección de diálogo de NPC",
	["CO_CHAT_MAIN_OOC"] = "Detección OOC",
	["CO_CHAT_MAIN_OOC_COLOR"] = "Color OOC",
	["CO_CHAT_MAIN_OOC_PATTERN"] = "Patrón de detección OOC",
	["CO_CHAT_MAIN_OOC_USE"] = "Usar detección OOC",
	["CO_CHAT_MAIN_SPEECH"] = "Detección de voz",
	["CO_CHAT_MAIN_SPEECH_USE"] = "Usar detección de voz",
	["CO_CHAT_MAIN_SPEECH_USE_TT"] = "El texto entre comillas se mostrará con el color como si se hubiera escrito con /decir.",
	["CO_CHAT_NPCSPEECH_REPLACEMENT"] = "Personalizar nombres de compañero en conversaciones de NPC",
	["CO_CHAT_NPCSPEECH_REPLACEMENT_TT"] = "Si el nombre de un compañero está entre paréntesis en la conversación de un NPC se coloreará, y su icono se mostrará dependiendo de los ajustes anteriores.",
	["CO_CHAT_REMOVE_REALM"] = "Quitar reino de los nombres de los jugadores",
	["CO_CHAT_SHOW_OOC"] = "Mostrar el indicador FDP",
	["CO_CHAT_USE"] = "Canales de chat usados",
	["CO_CHAT_USE_ICONS"] = "Mostrar iconos de los jugadores",
	["CO_CHAT_USE_SAY"] = "Canal /decir",
	["CO_CONFIGURATION"] = "Ajustes",
	["CO_CURSOR_DISABLE_OOC"] = "Desactivado mientras se esta OOC",
	["CO_CURSOR_DISABLE_OOC_TT"] = "Deshabilitar modificaciones de cursor cuando tu status de rol está |cnGREEN_FONT_COLOR:Out Of Character|r.",
	["CO_CURSOR_MODIFIER_KEY"] = "Tecla modificar",
	["CO_CURSOR_MODIFIER_KEY_TT"] = "Requiere mantener presionada una tecla modificar mientras se hace clic derecho a un jugador, para prevenir clics accidentales.",
	["CO_CURSOR_RIGHT_CLICK"] = "Clic derecho para abrir el perfil",
	["CO_CURSOR_RIGHT_CLICK_TT"] = [=[Clic derecho en un jugador en el mundo 3D para abrir su perfil, si tiene uno.

|TInterface\Cursor\WorkOrders:25|t Este icono se añadirá al cursor cuando un jugador tiene un perfil y puedes hacer clic derecho sobre él.

|cnGREEN_FONT_COLOR:Nota: Esta característica está deshabilitada durante el combate.|r]=],
	["CO_CURSOR_TITLE"] = "Interacciones del cursor",
	["CO_GENERAL"] = "General",
	["CO_GENERAL_BROADCAST"] = "Usar canal de emisión",
	["CO_GENERAL_BROADCAST_C"] = "Nombre del canal de emisión",
	["CO_GENERAL_BROADCAST_TT"] = "El canal de emisión se usa para una serie de características. Desactivarlo deshabilita características como la ubicación en el mapa, sonidos difundidos a nivel local, el acceso a escondrijos y carteles...",
	["CO_GENERAL_CHANGELOCALE_ALERT"] = [=[¿Quieres volver a cargar la interfaz para cambiar el idioma a %s ahora?

Si no, el idioma será cambiado en la próxima conexión.]=],
	["CO_GENERAL_COM"] = "Comunicación",
	["CO_GENERAL_DEFAULT_COLOR_PICKER"] = "Selector de color por defecto",
	["CO_GENERAL_DEFAULT_COLOR_PICKER_TT"] = "Activar para usar siempre el selector de color por defecto. Útil si estás usando un addon selector de color.",
	["CO_GENERAL_HEAVY"] = "Alerta de perfil sobrecargado",
	["CO_GENERAL_HEAVY_TT"] = "Ser avisado cuando el tamaño del perfil exceda un valor razonable.",
	["CO_GENERAL_LOCALE"] = "Idioma",
	["CO_GENERAL_MISC"] = "Miscelánea",
	["CO_GENERAL_NEW_VERSION"] = "Alerta de actualización",
	["CO_GENERAL_NEW_VERSION_TT"] = "Ser avisado cuando haya una nueva versión disponible.",
	["CO_GENERAL_RESET_CUSTOM_COLORS"] = "Resetear colores personalizados",
	["CO_GENERAL_RESET_CUSTOM_COLORS_TT"] = "Elimina todos los colores personalizados en el selector de color.",
	["CO_GENERAL_RESET_CUSTOM_COLORS_WARNING"] = "¿Seguro que quieres eliminar todos los colores personalizados en el selector de color?",
	["CO_GENERAL_TT_SIZE"] = "Información sobre herramientas del tamaño del texto",
	["CO_GENERAL_UI_ANIMATIONS"] = "Animaciones de la IU",
	["CO_GENERAL_UI_ANIMATIONS_TT"] = "Activar las animaciones de la IU.",
	["CO_GENERAL_UI_SOUNDS"] = "Sonidos de la IU.",
	["CO_GENERAL_UI_SOUNDS_TT"] = "Activar sonidos de la IU (al abrir ventanas, cambiar de pestañas, pulsar botones).",
	["CO_GLANCE_LOCK"] = "Anclar barra",
	["CO_GLANCE_LOCK_TT"] = "Ancla la barra para evitar que sea arrastrada.",
	["CO_GLANCE_MAIN"] = "Barra \"a primera vista\"",
	["CO_GLANCE_PRESET_TRP2"] = "Usar el estilo de posiciones del Total RP 2",
	["CO_GLANCE_PRESET_TRP2_BUTTON"] = "Usar",
	["CO_GLANCE_PRESET_TRP2_HELP"] = "Acceso directo de configuración en el estilo TRP2: a la derecha del marco de objetivo del WoW.",
	["CO_GLANCE_PRESET_TRP3"] = "Usar el estilo de posiciones del Total RP 3",
	["CO_GLANCE_PRESET_TRP3_HELP"] = "Acceso directo a la configuración del estilo TRP3: a la parte inferior del marco de objetivo del TRP3.",
	["CO_GLANCE_RESET_TT"] = "Cambiar la posición a la parte inferior izquierda de la barra del marco de anclaje.",
	["CO_GLANCE_TT_ANCHOR"] = "Punto de anclaje",
	["CO_HIDE_EMPTY_MAP_BUTTON"] = "Ocultar cuando no haya escaneos disponibles",
	["CO_LOCATION"] = "Ajustes de rastreo",
	["CO_LOCATION_ACTIVATE"] = "Habilitar la localización de personaje",
	["CO_LOCATION_ACTIVATE_TT"] = "Habilitar el sistema de localización de personaje te permite buscar a otros usuarios de Total RP en el mapa del mundo, permitiéndote localizarles.",
	["CO_LOCATION_DISABLE_CLASSIC_PVP"] = "Deshabilitar la localización cuando estás marcado para JcJ",
	["CO_LOCATION_DISABLE_CLASSIC_PVP_TT"] = "No vas a poder ser localizado por otros jugadores cuando estás marcado para JcJ. Esta opción es particularmente útil para evadir abusos del sistema de localización para perseguirte.",
	["CO_LOCATION_DISABLE_OOC"] = "Desactivar rastreo en modo FdR",
	["CO_LOCATION_DISABLE_OOC_TT"] = "No aparecerás en la solicitud de localización de otros personajes cuando estés Fuera de Personaje.",
	["CO_LOCATION_DISABLE_WAR_MODE"] = "Deshabilitar ubicación en Modo de Guerra",
	["CO_LOCATION_DISABLE_WAR_MODE_TT"] = [=[No aparecerás en la solicitud de localización de otros personajes cuando hayas activado el Modo Guerra y estés fuera de un |cff69CCF0santuario|r.

Esta opción es útil para evitar abusos del sistema por parte de otros jugadores para rastrearte.]=],
	["CO_LOCATION_SHOW_DIFFERENT_WAR_MODES"] = "Mostrar jugadores en diferente Modo de Guerra",
	["CO_LOCATION_SHOW_DIFFERENT_WAR_MODES_TT"] = "Los jugadores que están en la zona pero tienen un estado diferente del Modo de Guerra aparecerán en el mapa, con menos opacidad y un icono especial en la herramienta.",
	["CO_MAP_BUTTON"] = "Botón de escaneo de mapa",
	["CO_MAP_BUTTON_POS"] = "Anclar el botón de escaneo en el mapa",
	["CO_MINIMAP_BUTTON"] = "Botón del minimapa",
	["CO_MINIMAP_BUTTON_FRAME"] = "Marco de anclaje",
	["CO_MINIMAP_BUTTON_RESET"] = "Restablecer la posición",
	["CO_MINIMAP_BUTTON_RESET_BUTTON"] = "Restablecer",
	["CO_MINIMAP_BUTTON_SHOW_HELP"] = [=[Si estás usando otro addon para mostrar el icono en el minimapa del Total RP 3 (FuBar, Titan, Bazooka) puedes quitar el botón del minimapa.

|cff00ff00Recordatorio : Puedes abrir Total RP 3 usando /trp3 switch main|r]=],
	["CO_MINIMAP_BUTTON_SHOW_TITLE"] = "Mostrar botón en el minimapa",
	["CO_MODULES"] = "Módulos",
	["CO_MODULES_DISABLE"] = "Deshabilitar módulos",
	["CO_MODULES_ENABLE"] = "Habilitar módulo",
	["CO_MODULES_ID"] = "ID del módulo: %s",
	["CO_MODULES_SHOWERROR"] = "Mostrar error",
	["CO_MODULES_STATUS"] = "Estado: %s",
	["CO_MODULES_STATUS_0"] = "Dependencias faltantes",
	["CO_MODULES_STATUS_1"] = "Cargado",
	["CO_MODULES_STATUS_2"] = "Deshabilitado",
	["CO_MODULES_STATUS_3"] = "Se requiere actualización de Total RP 3",
	["CO_MODULES_STATUS_4"] = "Error en la inicialización",
	["CO_MODULES_STATUS_5"] = "Error en el inicio%sPara Total RP 3 build %s mínima.|r",
	["CO_MODULES_TT_DEP"] = "%s-%s (versión %s)|r",
	["CO_MODULES_TT_DEPS"] = "Dependencias",
	["CO_MODULES_TT_ERROR"] = [=[|cffff0000Error:|r
%s]=],
	["CO_MODULES_TT_NONE"] = "No hay dependencias",
	["CO_MODULES_TT_TRP"] = "%sPara Total RP 3 build %s mínima.|r",
	["CO_MODULES_TUTO"] = [=[Un módulo es una característica independiente que puede habilitarse o deshabilitarse.

Posibles estados:
|cff00ff00Cargado:|r El módulo está habilitado y cargado.
|cff999999Deshabilitado:|r El módulo está deshabilitado.
|cffff9900Faltan dependencias:|r Algunas dependencias no se cargaron.
|cffff9900Actualización de TRP necesaria:|r El módulo necesita una versión más reciente de TRP3.
|cffff0000Error en la inicialización o en el inicio:|r La secuencia de carga del módulo ha fallado. ¡Es probable que el módulo crea errores!

|cnGREEN_FONT_COLOR:Al desactivar un módulo, es necesario un reinicio de interfaz de usuario.|r]=],
	["CO_MODULES_VERSION"] = "Versión: %s",
	["CO_MSP"] = "Protocolo Mary Sue",
	["CO_REGISTER"] = "Registro",
	["CO_REGISTER_ABOUT_H1_SIZE"] = "Tamaño del texto del encabezado 1",
	["CO_REGISTER_ABOUT_H1_SIZE_TT"] = "Tamaño del texto entre las etiquetas {h1}. Por defecto: %d",
	["CO_REGISTER_ABOUT_H2_SIZE"] = "Tamaño del texto del encabezado 2",
	["CO_REGISTER_ABOUT_H2_SIZE_TT"] = "Tamaño del texto entre las etiquetas {h2}. Por defecto: %d",
	["CO_REGISTER_ABOUT_H3_SIZE"] = "Tamaño del texto del encabezado 3",
	["CO_REGISTER_ABOUT_H3_SIZE_TT"] = "Tamaño del texto entre las etiquetas {h3}. Por defecto: %d",
	["CO_REGISTER_ABOUT_P_SIZE"] = "Tamaño del texto del párrafo",
	["CO_REGISTER_ABOUT_P_SIZE_TT"] = "Tamaño del texto fuera de las etiquetas de encabezado. Por defecto: %d",
	["CO_REGISTER_ABOUT_SETTINGS"] = "Configuraciones de \"Acerca de\"",
	["CO_REGISTER_AUTO_PURGE"] = "Purgar directorio automáticamente",
	["CO_REGISTER_AUTO_PURGE_0"] = "Deshabilitar purga",
	["CO_REGISTER_AUTO_PURGE_1"] = "Después de %s día(s)",
	["CO_REGISTER_AUTO_PURGE_TT"] = [=[Eliminar automáticamente del directorio los perfiles de personajes con los que no te has cruzado en determinado tiempo. Puedes aplazarlo antes de eliminar.

|cnGREEN_FONT_COLOR:Ten en cuenta que los perfiles que tengan alguna relación con tus personajes no serán eliminados.|r

|cnWARNING_FONT_COLOR:Hay un error en WoW que pierde toda la información guardada al llegar a cierto límite. Recomendamos encarecidamente evitar deshabilitar el sistema de purga.|r]=],
	["CO_SANITIZER"] = "Sanear perfiles entrantes",
	["CO_SANITIZER_TT"] = "Eliminar secuencias de escape en campos de información de herramientas de los perfiles entrantes cuando TRP no lo permite (color, imágenes...).",
	["CO_TARGETFRAME"] = "Marco de objetivo",
	["CO_TARGETFRAME_ICON_SIZE"] = "Tamaño de iconos",
	["CO_TARGETFRAME_USE"] = "Mostrar condiciones",
	["CO_TARGETFRAME_USE_1"] = "Siempre",
	["CO_TARGETFRAME_USE_2"] = "Sólo en ER",
	["CO_TARGETFRAME_USE_3"] = "Nunca (deshabilitado)",
	["CO_TARGETFRAME_USE_TT"] = "Determina en que condiciones se mostrará el marco de objetivo.",
	["CO_TOOLBAR"] = "Barra de herramientas",
	["CO_TOOLBAR_CONTENT"] = "Ajustes de la barra de herramientas",
	["CO_TOOLBAR_CONTENT_CAPE"] = "Botón de capa",
	["CO_TOOLBAR_CONTENT_HELMET"] = "Botón de yelmo",
	["CO_TOOLBAR_CONTENT_RPSTATUS"] = "Estado del personaje (ER/FdR)",
	["CO_TOOLBAR_CONTENT_STATUS"] = "Estado del jugador (AUS/NM)",
	["CO_TOOLBAR_HIDE_TITLE"] = "Ocultar título de la barra de herramientas",
	["CO_TOOLBAR_HIDE_TITLE_HELP"] = "Oculta el título mostrado encima de la barra de herramientas.",
	["CO_TOOLBAR_ICON_SIZE"] = "Tamaño de iconos",
	["CO_TOOLBAR_MAX"] = "Iconos máximos por línea",
	["CO_TOOLBAR_MAX_TT"] = "¡Se establece en 1 si deseas la barra en posición vertical!",
	["CO_TOOLBAR_SHOW_ON_LOGIN"] = "Mostrar barra de herramientas al iniciar sesión",
	["CO_TOOLBAR_SHOW_ON_LOGIN_HELP"] = "Si no quieres que la barra de herramientas se muestre al iniciar sesión, desactiva esta opción.",
	["CO_TOOLTIP"] = "Herramientas",
	["CO_TOOLTIP_ANCHOR"] = "Punto de anclaje",
	["CO_TOOLTIP_ANCHORED"] = "Marco anclado",
	["CO_TOOLTIP_CHARACTER"] = "Herramientas del personaje",
	["CO_TOOLTIP_CLIENT"] = "Mostrar cliente",
	["CO_TOOLTIP_COLOR"] = "Mostrar colores personalizados",
	["CO_TOOLTIP_COMBAT"] = "Ocultar durante el combate",
	["CO_TOOLTIP_COMMON"] = "Ajustes comunes",
	["CO_TOOLTIP_CONTRAST"] = "Aumentar el contraste de color",
	["CO_TOOLTIP_CONTRAST_TT"] = "Habilitar esta opción permitirá a Total RP 3 modificar los colores personalizados para hacer el texto más legible si el color es demasiado oscuro.",
	["CO_TOOLTIP_CROP_TEXT"] = "Trunca textos excesivamente largos",
	["CO_TOOLTIP_CROP_TEXT_TT"] = [=[Limita el número de caracteres que pueden ser expuestos por cada campo en información para prevenir textos excesivamente largos y posibles problemas en el diseño.

|cnGREEN_FONT_COLOR:Detalles de límites:
Nombre: 100 caracteres
Título: 150 caracteres
Raza: 50 caracteres
Clase: 50 caracteres|r]=],
	["CO_TOOLTIP_CURRENT"] = "Mostrar información \"actual\"",
	["CO_TOOLTIP_CURRENT_LINES"] = "Saltos de línea máximos en información \"Actualmente\"",
	["CO_TOOLTIP_CURRENT_SIZE"] = "Longitud máxima de información \"actual\"",
	["CO_TOOLTIP_FT"] = "Mostrar título completo",
	["CO_TOOLTIP_GUILD"] = "Mostrar información de hermandad",
	["CO_TOOLTIP_HEALTH"] = "Mostrar salud",
	["CO_TOOLTIP_HEALTH_BOTH"] = "Número + Porcentaje",
	["CO_TOOLTIP_HEALTH_DISABLED"] = "Desactivado",
	["CO_TOOLTIP_HEALTH_NUMBER"] = "Número",
	["CO_TOOLTIP_HEALTH_PERCENT"] = "Porcentaje",
	["CO_TOOLTIP_HEALTH_TT"] = "Esto sólo se va a mostrar si el objetivo no tiene la vida completa",
	["CO_TOOLTIP_HIDE_IN_INSTANCE"] = "Ocultar en estancias",
	["CO_TOOLTIP_HIDE_ORIGINAL"] = "Ocultar marco original",
	["CO_TOOLTIP_ICONS"] = "Mostrar iconos",
	["CO_TOOLTIP_IN_CHARACTER_ONLY"] = "Ocultar cuando estés Fuera de Personaje",
	["CO_TOOLTIP_MAINSIZE"] = "Tamaño del texto principal",
	["CO_TOOLTIP_NO_FADE_OUT"] = "Ocultar inmediatamente en lugar de desvanecer",
	["CO_TOOLTIP_NOTIF"] = "Mostrar notificaciones",
	["CO_TOOLTIP_NOTIF_TT"] = "La línea de notificaciones es la línea que contiene la versión del cliente, el marcador de descripción no leída y el marcador de \"a primera vista\".",
	["CO_TOOLTIP_OWNER"] = "Mostrar propietario",
	["CO_TOOLTIP_PETS"] = "Herramienta de compañeros",
	["CO_TOOLTIP_PETS_INFO"] = "Mostrar información de compañero",
	["CO_TOOLTIP_PREFERRED_OOC_INDICATOR"] = "Indicador de FDP principal",
	["CO_TOOLTIP_PREFERRED_OOC_INDICATOR_ICON"] = "Icono:",
	["CO_TOOLTIP_PREFERRED_OOC_INDICATOR_TEXT"] = "Texto:",
	["CO_TOOLTIP_PROFILE_ONLY"] = "Utilizar sólo si el objetivo tiene un perfil",
	["CO_TOOLTIP_PRONOUNS"] = "Mostrar pronombres",
	["CO_TOOLTIP_RACE"] = "Mostrar raza, clase y nivel",
	["CO_TOOLTIP_REALM"] = "Mostrar reino",
	["CO_TOOLTIP_RELATION"] = "Mostrar el color de la relación",
	["CO_TOOLTIP_RELATION_TT"] = "Establece el color del borde del personaje según su relación contigo.",
	["CO_TOOLTIP_SPACING"] = "Mostrar espacios",
	["CO_TOOLTIP_SPACING_TT"] = "Coloca espacios entre la información del personaje para diferenciar mejor los apartados.",
	["CO_TOOLTIP_SUBSIZE"] = "Tamaño del texto secundario",
	["CO_TOOLTIP_TARGET"] = "Mostrar objetivo",
	["CO_TOOLTIP_TERSIZE"] = "Tamaño del texto terciario",
	["CO_TOOLTIP_TITLE"] = "Mostrar título",
	["CO_TOOLTIP_USE"] = "Usar herramientas de personajes/compañeros",
	["CO_TOOLTIP_ZONE"] = "Mostrar zona",
	["CO_TOOLTIP_ZONE_TT"] = "Esto sólo se mostrará si el objetivo no está en al misma zona que tú.",
	["CO_UI_RELOAD_WARNING"] = [=[La interfaz necesita ser reiniciada para que se apliquen los cambios.

¿Te gustaría reiniciar la interfaz ahora?]=],
	["CO_WIM"] = "|cffff9900Canales de susurros desactivados.",
	["CO_WIM_TT"] = "Estás usando |cff00ff00WIM|r, el administrador de canales de susurro está desactivado para propósitos de compatibilidad.",
	["COM_LIST"] = "Lista de comandos:",
	["COM_RESET_RESET"] = "¡La posición de los elementos de interfaz han sido restablecidos!",
	["COM_RESET_USAGE"] = "Uso: |cff00ff00/trp3 reset frames|r para restablecer todas las posiciones de los elementos de la interfaz.",
	["COM_STASH_DATA"] = [=[|cffff0000¿Estás seguro de que quieres ir acumulando tu información del Total RP 3?|r

Tus perfiles, los de tus compañeros y configuración se acumulará temporalmente y tu interfaz se cargará sin información, como si hubieras instalado Total RP 3 de nuevo.
|cff00ff00Utiliza el mismo comando de nuevo (|cff999999/trp3 stash|cff00ff00) para restaurar la información.|r]=],
	["COM_SWITCH_USAGE"] = "Uso: |cff00ff00/trp3 switch main|r para mostrar u ocultar la ventana principal o |cff00ff00/trp3 switch toolbar|r para mostrar u ocultar la barra de herramientas.",
	["COPY_DROPDOWN_POPUP_TEXT"] = "Copiar con %1$s. Pegar con %2$s. Este marco se cerrará al copiarse.",
	["COPY_SYSTEM_MESSAGE"] = "Copiado al portapapeles.",
	["CREDITS_DISCORD_LINK_TEXT"] = "Únete a nuestro Discord",
	["CREDITS_THANK_YOU_ROLE_1"] = "Líder de Proyecto",
	["CREDITS_THANK_YOU_ROLE_2"] = "Autor",
	["CREDITS_THANK_YOU_ROLE_3"] = "Desarrollador",
	["CREDITS_THANK_YOU_ROLE_4"] = "Mánager de la comunidad",
	["CREDITS_THANK_YOU_ROLE_5"] = "Mascota",
	["CREDITS_THANK_YOU_SECTION_1"] = "{h1:c}Total RP 3{/h1}",
	["CREDITS_THANK_YOU_SECTION_10"] = "{col:ffffff}Gracias a nuestros miembros activos de la comunidad en Discord:{/col}",
	["CREDITS_THANK_YOU_SECTION_11"] = "{col:ffffff}Gracias a Bor Blasthammer por su ayuda durante las pruebas en BfA.{/col}",
	["CREDITS_THANK_YOU_SECTION_2"] = "{h2}%1$s Creado por{/h2}",
	["CREDITS_THANK_YOU_SECTION_3"] = "{h2}%1$s El Resto del Equipo{/h2}",
	["CREDITS_THANK_YOU_SECTION_4"] = "{h2}%1$s Agradecimientos{/h2}",
	["CREDITS_THANK_YOU_SECTION_5"] = "{col:ffffff}Logo e ícono del minimapa:{/col} %1$s|n{col:ffffff}Sidebar dice icon:{/col} %2$s",
	["CREDITS_THANK_YOU_SECTION_7"] = "{col:ffffff}Gracias a todos nuestros amigos por su apoyo todos estos años:{/col}",
	["CREDITS_THANK_YOU_SECTION_8"] = "{col:ffffff}Por ayudarnos a crear la guild Total RP en el reino Kirin Tor (EU):{/col}",
	["CREDITS_THANK_YOU_SECTION_9"] = "{col:ffffff}Gracias a Horionne por enviarnos el Magazine Gamer Culte Online #14 con un artículo sobre el Total RP.{/col}",
	["CREDITS_VERSION_TEXT"] = "Versión %s",
	["CREDITS_WEBSITE_LINK_TEXT"] = "Página Web",
	["DB_ABOUT"] = "Acerca de Total RP 3",
	["DB_HTML_GOTO"] = "Click para abrir",
	["DB_MORE"] = "Más módulos",
	["DB_NEW"] = "¿Qué hay nuevo?",
	["DB_STATUS"] = "Estado",
	["DB_STATUS_CURRENTLY"] = "Actualmente",
	["DB_STATUS_CURRENTLY_COMMON"] = "Estos estados serán mostrados en la descripción de tu personaje. Mantenlo claro y corto ya que |cnGREEN_FONT_COLOR:por defecto los jugadores con TRP3 solo verán los primeros 140 caracteres.|r",
	["DB_STATUS_CURRENTLY_OOC"] = "Otra información (FdR)",
	["DB_STATUS_ICON_ITEM"] = "%1$s %2$s",
	["DB_STATUS_LC"] = "Idioma de roleo",
	["DB_STATUS_LC_DEFAULT"] = "Por defecto (%1$s)",
	["DB_STATUS_RP"] = "Estado de personaje",
	["DB_STATUS_RP_IC"] = "En rol",
	["DB_STATUS_RP_OOC"] = "Fuera de rol",
	["DB_TUTO_1"] = [=[|cffffff00El estado del personaje|r indica si actualmente estás interpretando a tu personaje.

|cffffff00El estado del jugador|r indica si eres un jugador de rol principiante o un veterano dispuesto a ayudar.

|cff00ff00Esta información se colocará en la descripción de tu personaje.|r]=],
	["DICE_HELP"] = "Tira un dado o varios dados separados por espacios, ejemplo: 1d6, 2d12 3d20 ...",
	["DICE_ROLL"] = "%s tira |cffff9900%sx d%s|r|cffcc6600%s|r y obtiene |cff00ff00%s|r.",
	["DICE_ROLL_T"] = "%s %s tira |cffff9900%sx d%s|r|cffcc6600%s|r y obtiene |cff00ff00%s|r.",
	["DICE_TOTAL"] = "%s Total de |cff00ff00%s|r de la tirada.",
	["DICE_TOTAL_T"] = "%s %s tuvo un total de |cff00ff00%s|r de la tirada.",
	["DTBK_AFK"] = "Total RP 3 - AUS/NM",
	["DTBK_CLOAK"] = "Total RP 3 - Capa",
	["DTBK_HELMET"] = "Total RP 3 - Yelmo",
	["DTBK_LANGUAGES"] = "Total RP 3 - Idiomas",
	["DTBK_RP"] = "Total RP 3 - ER/FdR",
	["GEN_VERSION"] = "Versión: %s (Build %s)",
	["GEN_WELCOME_MESSAGE"] = "¡Gracias por usar Total RP 3 (v %s)! ¡Diviértase!",
	["LANG_CHANGE_CAUSED_REVERT_TO_DEFAULT"] = "El idioma actual ha vuelto al %s por defecto %s porque ya no conoces el idioma %s seleccionado anteriormente.",
	["MAP_BUTTON_NO_SCAN"] = "Rastreo no disponible",
	["MAP_BUTTON_SCANNING"] = "Rastreando",
	["MAP_BUTTON_SUBTITLE"] = "Haz clic para mostrar los rastreos disponibles",
	["MAP_BUTTON_SUBTITLE_80_DISABLED"] = "El escaneo no está disponible debido a los cambios del 8.0",
	["MAP_BUTTON_SUBTITLE_CONNECTING"] = "El escaneado del mapa está configurándose. Por favor, espera.",
	["MAP_BUTTON_SUBTITLE_OFFLINE"] = "El escaneo del mapa no está disponible en estos momentos: %s",
	["MAP_BUTTON_TITLE"] = "Rastrear",
	["MAP_SCAN_CHAR"] = "Rastrear personajes",
	["MAP_SCAN_CHAR_TITLE"] = "Personajes",
	["MATURE_FILTER_EDIT_DICTIONARY"] = "Editar diccionario personalizado",
	["MATURE_FILTER_EDIT_DICTIONARY_ADD_BUTTON"] = "Añadir",
	["MATURE_FILTER_EDIT_DICTIONARY_ADD_TEXT"] = "Añadir nueva palabra al diccionario",
	["MATURE_FILTER_EDIT_DICTIONARY_BUTTON"] = "Editar",
	["MATURE_FILTER_EDIT_DICTIONARY_DELETE_WORD"] = "Eliminar palabra del diccionario personalizado",
	["MATURE_FILTER_EDIT_DICTIONARY_EDIT_WORD"] = "Editar palabra",
	["MATURE_FILTER_EDIT_DICTIONARY_RESET_BUTTON"] = "Resetear",
	["MATURE_FILTER_EDIT_DICTIONARY_RESET_TITLE"] = "Resetear diccionario",
	["MATURE_FILTER_EDIT_DICTIONARY_RESET_WARNING"] = "¿Seguro que quieres resetear el diccionario? Esto vaciará el diccionario y lo llenará con palabras por defecto de tu idioma actual (si está disponible).",
	["MATURE_FILTER_EDIT_DICTIONARY_TITLE"] = "Editor del diccionario personalizado",
	["MATURE_FILTER_EDIT_DICTIONARY_TT"] = "Editar el diccionario personalizado usado para el filtro de perfiles adultos.",
	["MATURE_FILTER_FLAG_PLAYER"] = "Marcar como adulto",
	["MATURE_FILTER_FLAG_PLAYER_OPTION"] = "Marcar como adulto",
	["MATURE_FILTER_FLAG_PLAYER_TEXT"] = [=[Confirma que quieres marcar el perfil de %s como contenido adulto. El contenido de este perfil quedará oculto.

|cffffff00Opcional:|r Indica las palabras ofensivas que encontraste en este perfil (separadas por un espacio) para añadirlas al filtro.]=],
	["MATURE_FILTER_FLAG_PLAYER_TT"] = "Marcar este perfil como contenido adulto. El contenido del perfil quedará oculto.",
	["MATURE_FILTER_OPTION"] = "Filtrar perfiles adultos",
	["MATURE_FILTER_OPTION_TT"] = [=[Marca esta opción para habilitar el filtrado de perfiles adultos. Total RP 3 escaneará nuevos perfiles cuando se reciban a través de palabras clave reportadas como adultas y marcará el perfil como adulto si encuentra dicha palabra.

Un perfil adulto tendrá la información oculta y tendrás que confirmar que deseas ver el perfil la primera vez que lo abras.]=],
	["MATURE_FILTER_STRENGTH"] = "Nivel de filtro adulto",
	["MATURE_FILTER_STRENGTH_TT"] = [=[Ajusta el nivel del filtro adulto.

|cffcccccc1 es bajo (10 palabrotas para marcar), 10 es alto (sólo 1 palabrota es necesaria para marcar).|r]=],
	["MATURE_FILTER_TITLE"] = "Filtro de perfiles adultos",
	["MATURE_FILTER_TOOLTIP_WARNING"] = "Contenido adulto",
	["MATURE_FILTER_TOOLTIP_WARNING_SUBTEXT"] = "Este perfil de personaje contiene contenido adulto. Usa el botón de la barra de acciones para mostrar si realmente deseas...",
	["MATURE_FILTER_WARNING_CONTINUE"] = "Continuar",
	["MATURE_FILTER_WARNING_GO_BACK"] = "Atrás",
	["MATURE_FILTER_WARNING_TEXT"] = [=[Tienes el filtro de contenido adulto de Total RP 3 habilitado.

Este perfil se ha marcado como contenido adulto.

¿Estás seguro de querer ver este perfil?]=],
	["MATURE_FILTER_WARNING_TITLE"] = "Contenido adulto",
	["MM_SHOW_HIDE_MAIN"] = "Mostrar/ocultar marco principal",
	["MM_SHOW_HIDE_MOVE"] = "Mover botón",
	["MM_SHOW_HIDE_SHORTCUT"] = "Mostrar/ocultar barra de herramientas",
	["MO_ADDON_NOT_INSTALLED"] = "El add-on %s no está instalado, integracion personalizada de Total RP 3 deshabilitada.",
	["MO_CHAT_CUSTOMIZATIONS_DESCRIPTION"] = "Añade compatibilidad personalizada para el add-on %s, asi que Total RP 3 cambia los mensajes de chat y los nombres de los jugadores en ese add-on.",
	["MO_TOOLTIP_CUSTOMIZATIONS_DESCRIPTION"] = "Añade compatibilidad personalizada para el add-on %s, asi que tus preferencias de ventana de información se aplicarán sobre las ventanas de Total RP 3.",
	["MORE_MODULES_2"] = [=[{h2:c}Módulos opcionales{/h2}
{h3}Total RP 3: Extended |cffF87431|r{/h3}
|cff9999ffTotal RP 3: Extended|r añade la posibilidad de crear nuevo contenido en WoW: campañas con misiones y diálogos, objetos, documentos (libros, señales, contratos...), ¡y mucho más!
{link*https://www.curseforge.com/wow/addons/total-rp-3-extended*Descargar en CurseForge}

{h3}TRP3 Location Toggle{/h3}
Adds a simple button to the toolbar to toggle on and off the map scan location feature.
{link*https://www.curseforge.com/wow/addons/trp3-location-toggle*Descargar en CurseForge}

{h3}Total RP 3: Unit Frames{/h3}
This module modifies Blizzard player and target frames to use RP name and color, and add a button to open profile.
{col:f2bf1a}{link*https://www.curseforge.com/wow/addons/total-rp-3-unit-frames*Descargar en CurseForge}{/col}]=],
	["NAMEPLATES_CONFIG_CUSTOMIZE_FULL_TITLES"] = "Mostrar títulos completos",
	["NAMEPLATES_CONFIG_CUSTOMIZE_HEALTH_COLORS"] = "Mostrar los colores personalizados de salud",
	["NAMEPLATES_CONFIG_CUSTOMIZE_HEALTH_COLORS_HELP"] = "Si está activo, cambiará el color de la barra de salud por el color personalizado del perfil.",
	["NAMEPLATES_CONFIG_CUSTOMIZE_ICONS"] = "Mostrar íconos",
	["NAMEPLATES_CONFIG_CUSTOMIZE_ICONS_HELP"] = "Si está activo, mostrará los íconos del perfil en la placa de nombre.",
	["NAMEPLATES_CONFIG_CUSTOMIZE_NAME_COLORS"] = "Mostrar los nombres con el color del perfil",
	["NAMEPLATES_CONFIG_CUSTOMIZE_NAME_COLORS_HELP"] = "Si está activo, se cambiará el color de los nombres por el color personalizado del perfil.",
	["NAMEPLATES_CONFIG_CUSTOMIZE_NAMES"] = "Mostrar nombres personalizados",
	["NAMEPLATES_CONFIG_CUSTOMIZE_NAMES_HELP"] = "Si está activo, reemplaza el nombre del personaje en la placa de nombre.",
	["NAMEPLATES_CONFIG_CUSTOMIZE_ROLEPLAY_STATUS"] = "Mostrar el indicador de estado de roleplay",
	["NAMEPLATES_CONFIG_CUSTOMIZE_ROLEPLAY_STATUS_HELP"] = "Si está activo, mostrará el indicador En Personaje o Fuera de Personaje en la placa de nombres.",
	["NAMEPLATES_CONFIG_DISABLE_IN_COMBAT"] = "Deshabilitar las personalizaciones en combate",
	["NAMEPLATES_CONFIG_DISABLE_IN_COMBAT_HELP"] = "Si está activo, se desactivarán los nombres y colores personalizados cuando estás en combate.",
	["NAMEPLATES_CONFIG_DISABLE_OUT_OF_CHARACTER"] = "Deshabilitar las personalizaciones en modo FdP",
	["NAMEPLATES_CONFIG_DISABLE_OUT_OF_CHARACTER_HELP"] = "Si está activo, deshabilita todas las personalizaciones de la placa de nombres cuando estás en modo Fuera de Personaje.",
	["NAMEPLATES_CONFIG_ELEMENT_HEADER"] = "Configuraciones de personalización",
	["NAMEPLATES_CONFIG_ENABLE_CLASS_COLOR_FALLBACK"] = "Usar el color de clase por defecto",
	["NAMEPLATES_CONFIG_ENABLE_CLASS_COLOR_FALLBACK_HELP"] = "Si está activo, habilita el uso de los colores de clase para los nombres y las barras de vida de aquellas unidades que no tengan un color personalizado en sus perfiles.|n|nLas unidades que no tengan un perfil de rol no serán afectadas por esta opción.",
	["NAMEPLATES_CONFIG_ICON_SIZE"] = "Tamaño de ícono",
	["NAMEPLATES_CONFIG_ICON_SIZE_HELP"] = "Configura el tamaño de los íconos mostrados en la placa de nombres si la opción |cnGREEN_FONT_COLOR:Mostrar íconos|r está habilitada.",
	["NAMEPLATES_CONFIG_MENU_TITLE"] = "Placa de nombres",
	["NAMEPLATES_CONFIG_PAGE_TEXT"] = "Configuraciones de placa de nombre",
	["NAMEPLATES_CONFIG_VISIBILITY_HEADER"] = "Configuraciones de visibilidad",
	["NAMEPLATES_MODULE_NAME"] = "Placa de nombres",
	["NEW_VERSION"] = [=[|cff00ff00Hay una nueva versión de Total RP 3 (v %s) disponible.

|cffffff00Recomendamos encarecidamente mantenerlo actualizado.|r

Este mensaje sólo aparecerá una vez por sesión y puede ser deshabilitado en los ajustes (Ajustes generales => Varios).]=],
	["NEW_VERSION_BEHIND"] = "Actualmente estás %s versiones atrasado y te faltan bugs arreglados y nuevas características. Puede que otros jugadores no vean tu perfil correctamente. Por favor, considera actualizar tu add-on.",
	["NEW_VERSION_TITLE"] = "Nueva actualización disponible",
	["NPC_TALK_BUTTON_TT"] = "Abre el marco de diálogos de PNJ el cual permite realizar diálogos y emociones de PNJ.",
	["NPC_TALK_CHANNEL"] = "Canal:",
	["NPC_TALK_COMMAND_HELP"] = "Abre el cuadro de diálogo de PNJ.",
	["NPC_TALK_ERROR_EMPTY_MESSAGE"] = "El mensaje no puede estar vacío.",
	["NPC_TALK_MESSAGE"] = "Mensaje",
	["NPC_TALK_NAME"] = "Nombre de PNJ",
	["NPC_TALK_NAME_TT"] = [=[Puedes usar etiquetas de chat estándar como %t para introducir el nombre de tu objetivo o %f para introducir el nombre de tu foco.

Puedes dejar este campo en blanco para crear emotes sin el nombre de un PNJ al principio.]=],
	["NPC_TALK_SAY_PATTERN"] = "dice:",
	["NPC_TALK_SEND"] = "Enviar",
	["NPC_TALK_TITLE"] = "Diálogos de PNJ",
	["NPC_TALK_WHISPER_PATTERN"] = "susurra:",
	["NPC_TALK_YELL_PATTERN"] = "grita:",
	["OPTION_DISABLED_TOAST"] = "Opciones deshabilitadas",
	["OPTION_ENABLED_TOAST"] = "Opción habilitada",
	["PATTERN_ERROR"] = "Error en el patrón",
	["PATTERN_ERROR_TAG"] = "Error en patrón : etiqueta de texto sin cerrar.",
	["PR_CO_BATTLE"] = "Compañero",
	["PR_CO_COUNT"] = "%s mascota/montura ligada a este perfil.",
	["PR_CO_EMPTY"] = "Sin compañeros",
	["PR_CO_MASTERS"] = "Dueños",
	["PR_CO_MOUNT"] = "Montura",
	["PR_CO_NEW_PROFILE"] = "Nuevo perfil de compañero",
	["PR_CO_PET"] = "Mascota",
	["PR_CO_PROFILE_DETAIL"] = "Este perfil está actualmente vinculado a",
	["PR_CO_PROFILE_HELP"] = [=[Un perfil contiene toda la información acerca de una |cffffff00"mascota"|r como un |cff00ff00personaje de rol|r.

Un perfil de compañero puede estar vinculado a:
-Los compañeros |cffff9900(sólo si se ha cambiado el nombre)|r
-Las mascotas del cazador
-Los demonios del brujo
-Los elementales del mago
-Los no-muertos del caballero de la muerte |cffff9900(Ver abajo)|r

Al igual que los perfiles de los personajes, un |cff00ff00perfil de compañero|r puede estar vinculado a |cffffff00várias mascotas|r, y una |cffffff00mascota|r puede cambiar fácilmente de un perfil a otro.

|cffff9900No-muertos:|r como los no-muertos obtienen un nombre diferente cada vez que son invocados, se tendrá que vincular el perfil para todos los nombres posibles del no-muerto.]=],
	["PR_CO_PROFILE_HELP2"] = [=[Haz clic aquí para crear un nuevo perfil de compañero.

|cff00ff00Para vincular un perfil con una mascota, invoca a la mascota, selecciónala y utiliza el marco de destino para vincularlo al perfil existente (o crear uno nuevo):|r]=],
	["PR_CO_PROFILEMANAGER_DELETE_WARNING"] = [=[¿Estás seguro de que deseas eliminar el perfil del compañero %s?
¡Esta acción no se podrá deshacer y toda la información del perfil TRP3 será destruida!]=],
	["PR_CO_PROFILEMANAGER_DUPP_POPUP"] = [=[Por favor, introduce un nombre para el nuevo perfil.
El nombre no puede estar vacío.

El duplicado no cambiará tus mascotas/monturas vinculadas a %s.]=],
	["PR_CO_PROFILEMANAGER_EDIT_POPUP"] = [=[Por favor, introduce un nuevo nombre para este perfil.
El nombre no puede estar vacío.

Cambiar el nombre no cambiará ningún vínculo entre este perfil y tus mascotas/monturas.]=],
	["PR_CO_PROFILEMANAGER_TITLE"] = "Perfiles de compañeros",
	["PR_CO_UNUSED_PROFILE"] = "Este perfil no está actualmente vinculado a ninguna mascota o montura.",
	["PR_CO_WARNING_RENAME"] = [=[|cffff0000Advertencia;|r se recomienda encarecidamente renombrar a la mascota antes de vincularla a un perfil.|r

¿Quieres enlazarla de todas formas?]=],
	["PR_CREATE_PROFILE"] = "Crear perfil",
	["PR_DEFAULT_PROFILE_NAME"] = "Perfil por defecto",
	["PR_DEFAULT_PROFILE_WARNING"] = "Crea un nuevo perfil o enlaza con uno ya existente en Perfiles para editar la información de tu personaje.",
	["PR_DELETE_PROFILE"] = "Eliminar perfil",
	["PR_DUPLICATE_PROFILE"] = "Duplicar perfil",
	["PR_EXPORT_IMPORT_HELP"] = [=[Puedes exportar e importar perfiles usando las opciones en el menú desplegable.

Usa la opción |cffffff00Exportar perfil|r para generar un texto conteniendo la información serializada del perfil. Puedes copiar el texto usando Control+C (o Comando+C en un Mac) y pegarlo en otra parte como seguridad. cffff0000Por favor, ten en cuenta que algunas herramientas de texto avanzadas como Microsoft Word reformateará algunos caracteres especiales como comillas, alterando la información. Utiliza herramientas de texto simples como Notepad.|r)

Usa la opción |cffffff00Importar perfil|r para pegar la información de una exportación previa dentro de un perfil existente. La información existente será reemplazada por las que pegues. No puedes importar información directamente de tu perfil seleccionado.]=],
	["PR_EXPORT_IMPORT_TITLE"] = "Exportar/importar perfil",
	["PR_EXPORT_NAME"] = "Serie para el perfil %s (tamaño %0.2f kB)",
	["PR_EXPORT_PROFILE"] = "Exportar perfil",
	["PR_EXPORT_TOO_LARGE"] = [=[El perfil es demasiado grande y no puede ser exportado.

Tamaño del perfil: %0.2f kB
Máx.: 20 kB]=],
	["PR_EXPORT_WARNING_MAC"] = [=[Algunas herramientas de edición de texto avanzada como Text Edit o Discord formatearán caracteres especiales como citas, alterando el contenido de los datos.

Si planeas copiar el texto de abajo en un documento, usa herramientas de edición más sencillas que no cambien caracteres automáticamente (en Text Edit ve a "Formato > Convertir en texto normal" antes de pegar)]=],
	["PR_EXPORT_WARNING_TITLE"] = "Atención:",
	["PR_EXPORT_WARNING_WINDOWS"] = [=[Ten en cuenta que algunas herramientas de edición de texto avanzadas como Microsoft Word o Discord reformarán caracteres especiales como citas, alterando el contenido de la información.

Si planeas copiar el texto de abajo en un documento, usa herramientas de edición más sencillas que no cambien caracteres automáticamente, como Notepad.]=],
	["PR_IMPORT"] = "Importar",
	["PR_IMPORT_CHAR_TAB"] = "Importar personajes",
	["PR_IMPORT_EMPTY"] = "Sin perfiles importables",
	["PR_IMPORT_IMPORT_ALL"] = "Importar todo",
	["PR_IMPORT_PETS_TAB"] = "Importar compañeros",
	["PR_IMPORT_PROFILE"] = "Importar perfil",
	["PR_IMPORT_PROFILE_TT"] = "Pegar aquí serie de perfil",
	["PR_IMPORT_WILL_BE_IMPORTED"] = "Se importarán",
	["PR_PROFILE"] = "Perfil",
	["PR_PROFILE_CREATED"] = "Perfil %s creado.",
	["PR_PROFILE_DELETED"] = "Perfil %s eliminado.",
	["PR_PROFILE_DETAIL"] = "Este perfil actualmente no está vinculado a ningún personaje de WoW.",
	["PR_PROFILE_HELP"] = [=[Un perfil contiene toda la información de un |cffffff00"personaje"|r como un |cff00ff00personaje de rol|r.

Un |cffffff00"personaje del WoW"|r sólo puede ser vinculado a un solo perfil a la vez, pero puedes cambiar de uno a otro en cualquier momento.

¡También puedes vincular varios |cffffff00"personajes"|r al mismo |cff00ff00perfil|r!]=],
	["PR_PROFILE_LOADED"] = "El perfil %s ha sido cargado.",
	["PR_PROFILE_MANAGEMENT_TITLE"] = "Administración de perfiles",
	["PR_PROFILEMANAGER_ACTIONS"] = "Acciones",
	["PR_PROFILEMANAGER_ALREADY_IN_USE"] = "El nombre del perfil %s no está disponible.",
	["PR_PROFILEMANAGER_COUNT"] = "%s personaje vinculado a este perfil.",
	["PR_PROFILEMANAGER_CREATE_POPUP"] = [=[Por favor, introduce un nombre para el nuevo perfil.
El nombre no puede estar vacío.]=],
	["PR_PROFILEMANAGER_CURRENT"] = "Perfil actual",
	["PR_PROFILEMANAGER_DELETE_WARNING"] = [=[¿Seguro que deseas eliminar el perfil %s?
¡Esta acción no se podrá deshacer y toda la información del perfil TRP3 (información del personaje, inventario, registro de misiones, estados aplicados...) será destruida!]=],
	["PR_PROFILEMANAGER_DUPP_POPUP"] = [=[Por favor introduce el nombre para el nuevo perfil.
El nombre no puede mostrarse vacío.

Este duplicado no cambiará las vinculaciones del personaje a %s.]=],
	["PR_PROFILEMANAGER_EDIT_POPUP"] = [=[Por favor, introduce un nuevo nombre para el perfil %s.
El nombre no puede mostrarse vacío.

Cambiar el nombre no afectará al vinculo entre este perfil y tus personajes.]=],
	["PR_PROFILEMANAGER_EMPTY"] = "No se ha encontrado ningún perfil",
	["PR_PROFILEMANAGER_IMPORT_WARNING"] = "¿Reemplazar todo el contenido del perfil %s con la información importada?",
	["PR_PROFILEMANAGER_IMPORT_WARNING_2"] = [=[Aviso: la serie de este perfil se ha hecho de una versión antigua de TRP3.
Puede causar incompatibilidades.

¿Deseas reemplazar todo el contenido del perfil %s con la información importada?]=],
	["PR_PROFILEMANAGER_RENAME"] = "Renombrar perfil",
	["PR_PROFILEMANAGER_SEARCH_PROFILE"] = "Buscar perfil",
	["PR_PROFILEMANAGER_SWITCH"] = "Seleccionar perfil",
	["PR_PROFILEMANAGER_TITLE"] = "Perfiles de personaje",
	["PR_PROFILES"] = "Perfiles",
	["PR_SLASH_EXAMPLE"] = "|cffffff00Uso del comando:|r |cffcccccc/perfil trp3 profile Millidan Iraspuma|r |cffffff00to cambiar al perfil de Millidan Iraspuma.|r",
	["PR_SLASH_NOT_FOUND"] = "|cffff0000No se pudo encontrar ningún perfil llamado|r |cffffff00%s|r|cffff0000.|r",
	["PR_SLASH_OPEN_ABORTING"] = "|cffffff00Petición de perfil abortada.|r",
	["PR_SLASH_OPEN_EXAMPLE"] = "|cffffff00Uso del comando:|r |cffcccccc/trp3 open|r |cffffff00para abrir el perfil de tu objetivo o |cffcccccc/trp3 open CharacterName-RealmName|r |cffffff00para abrir el perfil de ese personaje.|r",
	["PR_SLASH_OPEN_HELP"] = "Abrir el perfil de un personaje usando su nombre en el juego, o el perfil de tu objetivo si no se introduce ningún nombre.",
	["PR_SLASH_OPEN_WAITING"] = "|cffffff00Solicitando perfil, por favor espera...|r",
	["PR_SLASH_SWITCH_HELP"] = "Cambiar a otro perfil usando su nombre.",
	["PR_UNUSED_PROFILE"] = "Este perfil actualmente no está vinculado a ningún personaje de WoW.",
	["REG_COMPANION"] = "Compañero",
	["REG_COMPANION_BIND_TO_PET"] = "Mascota",
	["REG_COMPANION_BOUND_TO"] = "Vinculado a ...",
	["REG_COMPANION_BOUND_TO_TARGET"] = "Objetivo",
	["REG_COMPANION_BOUNDS"] = "Vínculos",
	["REG_COMPANION_BROWSER_BATTLE"] = "Buscador de compañeros",
	["REG_COMPANION_BROWSER_MOUNT"] = "Buscador de monturas",
	["REG_COMPANION_INFO"] = "Información",
	["REG_COMPANION_LINKED"] = "El compañero %s ahora está ligado al perfil %s.",
	["REG_COMPANION_LINKED_NO"] = "El compañero %s ya no está ligado a ningún perfil.",
	["REG_COMPANION_NAME"] = "Nombre",
	["REG_COMPANION_NAME_COLOR"] = "Color del nombre",
	["REG_COMPANION_PAGE_TUTO_C_1"] = "Consultar",
	["REG_COMPANION_PAGE_TUTO_E_1"] = [=[Esta es la |cff00ff00información principal del compañero|r.

Toda esta información aparecerá en la |cffff9900descripción de compañero|r.]=],
	["REG_COMPANION_PAGE_TUTO_E_2"] = [=[Esta es la |cff00ff00descripción del compañero|r.

No se limita a la |cffff9900descripción física|r. Siéntete libre de indicar parte de su |cffff9900trasfondo|r o detalles de su |cffff9900carácter|r.

Hay muchas maneras de personalizar la descripción.
Puedes elegir el |cffffff00fondo del texto|r para la descripción. También puedes utilizar las herramientas de formato para acceder a varios parámetros de diseño como el |cffffff00tamaño del texto, color y posicionamiento|r.
Esta herramienta también permite insertar |cffffff00imágenes, iconos o enlaces externos de sitios web|r.]=],
	["REG_COMPANION_PROFILES"] = "Perfiles de compañeros",
	["REG_COMPANION_TARGET_NO"] = "To objetivo no es una mascota, necrófago, elemental de mago o compañero renombrado válido.",
	["REG_COMPANION_TF_BOUND_TO"] = "Seleccionar perfil",
	["REG_COMPANION_TF_CREATE"] = "Crear nuevo perfil",
	["REG_COMPANION_TF_NO"] = "No hay perfil",
	["REG_COMPANION_TF_OPEN"] = "Abrir página",
	["REG_COMPANION_TF_OWNER"] = "Dueño: %s",
	["REG_COMPANION_TF_PROFILE"] = "Perfil de compañero",
	["REG_COMPANION_TF_PROFILE_MOUNT"] = "Perfil de montura",
	["REG_COMPANION_TF_UNBOUND"] = "Desvincular del perfil",
	["REG_COMPANION_TITLE"] = "Título",
	["REG_COMPANION_UNBOUND"] = "Desvincular de...",
	["REG_COMPANIONS"] = "Compañeros",
	["REG_DELETE_WARNING"] = "¿Seguro que quieres eliminar el perfil %s?",
	["REG_IGNORE_TOAST"] = "Personaje ignorado",
	["REG_LIST_ACTIONS_MASS"] = "Acción sobre los %s perfiles seleccionados.",
	["REG_LIST_ACTIONS_MASS_IGNORE"] = "Ignorar perfiles",
	["REG_LIST_ACTIONS_MASS_IGNORE_C"] = [=[Esta acción añadirá al |cff00ff00%s personaje|r a la lista de ignorados.

Opcionalmente, puede rellenar la razón de ser ignorado abajo. Esta nota es personal, servirá como recordatorio.]=],
	["REG_LIST_ACTIONS_MASS_REMOVE"] = "Eliminar perfiles",
	["REG_LIST_ACTIONS_MASS_REMOVE_C"] = "Esta acción eliminará los |cff00ff00%s perfiles seleccionados|r.",
	["REG_LIST_ACTIONS_PURGE"] = "Purgar registro",
	["REG_LIST_ACTIONS_PURGE_ALL"] = "Eliminar todos los perfiles",
	["REG_LIST_ACTIONS_PURGE_ALL_C"] = [=[Esta purga eliminará todos los perfiles vinculados desde el directorio.

|cff00ff00%s personajes|r]=],
	["REG_LIST_ACTIONS_PURGE_ALL_COMP_C"] = [=[Esta purga eliminará todos los compañeros del directorio.

|cff00ff00%s compañeros|r]=],
	["REG_LIST_ACTIONS_PURGE_COUNT"] = "%s perfiles serán eliminados.",
	["REG_LIST_ACTIONS_PURGE_EMPTY"] = "No hay perfiles que purgar.",
	["REG_LIST_ACTIONS_PURGE_IGNORE"] = "Perfiles de personajes ignorados.",
	["REG_LIST_ACTIONS_PURGE_IGNORE_C"] = [=[Esta purga eliminará a todos los perfiles vinculados a un personaje de WoW ignorado.

|cff00ff00%s|r]=],
	["REG_LIST_ACTIONS_PURGE_TIME"] = "Perfiles no vistos desde hace 1 mes",
	["REG_LIST_ACTIONS_PURGE_TIME_C"] = [=[Esta purga eliminará a todos los personajes no vistos desde hace un mes.

|cff00ff00%s|r]=],
	["REG_LIST_ACTIONS_PURGE_UNLINKED"] = "Perfiles no vinculados a un personaje",
	["REG_LIST_ACTIONS_PURGE_UNLINKED_C"] = [=[Esta purga eliminará todos los perfiles no vinculados a un personaje de WoW.

|cff00ff00%s|r]=],
	["REG_LIST_ADDON"] = "Tipo de perfil",
	["REG_LIST_CHAR_EMPTY"] = "Sin personajes",
	["REG_LIST_CHAR_EMPTY2"] = "Ningún personaje encaja con tu selección",
	["REG_LIST_CHAR_FILTER"] = "Personajes: %s / %s",
	["REG_LIST_CHAR_IGNORED"] = "Ignorado",
	["REG_LIST_CHAR_NAME_COPY"] = "Copiar nombre de personaje",
	["REG_LIST_CHAR_SEL"] = "Seleccionar personaje",
	["REG_LIST_CHAR_TITLE"] = "Personajes",
	["REG_LIST_CHAR_TT"] = "Click para mostrar página",
	["REG_LIST_CHAR_TT_CHAR"] = "Personaje(s) de WoW ligado(s):",
	["REG_LIST_CHAR_TT_CHAR_NO"] = "No está vinculado a ningún personaje",
	["REG_LIST_CHAR_TT_DATE"] = [=[Última vez que fue visto: |cff00ff00%s|r
Último lugar donde fue visto: |cff00ff00%s|r]=],
	["REG_LIST_CHAR_TT_GLANCE"] = "A primera vista",
	["REG_LIST_CHAR_TT_IGNORE"] = "Personaje(s) ignorado(s)",
	["REG_LIST_CHAR_TT_RELATION"] = [=[Relación:
|cff00ff00%s|r]=],
	["REG_LIST_FILTERS"] = "Filtros",
	["REG_LIST_FILTERS_APPLY"] = "Aplicar filtros",
	["REG_LIST_FILTERS_CLEAR"] = "Limpiar filtros",
	["REG_LIST_FLAGS"] = "Banderas",
	["REG_LIST_GUILD"] = "Hermandad",
	["REG_LIST_IGNORE_EMPTY"] = "Personaje no ignorado",
	["REG_LIST_IGNORE_TITLE"] = "Ignorados",
	["REG_LIST_IGNORE_TT"] = [=[Razón:
|cff00ff00%s

|cffffff00Click para eliminar de la lista de ignorados]=],
	["REG_LIST_NAME"] = "Nombre del personaje",
	["REG_LIST_NOTESONLY"] = "Solo hay notas",
	["REG_LIST_NOTIF_ADD"] = "Nuevo perfil descubierto: |cff00ff00%s",
	["REG_LIST_NOTIF_ADD_CONFIG"] = "Nuevo perfil descubierto",
	["REG_LIST_NOTIF_ADD_NOT"] = "Este perfil ya no existe.",
	["REG_LIST_PET_MASTER"] = "Nombre del dueño",
	["REG_LIST_PET_NAME"] = "Nombre del compañero",
	["REG_LIST_PET_TYPE"] = "Tipo de compañero",
	["REG_LIST_PETS_EMPTY"] = "No hay compañero",
	["REG_LIST_PETS_EMPTY2"] = "Ningún compañero encaja con tu selección",
	["REG_LIST_PETS_FILTER"] = "Compañeros: %s / %s",
	["REG_LIST_PETS_TITLE"] = "Compañeros",
	["REG_LIST_PETS_TOOLTIP"] = "Se ha visto en",
	["REG_LIST_PETS_TOOLTIP2"] = "Se ha visto con",
	["REG_LIST_REALMONLY"] = "Sólo en este reino",
	["REG_LOCATION_DIFFERENT_WAR_MODE"] = "Modo de Guerra distinto",
	["REG_MSP_ALERT"] = [=[|cffff0000ADVERTENCIA

No se puede tener más de un addon utilizando el Protocolo Mary Sue, ya que podrían entrar en conflicto.|r

Actualmente cargado: |cff00ff00%s

|cffff9900Por lo tanto, se desactivará el apoyo PMS para el Total RP3|r

Si no quieres que el TRP3 sea tu PMS y no quieres ver esta alerta de nuevo, puedes desactivarlo en el módulo Protocolo Mary Sue en ajustes de Total RP3 en -> Estado del módulo.]=],
	["REG_NOTES_PROFILE"] = "Notas",
	["REG_NOTES_PROFILE_TT"] = "Abre la ventana de notas para el personaje objetivo.",
	["REG_PLAYER"] = "Personaje",
	["REG_PLAYER_ABOUT"] = "Acerca de",
	["REG_PLAYER_ABOUT_ADD_FRAME"] = "Añadir un marco",
	["REG_PLAYER_ABOUT_EMPTY"] = "Sin descripción",
	["REG_PLAYER_ABOUT_HEADER"] = "Etiqueta del título",
	["REG_PLAYER_ABOUT_MUSIC_LISTEN"] = "Tocar tema",
	["REG_PLAYER_ABOUT_MUSIC_REMOVE"] = "Deseleccionar tema",
	["REG_PLAYER_ABOUT_MUSIC_SELECT"] = "Seleccionar tema",
	["REG_PLAYER_ABOUT_MUSIC_STOP"] = "Parar tema",
	["REG_PLAYER_ABOUT_MUSIC_THEME"] = "Tema musical del personaje",
	["REG_PLAYER_ABOUT_NOMUSIC"] = "|cffff9900Sin tema|r",
	["REG_PLAYER_ABOUT_P"] = "Etiqueta del parágrafo",
	["REG_PLAYER_ABOUT_REMOVE_FRAME"] = "Eliminar este marco",
	["REG_PLAYER_ABOUT_SOME"] = "Escribir texto aquí...",
	["REG_PLAYER_ABOUT_T1_YOURTEXT"] = "Tu texto aquí",
	["REG_PLAYER_ABOUT_TAGS"] = "Herramientas de formato",
	["REG_PLAYER_ABOUT_UNMUSIC"] = "|cffff9900Tema desconocido|r",
	["REG_PLAYER_ABOUTS"] = "Acerca de %s",
	["REG_PLAYER_ADD_NEW"] = "Crear nuevo",
	["REG_PLAYER_AGE"] = "Edad",
	["REG_PLAYER_AGE_TT"] = [=[Aquí puedes indicar la edad de tu personaje.

Puedes hacerlo de distintas maneras:|c0000ff00
- Usa años,
- O un adjetivo (joven, maduro, adulto, venerable, etc.).]=],
	["REG_PLAYER_ALERT_HEAVY_SMALL"] = [=[|cnWARNING_FONT_COLOR:El tamaño total de tu perfil es demasiado extenso.|r
Debes reducirlo.]=],
	["REG_PLAYER_BIRTHPLACE"] = "Lugar de nacimiento",
	["REG_PLAYER_BIRTHPLACE_TT"] = [=[Aquí puedes indicar el lugar de nacimiento tu personaje. Puede ser una región, zona o incluso un continente. Tú eres quien decide cuán preciso quieres que sea.

|c00ffff00Puedes usar el botón de la derecha para seleccionar tu ubicación actual como lugar de nacimiento.]=],
	["REG_PLAYER_CARACT"] = "Características",
	["REG_PLAYER_CHANGE_CONFIRM"] = [=[Puede que tengas algunos cambios sin guardar.
¿Deseas cambiar la página de todos modos?
|cffff9900Cualquier cambio se perderá.]=],
	["REG_PLAYER_CHARACTERISTICS"] = "Características",
	["REG_PLAYER_CLASS"] = "Clase",
	["REG_PLAYER_CLASS_TT"] = [=[Esta es la clase por defecto de tu personaje.

|cff00ff00Por ejemplo :|r
Caballero, pirotécnico, nigromante, arcanista...]=],
	["REG_PLAYER_COLOR_ALWAYS_DEFAULT_TT"] = [=[|cffffff00Clic:|r Selecciona un color
|cffffff00Clic derecho:|r Descarta un color]=],
	["REG_PLAYER_COLOR_CLASS"] = "Color de clase",
	["REG_PLAYER_COLOR_CLASS_TT"] = [=[Esto determina el color en que se visualizará la clase.
]=],
	["REG_PLAYER_COLOR_TT_SELECT"] = "Seleccionar color",
	["REG_PLAYER_COLOR_TT_DISCARD"] = "Descartar color",
	["REG_PLAYER_COLOR_TT_DEFAULTPICKER"] = "Usar el selector de color por defecto",
	["REG_PLAYER_EDIT_MUSIC_THEME"] = "Tema musical",
	["REG_PLAYER_EYE"] = "Color de ojos",
	["REG_PLAYER_EYE_TT"] = [=[Aquí puedes indicar el color de ojos de tu personaje.

Ten en cuenta que, aunque tu rostro esté constantemente oculto, vale la pena mencionarlo, por si acaso.]=],
	["REG_PLAYER_FIRSTNAME"] = "Nombre",
	["REG_PLAYER_FIRSTNAME_TT"] = [=[Este es el nombre de tu personaje. Este es un campo obligatorio a rellenar, por lo que si no se especifica un nombre se usará el nombre por defecto (|cffffff00%s|r).

¡Puedes utilizar un |c0000ff00apodo|r!]=],
	["REG_PLAYER_FULLTITLE"] = "Título completo",
	["REG_PLAYER_FULLTITLE_TT"] = [=[Aquí puedes escribir el título completo de tu personaje. Puede ser una versión más larga del título u otro título completo.

Sin embargo, es posible que quieras evitar repeticiones, en caso de que no haya información adicional que mencionar.]=],
	["REG_PLAYER_GLANCE"] = "A primera vista",
	["REG_PLAYER_GLANCE_BAR_DELETED"] = "Grupo prestablecido |cffff9900%s|r eliminado.",
	["REG_PLAYER_GLANCE_BAR_EMPTY"] = "El nombre del predeterminado no puede estar vacío.",
	["REG_PLAYER_GLANCE_BAR_LOAD"] = "Grupo restablecido",
	["REG_PLAYER_GLANCE_BAR_LOAD_SAVE"] = "Grupo predeterminado",
	["REG_PLAYER_GLANCE_BAR_NAME"] = [=[Por favor introduce el nombre del predeterminado.

|cff00ff00Nota: Si el nombre ya está siendo usado por otro grupo, será remplazado por este grupo. ]=],
	["REG_PLAYER_GLANCE_BAR_SAVE"] = "Guardar grupo como predeterminado.",
	["REG_PLAYER_GLANCE_BAR_SAVED"] = "Grupo predeterminado |cff00ff00%s|r ha sido creado",
	["REG_PLAYER_GLANCE_BAR_TARGET"] = "\"A primera vista\" predeterminado",
	["REG_PLAYER_GLANCE_CONFIG"] = [=[|cnGREEN_FONT_COLOR:"A primera vista"|r es una serie de ranuras que puedes usar para añadir información importante sobre este personaje.]=],
	["REG_PLAYER_GLANCE_CONFIG_EDIT"] = "Configurar ranura",
	["REG_PLAYER_GLANCE_CONFIG_TOGGLE"] = "Activar/desactivar ranura",
	["REG_PLAYER_GLANCE_CONFIG_PRESETS"] = "Ranuras prestablecidas",
	["REG_PLAYER_GLANCE_CONFIG_REORDER"] = "Reordenar ranuras",
	["REG_PLAYER_GLANCE_EDITOR"] = "Editor de A primera vista : Ranura %s",
	["REG_PLAYER_GLANCE_MENU_COPY"] = "Copiar ranura",
	["REG_PLAYER_GLANCE_MENU_PASTE"] = "Pegar ranura: %s",
	["REG_PLAYER_GLANCE_PRESET"] = "Cargar",
	["REG_PLAYER_GLANCE_PRESET_ADD"] = "Creado prestablecido |cff00ff00%s|r.",
	["REG_PLAYER_GLANCE_PRESET_ALERT1"] = "Por favor, introduce una categoría y un nombre",
	["REG_PLAYER_GLANCE_PRESET_CATEGORY"] = "Categoría prestablecida",
	["REG_PLAYER_GLANCE_PRESET_CREATE"] = "Crear prestablecido",
	["REG_PLAYER_GLANCE_PRESET_GET_CAT"] = [=[%s

]=],
	["REG_PLAYER_GLANCE_PRESET_NAME"] = "Nombre",
	["REG_PLAYER_GLANCE_PRESET_REMOVE"] = "Eliminar prestablecido |cff00ff00%s|r.",
	["REG_PLAYER_GLANCE_PRESET_SAVE"] = "Guardar información como prestablecida",
	["REG_PLAYER_GLANCE_PRESET_SAVE_SMALL"] = "Guardar como prestablecido",
	["REG_PLAYER_GLANCE_PRESET_SELECT"] = "Seleccionar prestablecido",
	["REG_PLAYER_GLANCE_TITLE"] = "Nombre de atributo",
	["REG_PLAYER_GLANCE_UNUSED"] = "Ranura no utilizada",
	["REG_PLAYER_GLANCE_USE"] = "Activar esta ranura",
	["REG_PLAYER_HEIGHT"] = "Altura",
	["REG_PLAYER_HEIGHT_TT"] = [=[Esta es la altura de tu personaje.
Tienes varias formas de hacerlo:|c0000ff00
- Numérico: 170 cm, 6'5" ...
- Cualificativo: Alto, bajo ...]=],
	["REG_PLAYER_HERE"] = "Seleccionar posición",
	["REG_PLAYER_HERE_HOME_PRE_TT"] = [=[Actual posición de la residencia:
|cff00ff00%s|r.]=],
	["REG_PLAYER_HERE_TT"] = "|cffffff00Click|r: Seleccionar tu posición actual",
	["REG_PLAYER_HERE_HOME_TT_CURRENT"] = "Usar la posición actual como tu residencia",
	["REG_PLAYER_HERE_HOME_TT_DISCARD"] = "Elimina la posición de la residencia",
	["REG_PLAYER_HISTORY"] = "Historia",
	["REG_PLAYER_ICON"] = "Icono del personaje",
	["REG_PLAYER_ICON_TT"] = "Selecciona una representación gráfica para tu personaje.",
	["REG_PLAYER_IGNORE"] = "Ignorar personajes vinculados (%s)",
	["REG_PLAYER_IGNORE_WARNING"] = [=[¿Quieres ignorar a estos personajes?

|cffff9900%s

|rOpcionalmente puedes escribir la razón a continuación. Esta nota personal servirá como recordatorio.]=],
	["REG_PLAYER_LASTNAME"] = "Apellido",
	["REG_PLAYER_LASTNAME_TT"] = "Es el apellido de tu personaje.",
	["REG_PLAYER_LEFTTRAIT"] = "Atributo izquierdo",
	["REG_PLAYER_MISC_ADD"] = "Añadir campo adicional",
	["REG_PLAYER_MISC_PRESET_PRONOUNS"] = "Pronombres",
	["REG_PLAYER_MORE_INFO"] = "Información adicional",
	["REG_PLAYER_MSP_HOUSE"] = "Nombre de la Casa",
	["REG_PLAYER_MSP_MOTTO"] = "Lema",
	["REG_PLAYER_MSP_NICK"] = "Apodo",
	["REG_PLAYER_NAMESTITLES"] = "Nombre y títulos",
	["REG_PLAYER_NO_CHAR"] = "Sin características",
	["REG_PLAYER_NOTES"] = "Notas",
	["REG_PLAYER_NOTES_ACCOUNT"] = "Notas de cuenta",
	["REG_PLAYER_NOTES_ACCOUNT_HELP"] = "Estas notas privadas están ligadas a tu cuenta y se compartirán con todos tus perfiles.",
	["REG_PLAYER_NOTES_PROFILE"] = "Notas de %s",
	["REG_PLAYER_NOTES_PROFILE_HELP"] = "Estas notas privadas están ligadas a tu perfil actual y cambiarán según el perfil que tengas activado.",
	["REG_PLAYER_NOTES_PROFILE_NONAME"] = "Notas del perfil",
	["REG_PLAYER_PEEK"] = "Varios",
	["REG_PLAYER_PHYSICAL"] = "Descripción física",
	["REG_PLAYER_PSYCHO"] = "Rasgos de personalidad",
	["REG_PLAYER_PSYCHO_ASCETIC"] = "Asceta",
	["REG_PLAYER_PSYCHO_ADD"] = "Añadir un rasgo de personalidad",
	["REG_PLAYER_PSYCHO_ATTIBUTENAME_TT"] = "Nombre del atributo",
	["REG_PLAYER_PSYCHO_BONVIVANT"] = "Vividor",
	["REG_PLAYER_PSYCHO_CHAOTIC"] = "Caótico",
	["REG_PLAYER_PSYCHO_CHASTE"] = "Casto",
	["REG_PLAYER_PSYCHO_PARAGON"] = "Ejemplar",
	["REG_PLAYER_PSYCHO_SPINELESS"] = "Cobarde",
	["REG_PLAYER_PSYCHO_CREATENEW"] = "Crear rasgo",
	["REG_PLAYER_PSYCHO_BRUTAL"] = "Brutal",
	["REG_PLAYER_PSYCHO_CUSTOM"] = "Rasgo personalizado",
	["REG_PLAYER_PSYCHO_CUSTOMCOLOR"] = "Seleccionar color de atributo",
	["REG_PLAYER_PSYCHO_CUSTOMCOLOR_LEFT_TT"] = "Selecciona un color para la barra del atributo de la izquierda.",
	["REG_PLAYER_PSYCHO_CUSTOMCOLOR_RIGHT_TT"] = "Selecciona un color para la barra del atributo de la derecha.",
	["REG_PLAYER_PSYCHO_SELFISH"] = "Egoísta",
	["REG_PLAYER_PSYCHO_ALTRUISTIC"] = "Altruista",
	["REG_PLAYER_PSYCHO_IMPULSIVE"] = "Impulsivo",
	["REG_PLAYER_PSYCHO_FORGIVING"] = "Indulgente",
	["REG_PLAYER_PSYCHO_LEFTICON_TT"] = "Establece el icono del atributo de la izquierda",
	["REG_PLAYER_PSYCHO_LAWFUL"] = "Legal",
	["REG_PLAYER_PSYCHO_LUSTFUL"] = "Lujurioso",
	["REG_PLAYER_PSYCHO_GENTLE"] = "Pacífico",
	["REG_PLAYER_PSYCHO_PERSONAL"] = "Características personales",
	["REG_PLAYER_PSYCHO_SUPERSTITIOUS"] = "Supersticioso",
	["REG_PLAYER_PSYCHO_RENEGADE"] = "Renegado",
	["REG_PLAYER_PSYCHO_RATIONAL"] = "Racional",
	["REG_PLAYER_PSYCHO_CAUTIOUS"] = "Cauteloso",
	["REG_PLAYER_PSYCHO_VINDICTIVE"] = "Vengativo",
	["REG_PLAYER_PSYCHO_RIGHTICON_TT"] = "Establece el icono del atributo de la derecha.",
	["REG_PLAYER_PSYCHO_TRUTHFUL"] = "Sincero",
	["REG_PLAYER_PSYCHO_SOCIAL"] = "Rasgos personales",
	["REG_PLAYER_PSYCHO_DECEITFUL"] = "Embustero",
	["REG_PLAYER_PSYCHO_VALOROUS"] = "Valeroso",
	["REG_PLAYER_RACE"] = "Raza",
	["REG_PLAYER_RACE_TT"] = "Aquí va la raza de tu personaje. No está restringido a las razas jugables. Hay muchas razas del Warcraft que pueden asumir formas comunes...",
	["REG_PLAYER_REGISTER"] = "Información del directorio",
	["REG_PLAYER_RELATIONSHIP_STATUS"] = "Estado de relación",
	["REG_PLAYER_RELATIONSHIP_STATUS_DIVORCED"] = "Divorciado",
	["REG_PLAYER_RELATIONSHIP_STATUS_MARRIED"] = "Casado",
	["REG_PLAYER_RELATIONSHIP_STATUS_SINGLE"] = "Soltero",
	["REG_PLAYER_RELATIONSHIP_STATUS_TAKEN"] = "En pareja",
	["REG_PLAYER_RELATIONSHIP_STATUS_TT"] = "Indica el estado de relación de tu personaje. Selecciona \"No mostrar\" si quieres mantener esta información oculta.",
	["REG_PLAYER_RELATIONSHIP_STATUS_UNKNOWN"] = "No mostrar",
	["REG_PLAYER_RELATIONSHIP_STATUS_WIDOWED"] = "Viudo",
	["REG_PLAYER_RESIDENCE"] = "Residencia",
	["REG_PLAYER_RESIDENCE_SHOW"] = "Coordenadas de residencia",
	["REG_PLAYER_RESIDENCE_SHOW_TT"] = "Mostrar en el mapa",
	["REG_PLAYER_RESIDENCE_TT"] = [=[Aquí puedes indicar donde vive el personaje normalmente. Esta podría ser su dirección personal (su casa) o el lugar donde se hospeda.
Ten en cuenta que si tu personaje es un vagabundo, tendrás que cambiar la información.

|c00ffff00Puedes utilizar el botón de la derecha para fijar la posición actual como residencia.]=],
	["REG_PLAYER_RIGHTTRAIT"] = "Atributo derecho",
	["REG_PLAYER_SHOWMISC"] = "Mostrar marco de varios",
	["REG_PLAYER_SHOWMISC_TT"] = [=[Márcalo si quieres mostrar los campos personalizados para tu personaje.

Si no quieres mostrar los campos personalizados, mantén esta casilla sin marcar y se mantendrá totalmente oculta.]=],
	["REG_PLAYER_SHOWPSYCHO"] = "Mostrar el marco de personalidad",
	["REG_PLAYER_SHOWPSYCHO_TT"] = [=[Marca si quieres utilizar la descripción del personaje.

Si no quieres mostrar la personalidad del personaje mediante este método, mantén esta casilla sin marcar y se mantendrá totalmente oculta.]=],
	["REG_PLAYER_STYLE_DEATH"] = "Aceptación de muerte",
	["REG_PLAYER_STYLE_EMPTY"] = "Sin atributos de rol compartidos",
	["REG_PLAYER_STYLE_GUILD"] = "Miembro de hermandad",
	["REG_PLAYER_STYLE_GUILD_IC"] = "Miembro ER",
	["REG_PLAYER_STYLE_GUILD_OOC"] = "Miembro FdR",
	["REG_PLAYER_STYLE_HIDE"] = "No mostrar",
	["REG_PLAYER_STYLE_INJURY"] = "Aceptación de heridas",
	["REG_PLAYER_STYLE_PERMI"] = "Con el permiso del jugador",
	["REG_PLAYER_STYLE_ROMANCE"] = "Aceptación de romances",
	["REG_PLAYER_STYLE_RPSTYLE"] = "Estilo de rol",
	["REG_PLAYER_TITLE"] = "Título",
	["REG_PLAYER_TITLE_TT"] = [=[El título de tu personaje es el título con el que tu personaje es llamado normalmente. Evita colocar títulos largos, para ello se ha de utilizar el título completo.

Ejemplos de |c0000ff00títulos apropiados|r:
|c0000ff00- Condesa,
- Marqués,
- Mago,
- Señor,
- etc.
|rEjemplo de |cffff0000títulos inapropiados|r:
|cffff0000- Condesa de las Marismas del Norte,
- Mago de la Torre de Ventormenta,
- Diplomático de los draenei,
- etc.]=],
	["REG_PLAYER_TRP2_PIERCING"] = "Piercings",
	["REG_PLAYER_TRP2_TATTOO"] = "Tatuajes",
	["REG_PLAYER_TRP2_TRAITS"] = "Fisionomía",
	["REG_PLAYER_TUTO_ABOUT_COMMON"] = [=[|cff00ff00Tema del personaje:|r
Puedes elegir un |cffffff00tema|r para tu personaje. Piensa en ello como una |cffffff00música de ambientación para la lectura de la descripción de tu personaje.

|cff00ff00Fondo:|r
Este es el |cffffff00tipo de fondo|r para la descripción de tu personaje.

|cff00ff00Plantilla:|r
La plantilla elegida define |cffffff00las posibilidades del diseño y escritura generales|r para tu descripción.
|cffff9900Sólo la plantilla seleccionada se verá, no hace falta rellenar todas.|r
Una vez elegida la plantilla puedes volver a abrir este tutorial para tener más ayuda sobre cada plantilla.]=],
	["REG_PLAYER_TUTO_ABOUT_MISC_1"] = [=[Esta selección te ofrece |cnGREEN_FONT_COLOR:5 ranuras|r con las que se puede describir |cnGREEN_FONT_COLOR:las piezas más importantes de tu personaje|r.

Estas ranuras serán visibles en |cnGREEN_FONT_COLOR:"A primera vista"|r cuando alguien seleccione a tu personaje.]=],
	["REG_PLAYER_TUTO_ABOUT_MISC_3"] = "Esta sección contiene |cnGREEN_FONT_COLOR:una lista de notas|r para responder muchas |cnGREEN_FONT_COLOR:preguntas comunes que la gente podría preguntarse|r acerca de ti, sobre tu personaje y la forma en que deseas interpretarlo.",
	["REG_PLAYER_TUTO_ABOUT_T1"] = [=[Esta plantilla te permite |cff00ff00estructurar libremente tu descripción|r.

La descripción no tiene que limitarse a la |cffff9900descripción física|r de tu personaje. Siéntete libre para indicar parte de su |cffff9900trasfondo|r o detalles sobre su |cffff9900personalidad|r.]=],
	["REG_PLAYER_TUTO_ABOUT_T2"] = [=[Esta plantilla es más estructurada y consiste en |cff00ff00una lista de marcos independientes|r.

Cada marco se caracteriza por un |cffffff00icono, un fondo y un texto|r. Ten en cuenta que puedes utilizar algunas etiquetas de texto en estos recuadros, como el color y las etiquetas de icono de texto.

La descripción no tiene que limitarse a la descripción física|r de tu personaje. Siéntete libre para indicar parte de tu |cffff9900trasfondo|r o detalles sobre tu |cffff9900personalidad|r.]=],
	["REG_PLAYER_TUTO_ABOUT_T3"] = [=[Esta plantilla está separada en 3 secciones: |cff00ff00Descripción física, personalidad y trasfondo|r.

No hace falta llenar todos los cuadros, |cffff9900si dejas un cuadro vacío no se mostrará en tu descripción|r.

Cada cuadro se caracteriza por un |cffffff00icono, un fondo y un texto|r. Ten en cuenta que puedes utilizar algunas etiquetas de texto en estos cuadros, como el color y las etiquetas de iconos de texto.]=],
	["REG_PLAYER_TUTO_FORMATTING_TOOLS"] = "Las herramientas de formato le permiten acceder a varios |cnGREEN_FONT_COLOR:parámetros de diseño|r (tamaño del texto, color y alineación). También puede |cnGREEN_FONT_COLOR:insertar imágenes, iconos o enlaces a sitios web externo|r.",
	["REG_PLAYER_WEIGHT"] = "Complexión",
	["REG_PLAYER_WEIGHT_TT"] = [=[Esta es la complexión de tu personaje.
Por ejemplo podría ser |c0000ff00delgado, gordo o musculoso...|r ¡O simplemente podría ser normal!]=],
	["REG_PLAYERS"] = "Jugadores",
	["REG_REGISTER"] = "Directorio",
	["REG_REGISTER_CHAR_LIST"] = "Lista de personajes",
	["REG_RELATION"] = "Relación",
	["REG_RELATION_BUSINESS"] = "Negocios",
	["REG_RELATION_BUSINESS_TT"] = "%s y %s tienen una relación de negocios",
	["REG_RELATION_BUTTON_TT"] = "|cnGREEN_FONT_COLOR:Relación: %s|r|n%s",
	["REG_RELATION_BUTTON_TT_ACTIONS"] = "Mostrar las acciones posibles",
	["REG_RELATION_FAMILY"] = "Familia",
	["REG_RELATION_FAMILY_TT"] = "%s comparte un vínculo de sangre con %s.",
	["REG_RELATION_FRIEND"] = "Amistoso",
	["REG_RELATION_FRIEND_TT"] = "%s considera a %s amigo.",
	["REG_RELATION_LOVE"] = "Amor",
	["REG_RELATION_LOVE_TT"] = "%s está enamorado de %s",
	["REG_RELATION_NEUTRAL"] = "Neutral",
	["REG_RELATION_NEUTRAL_TT"] = "%s conoce a %s.",
	["REG_RELATION_NONE"] = "Ninguna",
	["REG_RELATION_NONE_TT"] = "%s no conoce a %s.",
	["REG_RELATION_TARGET"] = "Cambiar relación",
	["REG_RELATION_UNFRIENDLY"] = "Enemigo",
	["REG_RELATION_UNFRIENDLY_TT"] = "%s está enemistado con %s.",
	["REG_REPORT_PLAYER_OPEN_URL"] = [=[Solo puedes denunciar a jugadores desde el juego si los marcas como objetivo (usa el botón de marco de objetivo de TRP3).

Si quieres denunciar el perfil de %s y no puedes marcarlo como objetivo tendrás que enviar un ticket al soporte de Blizzard usando el link a continuación.]=],
	["REG_REPORT_PLAYER_OPEN_URL_160"] = "Si quieres denunciar el perfil de %s tendrás que enviar un ticket al soporte de Blizzard usando el link a continuación.",
	["REG_REPORT_PLAYER_PROFILE"] = "Denunciar perfil a |cff449fe0Blizzard|r",
	["REG_REPORT_PLAYER_PROFILE_TT"] = [=[Puedes denunciar un perfil que infrinja los Términos de Servicio de Blizzard. Esto puede incluir acoso, publicación de información privada, lenguaje de odio, contenido obsceno u otras formas de contenido inadecuado.

|cnWARNING_FONT_COLOR:Recuerda que esta opción no es para denunciar perfiles de rol de baja calidad. ¡Los abusos de esta función serán sancionados!|r]=],
	["REG_REPORT_PLAYER_TEMPLATE"] = "Este jugador está usando el perfil de rol %s del addon para compartir contenido en contra de los Términos de Servicio.",
	["REG_REPORT_PLAYER_TEMPLATE_DATE"] = "La información del addon fue transferida a través del historial de mensajes del addon en %s.",
	["REG_REPORT_PLAYER_TEMPLATE_TRIAL_ACCOUNT"] = "Este jugador tiene una cuenta de prueba.",
	["REG_TIME"] = "Última vez visto",
	["REG_TRIAL_ACCOUNT"] = "Cuenta de prueba",
	["REG_TT_GUILD"] = "%s de %s",
	["REG_TT_GUILD_IC"] = "Miembro ER",
	["REG_TT_GUILD_OOC"] = "Miembro FdR",
	["REG_TT_IGNORED"] = "<Personaje ignorado>",
	["REG_TT_IGNORED_OWNER"] = "<Propietario ignorado>",
	["REG_TT_LEVEL"] = "Nivel %s %s",
	["REG_TT_NOTIF"] = "Descripción sin leer",
	["REG_TT_REALM"] = "Reino: |cffff9900%s",
	["REG_TT_TARGET"] = "Objetivo: |cffff9900%s",
	["REG_TT_ZONE"] = "Zona",
	["SCRIPT_ERROR"] = "Error en el script.",
	["SCRIPT_UNKNOWN_EFFECT"] = "Error de script, FX desconocido",
	["SLASH_CMD_STATUS_USAGE"] = "ep || fdp || mostrar/ocultar",
	["TB_AFK_MODE"] = "Ausente",
	["TB_DND_MODE"] = "No molestar",
	["TB_GO_TO_MODE"] = "Cambiar a %s",
	["TB_LANGUAGE"] = "Idioma",
	["TB_LANGUAGES_TT"] = "Cambiar idioma",
	["TB_NORMAL_MODE"] = "Normal",
	["TB_RPSTATUS_OFF"] = "Personaje: |cnRED_FONT_COLOR:Fuera de rol|r",
	["TB_RPSTATUS_ON"] = "Personaje: |cnGREEN_FONT_COLOR:En rol|r",
	["TB_RPSTATUS_TO_OFF"] = "Cambiar a Fuera de rol",
	["TB_RPSTATUS_TO_ON"] = "Cambiar a En rol",
	["TB_STATUS"] = "Jugador",
	["TB_SWITCH_CAPE_1"] = "Mostrar capa",
	["TB_SWITCH_CAPE_2"] = "Ocultar capa",
	["TB_SWITCH_CAPE_OFF"] = "Capa: |cffff0000Oculta|r",
	["TB_SWITCH_CAPE_ON"] = "Capa: |cffff0000Mostrada|r",
	["TB_SWITCH_HELM_1"] = "Mostrar yelmo",
	["TB_SWITCH_HELM_2"] = "Ocultar yelmo",
	["TB_SWITCH_HELM_OFF"] = "Yelmo: |cffff0000Oculto|r",
	["TB_SWITCH_HELM_ON"] = "Yelmo: |cffff0000Mostrado|r",
	["TB_SWITCH_PROFILE"] = "Cambiar a otro perfil",
	["TB_SWITCH_TOOLBAR"] = "Cambiar barra de herramientas",
	["TB_TOOLBAR"] = "Barra de herramientas",
	["TF_IGNORE"] = "Ignorar jugador",
	["TF_IGNORE_CONFIRM"] = [=[¿Estás seguro que deseas ignorar esta ID?

|cffffff00%s|r

|cffff7700Opcionalmente puedes escribir debajo la razón por la que le quieres ignorar. Esta es una nota personal, no será visible por otros y servirá como recordatorio.|r]=],
	["TF_IGNORE_NO_REASON"] = "Sin razón",
	["TF_OPEN_CHARACTER"] = "Mostrar página del personaje",
	["TF_OPEN_COMPANION"] = "Mostrar página del compañero",
	["TF_OPEN_MOUNT"] = "Mostrar página de montura",
	["TF_CHAR_THEME"] = "Tema del personaje",
	["TF_CHAR_THEME_PLAY"] = "Tocar %s",
	["THANK_YOU_1"] = [=[{h1:c}Total RP 3{/h1}
{p:c}{col:6eff51}Versión %s (build %s){/col}{/p}
{p:c}{link*http://totalrp3.info*TotalRP3.info}{/p}

{h2}{icon:INV_Eng_gizmo1:20} Creado por{/h2}
- Morgane "{twitter*EllypseCelwe*Ellypse}" Parize
- Sylvain "{twitter*Telkostrasz*Telkostrasz}" Cossement


{h2}{icon:THUMBUP:20} Reconocimientos{/h2}
{col:ffffff}Logo e icono del botón del minimapa:{/col}
- {link*https://twitter.com/Kelandiir*@Kelandiir}

{col:ffffff}Nuestro equipo PR pre-alpha:{/col}
- Saelora
- Erzan
- Calian
- Kharess
- Alnih
- 611

{col:ffffff}Gracias a todos nuestros amigos por su apoyo todos estos años:{/col}
- Para Telkos: Kharess, Kathryl, Marud, Solona, Stretcher, Lisma...
- Para Ellypse: Las hermandades Maison Celwë'Belore, Mercenaires Atal'ai, y más particularmente Erzan, Elenna, Caleb, Siana and Adaeria

{col:ffffff}Por ayudarnos a crear la hermandad Total RP en Kirin Tor (EU):{/col}
- Azane
- Hellclaw
- Leylou]=],
	["THANK_YOU_ROLE_AUTHOR"] = "Autor",
	["THANK_YOU_ROLE_COMMUNITY_MANAGER"] = "Administrador de la comunidad",
	["THANK_YOU_ROLE_CONTRIBUTOR"] = "Colaborador",
	["THANK_YOU_ROLE_GUILD_MEMBER"] = "Miembro de hermandad",
	["THANK_YOU_ROLE_TESTER"] = "Control de Calidad",
	["TT_ELVUI_SKIN"] = "Skin ElvUI",
	["TT_ELVUI_SKIN_ENABLE_TARGET_FRAME"] = "Aspecto del marco de objetivo",
	["TT_ELVUI_SKIN_ENABLE_TOOLTIPS"] = "Herramientas de aspecto",
	["UI_BKG"] = "Trasfondo %s",
	["UI_CLOSE_ALL"] = "Cerrar todo",
	["UI_COLOR_BROWSER"] = "Buscador de color",
	["UI_COLOR_BROWSER_PRESETS"] = "Preselección",
	["UI_COLOR_BROWSER_PRESETS_BASIC"] = "Básico",
	["UI_COLOR_BROWSER_PRESETS_CLASSES"] = "Clase",
	["UI_COLOR_BROWSER_PRESETS_CUSTOM"] = "Personalizado",
	["UI_COLOR_BROWSER_PRESETS_ITEMS"] = "Calidad de objeto",
	["UI_COLOR_BROWSER_PRESETS_RESOURCES"] = "Recursos",
	["UI_COLOR_BROWSER_SELECT"] = "Seleccionar color",
	["UI_COMPANION_BROWSER_HELP"] = "Seleccionar compañero",
	["UI_FILTER"] = "Filtro",
	["UI_ICON_BROWSER"] = "Buscador de icono",
	["UI_ICON_SELECT"] = "Seleccionar icono",
	["UI_ICON_COPY"] = "Copiar icono",
	["UI_IMAGE_BROWSER"] = "Buscador de imagen",
	["UI_IMAGE_SELECT"] = "Seleccionar imagen",
	["UI_LINK_SAFE"] = "Aquí está el link URL.",
	["UI_LINK_TEXT"] = "Escribe aquí",
	["UI_LINK_URL"] = "http://tu.url.aqui",
	["UI_LINK_WARNING"] = [=[Aquí está el enlace URL.
Puedes copiar/pegar desde tu navegador web.

|cffff0000¡¡Atención!!|r
Total RP no es responsable de los enlaces que conducen a contenidos nocivos.]=],
	["UI_MUSIC_BROWSER"] = "Buscador de tema",
	["UI_MUSIC_DURATION"] = "Duración",
	["UI_MUSIC_SELECT"] = "Seleccionar música",
	["UI_TUTO_BUTTON"] = "Modo tutorial",
	["UI_TUTO_BUTTON_TT"] = "Activar/desactivar el modo tutorial",
	["UNIT_POPUPS_CONFIG_SHOW_OPEN_PROFILE"] = "Mostrar el botón de Abrir Perfil",
	["UNIT_POPUPS_CONFIG_VISIBILITY_HEADER"] = "Opciones de visibilidad",
	["UNIT_POPUPS_CURRENT_PROFILE"] = "Perfil Actual",
	["UNIT_POPUPS_CURRENT_PROFILE_NAME"] = "Perfil Actual: %1$s",
	["UNIT_POPUPS_OPEN_PROFILE"] = "Abrir Perfil",
	["UNIT_POPUPS_ROLEPLAY_OPTIONS_HEADER"] = "Opciones de Roleplay"
};

TRP3_API.loc:RegisterNewLocale("esES", "Español (EU)", L);
