-- Copyright The Total RP 3 Authors
-- SPDX-License-Identifier: Apache-2.0

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- ALL MODIFICATIONS TO THIS FILE WILL BE LOST.

local _, TRP3_API = ...;

local L;

L = {
	["ABOUT_TITLE"] = "Acerca de",
	["BW_COLOR_CODE"] = "Código de color",
	["BW_COLOR_CODE_ALERT"] = "¡Código hexadecimal erróneo!",
	["BW_COLOR_PRESET_SAVE"] = "Guardar color actual",
	["CL_IMPORT_PROFILE"] = "Importar perfil",
	["CM_ACTIONS"] = "Acciones",
	["CM_APPLY"] = "Aplicar",
	["CM_CANCEL"] = "Cancelar",
	["CM_CENTER"] = "Centro",
	["CM_CLASS_DEATHKNIGHT"] = "Caballero de la muerte",
	["CM_CLASS_DRUID"] = "Druida",
	["CM_CLASS_HUNTER"] = "Cazador",
	["CM_CLASS_MAGE"] = "Mago",
	["CM_CLASS_MONK"] = "Monje",
	["CM_CLASS_PALADIN"] = "Paladín",
	["CM_CLASS_PRIEST"] = "Sacerdote",
	["CM_CLASS_ROGUE"] = "Pícaro",
	["CM_CLASS_SHAMAN"] = "Chamán",
	["CM_CLASS_UNKNOWN"] = "Desconocido",
	["CM_CLASS_WARLOCK"] = "Brujo",
	["CM_CLASS_WARRIOR"] = "Guerrero",
	["CM_CLICK"] = "Click",
	["CM_COLOR"] = "Color",
	["CM_DRAGDROP"] = "Arrastrar y soltar",
	["CM_ICON"] = "Icono",
	["CM_IMAGE"] = "Imagen",
	["CM_LEFT"] = "Izquierda",
	["CM_LINK"] = "Enlace",
	["CM_NAME"] = "Nombre",
	["CM_RIGHT"] = "Derecha",
	["CM_UNKNOWN"] = "Desconocido",
	["CO_ANCHOR_LEFT"] = "Izquierda",
	["CO_ANCHOR_RIGHT"] = "Derecha",
	["COM_LIST"] = "Lista de comandos:",
	["GEN_WELCOME_MESSAGE"] = "¡Gracias por usar Total RP 3 (v %s)! ¡Diviértase!"
};

TRP3_API.loc:RegisterNewLocale("esES", "Español (EU)", L);
