-- Copyright The Total RP 3 Authors
-- SPDX-License-Identifier: Apache-2.0

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- ALL MODIFICATIONS TO THIS FILE WILL BE LOST.

local _, TRP3_API = ...;

local L;

L = {
	["ABOUT_TITLE"] = "À propos",
	["BW_COLOR_CODE"] = "Code couleur",
	["BW_COLOR_CODE_ALERT"] = "Mauvais code hexadécimal !",
	["BW_COLOR_PRESET_SAVE"] = "Enregistrer cette couleur",
	["BW_COLOR_PRESET_TITLE"] = "Couleurs enregistrées",
	["CL_IMPORT_PROFILE"] = "Importer le profil",
	["CM_ACTIONS"] = "Actions",
	["CM_APPLY"] = "Appliquer",
	["CM_CANCEL"] = "Annuler",
	["CM_CENTER"] = "Centre",
	["CM_CLASS_DEATHKNIGHT"] = "Chevalier de la mort",
	["CM_CLASS_DRUID"] = "Druide",
	["CM_CLASS_HUNTER"] = "Chasseur",
	["CM_CLASS_MAGE"] = "Mage",
	["CM_CLASS_MONK"] = "Moine",
	["CM_CLASS_PALADIN"] = "Paladin",
	["CM_CLASS_PRIEST"] = "Prêtre",
	["CM_CLASS_ROGUE"] = "Voleur",
	["CM_CLASS_SHAMAN"] = "Chaman",
	["CM_CLASS_UNKNOWN"] = "Inconnu",
	["CM_CLASS_WARLOCK"] = "Démoniste",
	["CM_CLASS_WARRIOR"] = "Guerrier",
	["CM_CLICK"] = "Clic",
	["CM_COLOR"] = "Couleur",
	["CM_DRAGDROP"] = "Glisser-déposer",
	["CM_ICON"] = "Icône",
	["CM_IMAGE"] = "Image",
	["CM_LEFT"] = "Gauche",
	["CM_LINK"] = "Lien",
	["CM_NAME"] = "Nom",
	["CM_RIGHT"] = "Droite",
	["CM_UNKNOWN"] = "Inconnu",
	["CO_ANCHOR_LEFT"] = "Gauche",
	["CO_ANCHOR_RIGHT"] = "Droite",
	["COM_LIST"] = "Liste des commandes :",
	["GEN_WELCOME_MESSAGE"] = "Merci d'utiliser Total RP 3 (v %s) ! Amusez-vous bien !"
};

TRP3_API.loc:RegisterNewLocale("frFR", "Français", L);
