-- Copyright The Total RP 3 Authors
-- SPDX-License-Identifier: Apache-2.0

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- ALL MODIFICATIONS TO THIS FILE WILL BE LOST.

local _, TRP3_API = ...;

local L;

L = {
	["ABOUT_TITLE"] = "Di",
	["BW_COLOR_CODE"] = "Codice colore",
	["BW_COLOR_CODE_ALERT"] = "Codice esadecimale sbagliato!",
	["BW_COLOR_PRESET_SAVE"] = "Salva il colore corrente",
	["BW_COLOR_PRESET_TITLE"] = "Impostazioni colore",
	["CL_IMPORT_PROFILE"] = "Importa profilo",
	["CM_ACTIONS"] = "Azioni",
	["CM_APPLY"] = "Applicare",
	["CM_CANCEL"] = "Annullare",
	["CM_CENTER"] = "Centrare",
	["CM_CLASS_DEATHKNIGHT"] = "Cavalliere della Morte",
	["CM_CLASS_DRUID"] = "Druido",
	["CM_CLASS_HUNTER"] = "Cacciatore",
	["CM_CLASS_MAGE"] = "Mago",
	["CM_CLASS_MONK"] = "Monaco",
	["CM_CLASS_PALADIN"] = "Paladino",
	["CM_CLASS_PRIEST"] = "Sacerdote",
	["CM_CLASS_ROGUE"] = "Ladro",
	["CM_CLASS_SHAMAN"] = "Sciamano",
	["CM_CLASS_UNKNOWN"] = "Sconosciuto",
	["CM_CLASS_WARLOCK"] = "Stregone",
	["CM_CLASS_WARRIOR"] = "Guerriero",
	["CM_CLICK"] = "Clic",
	["CM_COLOR"] = "Colore",
	["CM_DRAGDROP"] = "Trascinare e rilasciare",
	["CM_ICON"] = "Icona",
	["CM_IMAGE"] = "Immagine",
	["CM_LEFT"] = "Sinistra",
	["CM_LINK"] = "Link",
	["CM_NAME"] = "Nome",
	["CM_RIGHT"] = "Destra",
	["CM_UNKNOWN"] = "Sconosciuto",
	["CO_ANCHOR_LEFT"] = "Sinistra",
	["CO_ANCHOR_RIGHT"] = "Destra",
	["COM_LIST"] = "Lista di comandi:",
	["GEN_WELCOME_MESSAGE"] = "Grazie per aver scelto Total RP 3 (v% s)! Divertiti!"
};

TRP3_API.loc:RegisterNewLocale("itIT", "Italiano", L);
