-- Copyright The Total RP 3 Authors
-- SPDX-License-Identifier: Apache-2.0

TRP3_InterfaceSounds = {
	BrowserClose = SOUNDKIT.IG_ABILITY_CLOSE,
	BrowserOpen = SOUNDKIT.IG_ABILITY_OPEN,
	ButtonClick = SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON,
	DragDrop = SOUNDKIT.IG_ABILITY_ICON_DROP,
	DragPickup = 837,
	MenuClose = SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_OFF,
	MenuOpen = SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON,
	PageChange = SOUNDKIT.IG_ABILITY_PAGE_TURN,
	PopupClose = SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON,
	WindowClose = SOUNDKIT.IG_MAINMENU_CLOSE,
	WindowOpen = SOUNDKIT.IG_CHARACTER_INFO_TAB,
	MainWindowOpen = SOUNDKIT.ACHIEVEMENT_MENU_OPEN or SOUNDKIT.IG_CHARACTER_INFO_TAB,
	MainWindowClose = SOUNDKIT.ACHIEVEMENT_MENU_CLOSE or SOUNDKIT.IG_MAINMENU_CLOSE,
};
