#!/bin/bash
set -euo pipefail

declare cf_api_token="${CF_API_KEY}"
declare cf_project_id=75973
declare cf_localization_url="https://wow.curseforge.com/api/projects/${cf_project_id}/localization/export"
declare cf_localization_opts="&export-type=Table&unlocalized=Ignore"

fetch_locale() {
	local lang="$1"

	curl -sfH "X-API-Token: ${cf_api_token}" --retry 5 --retry-delay 5 \
		"${cf_localization_url}?lang=${lang}${cf_localization_opts}"
}

generate_locale() {
	local lang="$1"
	local name="$2"

	cat <<EOF
-- Copyright The Total RP 3 Authors
-- SPDX-License-Identifier: Apache-2.0

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- ALL MODIFICATIONS TO THIS FILE WILL BE LOST.

local L;

EOF

	fetch_locale "$lang"

cat <<EOF


TRP3_API.loc:RegisterNewLocale("$lang", "$name", L);
EOF
}

generate_locale "deDE" "Deutsch" > totalRP3/Locales/deDE.lua
generate_locale "enUS" "English" > totalRP3/Locales/enUS.lua
generate_locale "esES" "Español (EU)" > totalRP3/Locales/esES.lua
generate_locale "esMX" "Español (AL)" > totalRP3/Locales/esMX.lua
generate_locale "frFR" "Français" > totalRP3/Locales/frFR.lua
generate_locale "itIT" "Italiano" > totalRP3/Locales/itIT.lua
generate_locale "koKR" "한국어" > totalRP3/Locales/koKR.lua
generate_locale "ptBR" "Português" > totalRP3/Locales/ptBR.lua
generate_locale "ruRU" "Pусский" > totalRP3/Locales/ruRU.lua
generate_locale "zhCN" "简体中文" > totalRP3/Locales/zhCN.lua
generate_locale "zhTW" "繁體中文" > totalRP3/Locales/zhTW.lua
