---
name: Import External Translations
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: {}

jobs:
  build:
    if: github.repository_owner == 'Total-RP'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-translations

      - name: Import External Translations
        run: just translations-import
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Import External Translations
          branch: actions/import-external-translations
          delete-branch: true
          title: Import External Translations
          body: Automated import of external translation strings.
          author: GitHub <noreply@github.com>
          reviewers: Meorawr, Solanya

      - name: Send Webhook Notification
        if: failure()
        uses: ./.github/actions/send-webhook-notification
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
