---
name: Package (Release)
on:
  push:
    tags:
      - '*'
      - '!**-alpha**'
      - '!**-beta**'

jobs:
  build:
    if: github.repository_owner == 'Total-RP'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Create Package
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

      - name: Send Webhook Notification
        if: failure()
        uses: ./.github/actions/send-webhook-notification
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
