---
name: Process CurseForge Translations
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Upload CurseForge Translations
        run: make translations/upload
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Download CurseForge Translations
        run: make translations/download
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Import CurseForge Localization
          branch: actions/import-cf-localization
          delete-branch: true
          title: Import CurseForge Localization
          body: Automated import of CurseForge localization.
          author: GitHub <noreply@github.com>
          reviewers: Meorawr, Solanya

      - name: Send Webhook Notification
        if: failure()
        run: |
          git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        env:
          JOB_STATUS: ${{ job.status }}
          HOOK_OS_NAME: ${{ runner.os }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WORKFLOW_NAME: ${{ github.workflow }}
